eclipse-sw360/sw360

README.md
frontend/sw360-theme/src/main/webapp/templates/portal_normal.vm
pom.xml
rest/resource-server/src/docs/asciidoc/api-guide.adoc
rest/resource-server/src/docs/asciidoc/index.adoc

- REST API Documentation welcome page (issues, link)
- REST API Documentation users (link)
- sw360Portal footer (liferay, link to issue tracker)
- travis results (readme)
closes eclipse/sw360#3

chore(config): Change sw360portal specific links because of new repository

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/AttachmentStreamConnector.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissions.java

- add complete attachments to source bundle generation (zip file)
closes eclipse/sw360#1

fix(attachments): Allows to set attachments for source bundle generation

---

backend/src-common/src/main/resources/sw360.properties

- add missing sw360.properties to sw360 project
closes eclipse/sw360#89

chore(config): Restore sw360.properties configuration file

---

backend/src/src-fossology/src/main/java/org/eclipse/sw360/fossology/ssh/FossologyUploader.java
libraries/lib-datahandler/src/main/thrift/projects.thrift

- remove default value for `clearingTeam` = `Unknown`
closes eclipse/sw360#282

chore(projects): Remove default value for clearingTeam in projects

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/datatables/DataTablesParser.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/datatables/DataTablesUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/datatables/PaginationParser.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/datatables/data/PaginationParameters.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/webapp/css/dataTable_Siemens.css
frontend/sw360-portlet/src/main/webapp/css/dataTable_SiemensHomepage.css
frontend/sw360-portlet/src/main/webapp/html/components/view.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/common/datatables/DataTablesParserTest.java

- proof of concept implementation
- supports pagination for component and project view
closes eclipse/sw360#243

feat(ui): Pagination of entries in project and component view

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/webapp/html/components/edit.jsp
frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
frontend/sw360-portlet/src/main/webapp/html/utils/includes/editExternalIds.jsp

- keys can be configured in the etc/sw360 properties file
- project configuration: project.externalkeys
- component configuration: component.externalkeys
- release configuration: release.externalkeys
closes eclipse/sw360#221

feat(ui): Add preferred external id keys for projects, components and releases

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java

Show release summary if the search text is empty
closes eclipse/sw360#293

fix(releases): Show release summary if the search text is empty

---

backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ComponentModerationRequestGenerator.java
backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ProjectModerationRequestGenerator.java

- fixed for projects and components
- external id changes will be visible in basic fields
closes eclipse/sw360#295

fix(moderation): Add external id map to moderation request

---

frontend/sw360-portlet/src/main/webapp/html/moderation/view.jsp

fix footer length (width) in moderation view
closes eclipse/sw360#297

chore(moderation): Adjust footer length with datatable width (columns)

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java

- fix the null pointer exception in case of merging licenseInfo objects.
closes eclipse/sw360#315

fix(licenseinfo): Update merge handling for licenseInfo objects

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/VendorSearchHandler.java
backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
build-configuration/resources/couchdb.properties
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/datatables/PaginationParser.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/datatables/data/PaginationParameters.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/webapp/html/components/view.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
frontend/sw360-portlet/src/main/webapp/html/utils/includes/searchReleases.jsp
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/DatabaseSettings.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
libraries/lib-datahandler/src/main/thrift/vendors.thrift

- improves the lucene search result logic
- disable automatic column order in case of advanced searches
This pull request enables leading wildcard search for lucene.
_(Note: this is a really expensive operation)_
**How-to enable leading wildcard search:**
> _build-configuration/resources/couchdb.properties_
> lucenesearch.leading.wildcard = true
> _couchdb-lucene.ini (is part of the couchdb-lucene .war package)_
>  [lucene]
>  allowLeadingWildcard=true
closes eclipse/sw360#322

feat(search): Improve lucene search logic and handling of results

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java

Signed-off-by: hengel2810 <henrik.engelbrink@bosch-si.com>

feat(rest) Route PATCH /component/{id} added to update an existing component

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/MultiStatus.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/TestHelper.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java

Signed-off-by: hengel2810 <henrik.engelbrink@bosch-si.com>

feat(rest) Batch-Deletion for components

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/TestHelper.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ReleaseTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

Signed-off-by: Henrik Engelbrink <henrik.engelbrink@bosch-si.com>

feat(rest) Added route DELETE /releases/{ID},{ID2} to delete releases

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

Shows again sw360:attachments array for releases (also projects and components)

fix(rest): Show attachments as embedded resource list

---

backend/src-common/src/test/java/org/eclipse/sw360/components/summary/ProjectSummaryTest.java
frontend/sw360-portlet/src/main/webapp/html/projects/includes/detailOverview.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/vulnerabilities.jspf
libraries/lib-datahandler/src/main/thrift/projects.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java

some users do not want to reveal vuls to their project.

feat(projects): add a flag to enable/disable displaying project's vulnerabilities

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/PaginationOptions.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/PaginationResult.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceListController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/resources/application.yml
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java

This PR will remove the default paging if there are no paging parameters in the `GET /{resources}` request.

fix(rest): GET /{resources} response will contain all resources if there are no paging parameters in the request

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyProjectsPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayAcceptedReleases.java
frontend/sw360-portlet/src/main/webapp/WEB-INF/customTags.tld
frontend/sw360-portlet/src/main/webapp/html/homepage/myprojects/view.jsp

This PR adds accepted releases column to MyProjects portlet.
Let's test the performance of this feature first and if necessary lets't do modifications.
Signed-off-by: Kalle Soranko <ksoranko@verifa.io>

feat(homepage): show accepted releases in MyProjects portlet

---

frontend/sw360-theme/src/main/webapp/css/custom.css
frontend/sw360-theme/src/main/webapp/js/supportedBrowser.js
frontend/sw360-theme/src/main/webapp/templates/portal_normal.vm

- display banner warning for Internet Explorer usage

chore(ui): Display banner warning for IE

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java

- Project Version should be included in the lucene wildcard query

chore(ui): Improve lucene search logic for project version

---

frontend/sw360-portlet/pom.xml
frontend/sw360-portlet/src/main/webapp/html/components/includes/components/clearingStatus.jspf
frontend/sw360-portlet/src/main/webapp/html/utils/includes/requirejs.jspf

- Set the sort order of all releases by release version
closes eclipse/sw360#325

chore(components): Change default sort order for release overview

---

frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseClearingInformation.jspf
frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
frontend/sw360-portlet/src/main/webapp/html/preferences/view.jsp
frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/administrationEdit.jspf

Month and year selection is made available in datepicker.

fix(ui): datepicker date and year selection is made available

---

pom.xml

refactor(db-bridge): updated ektorp library version to current 1.5.0

---

README.md

- Change Thrift Version in Readme

chore(rm): Change Thrift Version in Readme

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java

During the license info generation of the project, added the project version string to the generated file title along with date and time of creation of the file.
Closes #234

feat(license-info): Add version string to file name

---

rest/authorization-server/pom.xml
rest/resource-server/pom.xml

Added security label changes to build files.
Changed the plugin repository urls from http to https.
closes: #500

fix: Security changes in source code

---

backend/src/pom.xml
backend/src/src-codescoop/pom.xml
backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/CodescoopConfig.java
backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/CodescoopHandler.java
backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/CodescoopServlet.java
backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/CodescoopSpringServlet.java
backend/src/src-codescoop/src/main/java/org/eclipse/sw360/codescoop/ModelTranslator.java
backend/src/src-codescoop/src/main/resources/codescoop.properties
backend/svc/pom.xml
backend/svc/svc-codescoop/pom.xml
backend/svc/svc-codescoop/src/main/webapp/WEB-INF/web.xml
backend/svc/svc-codescoop/src/main/webapp/index.jsp
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/resources/sw360.properties
frontend/sw360-portlet/src/main/webapp/html/components/detail.jsp
frontend/sw360-portlet/src/main/webapp/html/components/edit.jsp
frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
frontend/sw360-portlet/src/main/webapp/html/components/includes/components/clearingStatus.jspf
frontend/sw360-portlet/src/main/webapp/html/components/includes/components/editBasicInfo.jspf
frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
frontend/sw360-portlet/src/main/webapp/html/components/view.jsp
frontend/sw360-portlet/src/main/webapp/js/modules/codeScoop.js
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftClients.java
libraries/lib-datahandler/src/main/thrift/codescoop.thrift

Codescoop integration:
1. Maven profile to enable Codescoop inside sw360
2. Thrift Service for CodescoopHandler servlet
3. OSMAN dependency for API access
4. Purl integration for matching components between systems

feat(codescoop): osman integration

---

rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

- Added the dcumentation for linking releases to the project.
- Updated the documentation for creating the project with linked project and linked release.

feat(REST-Doc): Updated the REST API Documentation

---

rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

-Added update project rest end point.
-Updated the Rest API documentation for the same.
closes: #569

feat(Rest-Project) : Added possibility to update project from rest endpoint.

---

scripts/migrations/011_migrate_attachment_usages_license_info.py
scripts/migrations/README.md

* added a script that migrates attachment usages of type LICENSE_INFO to
match the new version introduced in eclipse/sw360#508
This is a improvement to the changes of eclipse/sw360#483

feat(licenseInfoMigration): added manual migration script for license infos

---

backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/entitytranslation/WsLibraryToSw360ComponentTranslator.java
backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/entitytranslation/WsLibraryToSw360ReleaseTranslator.java
backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/entitytranslation/WsLicenseToSw360LicenseTranslator.java
backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/rest/WsImportService.java
backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/rest/WsRestClient.java
backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/thrift/ThriftUploader.java
backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/utility/TranslationConstants.java

* Setting OSS as component type
* Keep "Suspected" in license name if it is there
* Catch `HttpException` in the rest call 
* Small refactoring

fix(wsimport): small fixes, refactoring and improvements

---

rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/Sw360LicenseInfoService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

* Fixed the issue with download license information file rest endpoint and added the documentation for the same. 
closes: #575 

fix(rest): Download licenseinfo file rest endpoint.

---

backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/CveSearchApiImpl.java
backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/CveSearchGuesser.java
backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/json/CveSearchJsonParser.java
backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/json/ListCveSearchJsonParser.java
backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/json/SingleCveSearchJsonParser.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/TestWithCveSearchConnection.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/CveSearchApiImplTest.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/CveSearchGuesserTest.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/CveSearchWrapperTest.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/json/CveSearchJsonParserTest.java
backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/entitytranslation/CveSearchDataTranslatorTest.java

this should fix https://github.com/eclipse/sw360/issues/592
the line disabling the tests is: https://github.com/eclipse/sw360/pull/593/files#diff-a160378f662a9d3ddb8a062609ffac05R36
current state: ~~waiting for travis.~~ travis is green.

fix(cve-search): disable tests by assume statement and refactor

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/UserPortlet.java

fix(user export): fix Nullpointer Exception on user export

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java

*  Fixed the bug w.r.t title field while adding the TODOs to the licenses.
closes: #599

fix(license-todo): Adding TODOs to License

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/AbstractTasksPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyTaskAssignmentsPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyTaskSubmissionsPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/css/utils/_badges.scss
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/clearingDetails.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/detailOverview.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/ajax/sendableTable.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/import.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/linkedProjectsEdit.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp

This PR contains changes to resolve the feedback from PR #610.

chores(liferay): Feedback from Liferay 7 review

---

CHANGELOG.md
pom.xml

and also added a changelog file

changing release tag for tagging 5.0.0-M1

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java

- Added validation for default vendor id. 
Closes: #647

fix(rest): Fixed get component API having default vendor id as empty

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java

Currently create project request from rest end point is returning `500 internal server error` as error response. 
Data is getting saved successfully in backend however while formulating the HATEOAS data it was failing.  Added the necessary fix for the same. 
Closes : #670

fix(REST Project) : Fixed error response for create project from rest

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
backend/src/src-licenseinfo/src/main/resources/textLicenseInfoFile.vm

- Acknowledgements have been added in the TEXT and DOCx format disclosure documents which was missing earlier.
closes: #369 
closes: #674

fix(licenseDisclosure): Added acknowledgements in TEXT and DOCX format

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/vulnerabilities/view.jsp

Vulnerability tab was not getting loaded due to a minor java script issue.

fix(vulnerability): Vulnerability tab loading issue

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
frontend/liferay-theme/src/main/webapp/css/_clay_variables.scss
frontend/sw360-portlet/src/main/resources/META-INF/resources/css/main.scss
frontend/sw360-portlet/src/main/resources/META-INF/resources/css/portlets/admin/_buttons.scss

* Merging complex fields
This commits fixes the merge of the two complex fields 'external ids' and
'additional data' in components.
* Style impprovements
Layout and style of merge wizard have been improved. Style for DisplayMap
(for external ids and additonal data) has been improved.
Closes #596

fix(merge): allow merging of complex fields, style improvements

---

CHANGELOG.md
pom.xml

Just doing two things:
* adding entry to changelog.md
* changing variable in `pom.xml`

chore(release): making files for 5.1.0-M1

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsagesRows.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedProjectsRows.jspf

* Corrected the release link under sub-projects.
closes #696 

fix(links): Fixed the incorrect links

---

rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360AuthorizationServerConfiguration.java
rest/authorization-server/src/main/resources/application.yml

1. Added support to read jwt-keystore.jks file from etc/sw360 folder, if not found then it will search from default project resource path. 
2. Read keystore secret key from application.yml . 
closes: #691

feat(Authorization): Added support to read keystore from central configuration

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/sw360Wizard.js

Component merge was not working due error in Json parsing.
Issue Fixed.

fix(component): component merge not working

---

backend/src-common/src/main/java/org/eclipse/sw360/common/utils/BackendUtils.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java

fix(projectUI): NPE in ProjectDatabaseHandler.setReleaseRelations

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
libraries/lib-datahandler/src/main/thrift/projects.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java

prevent cyclic link in linked projects while updating or creating new project
closes: #546 

fix(project): prevent cyclic link in linked projects

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
libraries/lib-datahandler/src/main/thrift/sw360.thrift

Add checking naming component error and error message.
Issue #556
Signed-off-by: Pham Le Trung <trung.phamle@toshiba-tsdv.com>

fix(Components): Fix naming component error (component's name contains only space characters)

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java

This change will only applicable when copying the projects.
closes: #280 

fix(project): Keep project mainline state as it is while cloning/creating project

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/linkedProjects.jspf

Options are added to generate LicenseInfo and SourceCodeBundle for main project only or main project with subprojects.

fix(ProjectUI): Added options to generate ReadmeOSS for main project only or main project with subprojects.

---

rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

Added parameter to GET project by Group and Tag

feat(REST): Added parameter to GET project by Group and Tag

---

CHANGELOG.md
pom.xml

just changing files for release 6.0.0-M1:
* pom.xml with change of the release variable
* CHANGELOG.md with changes since last release 5.1.0-M1

chore(release): making files for 6.0.0-M1

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
backend/src/src-projects/src/test/java/org/eclipse/sw360/projects/ProjectHandlerTest.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyProjectsPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/myprojects/view.jsp
libraries/lib-datahandler/src/main/thrift/projects.thrift
libraries/lib-datahandler/src/main/thrift/users.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java

Listing of MyProjects in Homepage is made configurable . 
User can select the Roles [creator,moderator,Contributor,Project Owner,Lead Architect, Project responsible, Security responsible] from the dropdown based on which the projects will be listed.

feat(HomePageUI): Listing of MyProjects is made configurable

---

rest/resource-server/src/docs/asciidoc/releases.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

Added request parameter to GET release by name

feat(REST): Add parameter to GET release by name

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/AttachmentPortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
libraries/commonIO/src/main/java/org/eclipse/sw360/commonIO/AttachmentFrontendUtils.java

fix(licenseinfo): White page while downloading license disclosure

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentAwareDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/FossologyAwarePortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/editRelease.jsp
libraries/lib-datahandler/src/main/thrift/components.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java

Prevent cyclic link in linked releases while updating or creating new release from UI or REST.
Add recursive check for REST API - get all releases including linked release for a project
closes: #733 

fix(ReleaseUI/REST): prevent cyclic link in release

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java

fix(ProjectUI): fixed 'Project is temporarily unavailable' issue due to obligation feature

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayVendorEdit.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/css/main.scss
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/bulkReleaseEdit/view.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/edit.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/editRelease.jsp

Once selected and saved a vendor user had no choice to remove it, user can only select another vendor.
Added button to remove selected vendor for component and release

feat(Component/ReleaseUI): Added button to remove selected vendor for component and release

---

scripts/migrations/015_update_fullmyprojects_view.py
scripts/migrations/README.md
scripts/utilities/002_update_view.py
scripts/utilities/README.md

Script to update couchdb views.
Following variables needs to be updated based on requirement
`doc_id` = "Document_ID"
`nested_field_key` = ["key1", "nestedKey2", "nestedKey3"]
`newValue` = "new_value"
Ex - to update `"views" -> "fullmyprojects" -> "map"` key in  `"_design/Project"`
`doc_id` = "_design/Project"
`nested_field_key` = ["views", "fullmyprojects", "map"]

feat(updateViewScript): Script to update Views.

---

CHANGELOG.md
pom.xml

Just adding the files for mile stone release 7.0.0
* pom.xml
* CHANGELOG.md
I think if auto checks are good, it is good.

Feat/release7: just doing the files for M1-7.0.0

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp

see also:
- https://github.com/eclipse/sw360/commit/df54014729a05e977095c187f65ce7f0d22f433f#commitcomment-36950304
- https://github.com/eclipse/sw360/issues/762

fix(ui): fix issue #762, introduced in df5401472

---

README.md

Just a selection of badges to have some more bling bling instead of the just single "building" badge. 
Is it an improvement?

Adding some more badges to the readme.

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf

fix(ProjectUI: fixed blank / non-responsive screen on project attachment tab

---

CHANGELOG.md
README.md
pom.xml

Release fixes two bugs in 7.0.0-M1
* a lost character in some file has damaged a view
* depending on context a pop-up dialogue to enter values to not render
This PR changes files accordingly for 7.0.1-M1 in order to tag

Updating files for release 7.0.1-M1

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java

fix(ui): saving attachment usage issue for source code bundle and others

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/PropertyKeyMapping.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/serializer/JsonInstantSerializer.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/serializer/JsonProjectRelationSerializer.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/serializer/JsonReleaseRelationSerializer.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/LicenseInfoController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/apiToken/ApiTokenAuthenticationProvider.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/keycloak/KeycloakAccessTokenConverter.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/configuration/security/Sw360AuthorizationServerConfiguration.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

Removing unneeded Exceptions, reformatting stream().forEach() to
only for forEach(), removing unnecessary variable assignments and
some other minor clean up.

Clean up some warning in the code

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_tooltips.scss
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
libraries/lib-datahandler/src/main/thrift/components.thrift
libraries/lib-datahandler/src/main/thrift/sw360.thrift
rest/resource-server/src/docs/asciidoc/components.adoc

Added new project release relation `Code Snippet` for source code snippets

feat(AddProjectReleaseRelation): add a project release relation for source code snippets

---

.travis/testForLicenseHeaders.sh
backend/src-common/pom.xml
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/spdx/SpdxBOMImporter.java
backend/src-common/src/main/java/org/eclipse/sw360/spdx/SpdxBOMImporterSink.java
backend/src-common/src/test/java/org/eclipse/sw360/spdx/SpdxBOMImporterTest.java
backend/src-common/src/test/resources/bom.spdx
backend/src-common/src/test/resources/bom.spdx.rdf
backend/src/src-attachments/src/main/java/org/eclipse/sw360/attachments/AttachmentHandler.java
backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/attachmentsUpload.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/importBom.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/includes/attachmentsUpload.js
libraries/lib-datahandler/src/main/thrift/components.thrift
libraries/lib-datahandler/src/main/thrift/projects.thrift

This PR adds the BOM import functionallity for projects and releases.
[example.spdx.rdf](https://github.com/eclipse/sw360/files/3646100/example.spdx.rdf.txt)
```
SPDXVersion: SPDX-2.1
DataLicense: CC0-1.0
DocumentNamespace: http://www.spdx.org/spdxdocs/8f141b09-1138-4fc5-aecb-fc10d9ac1eed
DocumentName: SBOM toy exaple
SPDXID: SPDXRef-DOCUMENT
Creator: Organization: NTIA Standards and Formats Workgroup
Created: 2019-08-31T11:29:46Z
Relationship: SPDXRef-DOCUMENT DESCRIBES SPDXRef-asoftware-v1.1
PackageName: asoftware
SPDXID: SPDXRef-asoftware-v1.1
PackageVersion: 1.1
PackageSupplier: Organization: Acme
PackageDownloadLocation: NOASSERTION
FilesAnalyzed: false
PackageChecksum: SHA1: 75068c26abbed3ad3980685bae21d7202d288317
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: …
```

Add spdx bom import functionality

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/helper/ReleaseHelper.java

fix(spreadsheet-export): fixed the sequence of values based on headers

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesRelationAjax.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editLinkedReleases.jspf

Fixed missing functionality of button to delete release to release relation in Edit Release Page.
closes: #773 

fix(EditReleaseUI): Fixed missing functionality of button to delete release to release relation.

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
scripts/migrations/016_update_byExternalIds_component_view.py
scripts/migrations/README.md

Fixed search component by external id ,REST endpoint.

fix(REST): fixed search component by external id

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentAwareDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src/src-projects/src/test/java/org/eclipse/sw360/projects/ProjectHandlerTest.java
libraries/lib-datahandler/src/main/thrift/projects.thrift
libraries/lib-datahandler/src/main/thrift/sw360.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java

feat(rest): validate the dependent document ids in the payload before updating it in the DB

---

CHANGELOG.md
pom.xml

somehow my key works again ... please find attached the changes for the new release 8.

chore(release): changing pom.xml and changelog for rel 8

---

CHANGELOG.md
README.md
pom.xml

yes, and because we found a bug which is worth to release a patch level release.
It fixes creating releases from the UI.

chore(release): chaging files, readme, pom, changelog for 8.0.1

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/vulnerabilities.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/vulnerabilities/view.jsp

* Added the check for title field as well for safety.

fix(vulerability): vulnerability view breaks at backslash in desc.

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligations.jspf
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
libraries/lib-datahandler/src/main/thrift/sw360.thrift

Added new status fields for Obligation.
- Not Applicable
- To be fulfilled by parent project

feat(ObligationUI): Added new status fields for Obligation.

---

backend/src/src-fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
backend/src/src-fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java
libraries/lib-datahandler/src/main/thrift/fossology.thrift
libraries/lib-datahandler/src/main/thrift/sw360.thrift
rest/resource-server/src/docs/asciidoc/releases.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

- Added REST endpoint to Trigger FOSSology process for a release.
- Added REST endpoint to check status of FOSSology process.

feat(REST): Trigger FOSSology process and check status.

---

.github/pull_request_template.md

This introduces a pull request template that metions:
- summary
- issue reference
- reviewer suggestion
- question of how to test
Issue: #801
This can not be tested.

Add pull request tempalte and .github folder

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/vendors/mergeVendor.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeComponent.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeRelease.jsp

> Merge of component, release, vendor - `choose source page` , gives JS error which blocks user to proceed to next step
> * Which issue is this pull request belonging to and how is it solving it? (*#826*)
> Try to merge Component, Release or Vendor
> No additional tests were implemented

fix(mergeUI): Provided fix for error message on merge component, release, vendor - choose source page

---

CHANGELOG.md
README.md
pom.xml

Changing for release 8.2-m1:
* pom file for artefacts generation
* changelog for describing it
will be merged after ci runs through

chore(release): updating pom.xml and changelog for 8.2 release

---

frontend/sw360-portlet/bnd.bnd
frontend/sw360-portlet/pom.xml
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/components/BuildInfoTemplateContextContributor.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/components/DynamicComponentManager.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/components/FossologyCheckConnectionOnStartupHook.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/LoginAction.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/LogoutAction.java
frontend/sw360-portlet/src/main/resources/sw360.properties

* Added a post logout hook which can be used to write any custom logic post logout such as redirecting to a custom logout page, integrating or invalidating third party auth cookies viz. mod-mellon, invalidating session etc.
* Fixed dynamically activation of components via `components.activate` of `sw360.properties`. 
* Added `Clear-Site-Data` response header upon logout to clear cookies, storage and cache
Enable the `LogoutAction` hook/component in sw360.properties.
Verify the browser cookies, cache, and …

feat(logout): Added post logout hook to add custom logic

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/RelationsUsageRepository.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/LinkedReleasesAndProjectsAwarePortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/licenseInfo.jsp
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
libraries/lib-datahandler/src/main/thrift/projects.thrift

> Exclude Linked Project from ReadmeOss generation based on project relation selection
> * Which issue is this pull request belonging to and how is it solving it? (*#832*)
> Click on `Generate LicenseInfo with subprojects`, click on Download ,uncheck Project relation which needs to be excluded
Must:

feat(ReadmeOss): Filter linked project from ReadmeOss based on selection.

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseMixInForChangeLog.java

> Fixed missing fields like componentType in Changelog history.
* Added generic isChanged check for field type TEnum, TBase.
* Added RepositoryMixin to ignore unwanted fields in Repository field of Release
> * Which issue is this pull request belonging to and how is it solving it? (*#846*)
> Update ComponentType, changes should be registered in Changelog
Create Release with RepositoryURl set , unwanted fields like `setRepositorytype , setUrl` should not be logged in ChangeLog
Must:

fix(Changelog): Fixed missing fields like componentType in Changelog

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/changelogs/elementView.jsp

> * Which issue is this pull request belonging to and how is it solving it? (*#850*)
> View Changelog for Project, Component, Release. The Basuc Info Tab in changelog should be of similar style as Moderation request.
Must:

fix(ChangelogBasicInfoUI): Applied generic style and reordered the metadatas for Basic Info.

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java

> Prevent multiple releases with same name and version for a component, which may occur during merge component.
> Provided suffix `_conflict (id)` for releases of src component with same version as of target component's releases
> * Which issue is this pull request belonging to and how is it solving it? (*#848*)
> * Did you add or update any new dependencies that are required for your change?- No
> Merge two Component with same release version. Target component should not have Release with same name and version, suffix should be added to the release from src component to indicate conflict, which can be resolved later by merging of release.
Must:

fix(mergeComponent): Prevent multiple releases with same name and version for a component, which may occur during merge component.

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CustomFieldHelper.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/customfields/CustomFieldPageIdentifier.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java

* Enabled custom field for additional data in project portlet.
Issue: #860 
* Please follow the steps mentioned in issue #809 for testing.
Must:

feat(ProjectUI): Custom Field for Additional data in Proejct

---

CHANGELOG.md
pom.xml

A pull request to update changelog and pom.xml file to make the current master ready for tagging the 9.0.0-M1 release

chore(release): bumping version to 9.0.0-M1

---

backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
libraries/lib-datahandler/src/main/thrift/components.thrift
rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/docs/asciidoc/releases.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ProjectTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

> Added new allDetails Parameter to List Projects and List Releases API to fetch records with all details.
> * Which issue is this pull request belonging to and how is it solving it? (*#873*)
> Invoke List Projects and List Releases with `allDetails` parameter
`/resource/api/projects?allDetails=true`
`/resource/api/releases?allDetails=true`
Need to be tested in test instance with large dataset to validate any timeout issue.
Must:

feat(REST): Added new allDetails Parameter to List Projects and List Releases API to fetch records with all details.

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseSearchHandler.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/searchReleasesAjax.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/searchReleases.jsp

Issue: 
Fixes #898 
As mentioned in the issue #898 
Must:

feat(ui/search): search release using id while linking it to project

---

CHANGELOG.md
README.md
pom.xml
rest/resource-server/src/docs/asciidoc/api-guide.adoc
scripts/migrations/README.md

Just changing files for release ten.
Issue: 
Tested the UI with a various functions. Also code version has been deployed on one productive server.

chore(release): making files for release 10.0.0-M1

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/LinkedReleasesAndProjectsAwarePortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesAjax.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/linkedReleasesEdit.jspf

> * Which issue is this pull request belonging to and how is it solving it? (*#919*)
> Edit project release table should be sorted by Release name and version . Add release and update project
Must:

feat(EditProjectUI): Release table in edit project page should be sorted and omit vendor name

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java

> Import SPDX BOM from Project or Component List Page giving 500 error.
> * Which issue is this pull request belonging to and how is it solving it? (*#944*)
> Import SPDX BOM from Project or Component List Page - Import should be successful and Project, Component, Release should be created successfully
Must:

fix(ImportSPDXBOM): Set Default value[Default_Category] to categories field of Component if found null or empty

---

backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/searchProjects.jsp
frontend/sw360-portlet/src/main/resources/content/Language.properties
frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
libraries/lib-datahandler/src/main/thrift/projects.thrift

Please refer:  #928 
Issue: 
fixes: #928 
* A new button added in the project details view tab to link to specific project.
* Verify if it is creating cyclic link while linking to other project.
* Check the alignment etc.
Must:

feat(ui): Added link to project button from project detail view

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/ImportExportPortlet.java

Issue: 
#906 
> Admin > Import & Export > Download License Archive
Must:

Fix download license archive (Admin > Import & Export)

---

backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/ImportExportPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/LicenseAdminPortlet.java

Ref Issue : #962 
Issue: 
Fixes #962 
Try adding obligations in Admin -> Obligations view.
Download license archive from Admin -> Import & Export
Must:

fix(license): Fixed the NullPointerException and addressed code duplication

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/vendors/view.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/detailOverview.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/link.js

> Prevent resubmission of form for Project, Component, Vendor, Moderation inorder to prevent loss of data.
> * Which issue is this pull request belonging to and how is it solving it? (*#338*)
> How should these changes be tested by the reviewer? - Refer #338 
> - Create/Update form, close tab - reopen closed tab 
> - In-order to validate whether form was resubmitted, check changelogs or revision Id of Doc in DB,  whether there is any changes.
> - Tested in mozilla and chrome
Must:

fix(ui): Prevent resubmission of form for Project, Component, Vendor, Moderation inorder to prevent loss of data.

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
scripts/migrations/019_update_byExternalIds_component_view.py
scripts/migrations/020_update_byExternalIds_release_view.py
scripts/migrations/021_update_byexternalids_project_view.py

> * Fix #968 
> * No new dependencies
Issue: 
If the param of JSON.parse is a quoted-number value, it returns the number, if the param is a quoted-string value it throws SyntaxError
e.g.
```
JSON.parse("123") == 123
```
```
JSON.parse("eee")
Uncaught SyntaxError: Unexpected token e in JSON at position 0
at JSON.parse (<anonymous>)
at <anonymous>:1:6
```
Must:

fix(byExternalIdView): Fixed the byExternalIds view not working if the value is number.

---

CHANGELOG.md
README.md
pom.xml

just the pom.xml and the changelog updated for rel 11... let's see if the CI runs through

chore(release): updating files for sw360 11 release

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/LinkedReleasesAndProjectsAwarePortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java

> * Which issue is this pull request belonging to and how is it solving it? (*#960*)
> - Generate ReadmeOss in txt, html, docx format and  Clearing report  - Release should sorted be alphabetically
> - Clearing Status Tree View -  Release and project should be sorted alphabetically
Must:

feat(ui): Sorted order of release in ReadmeOss, Clearing Report, Clearing Status Tree View.

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/AbstractCLIParser.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/CLIParser.java
backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGeneratorTest.java
backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/CLIParserTest.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsByReleases.jspf
libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift

> Rename Obligation in LicenseInfo.thrift to ObligationAtProject
>  * added null check in change log for merge release
> * Which issue is this pull request belonging to and how is it solving it? (*#987*)
> Generate Clearing Report and ReadmeOss in different format. Also Use Obligations added from UI
Must:

feat(LicenseInfoObligation): Rename Obligation in LicenseInfo.thrift to ObligationAtProject

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java

> Fixed search user functionality
> * Which issue is this pull request belonging to and how is it solving it? (*#991*)
> - Goto Search Page - Search Project, Component, Release, User... 
> - Create/Edit Project, Component, Release - add user using search functionality to moderator, contributor, Project Responsible etc.
Must:

fix(UserSearch): Fixed search user functionality

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectSearchHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp

* Added new filter `Additional Data` in `Advanced Search` for projects list page.
Issue: Closes #996 
* Add `Additional Data` for a project, and perform `Advanced Search` on project.
* Search result should only list the projects with matching `Additional Data` entered in search.
Must:

feat(Project-UI): Added new field in Advanced Search for Projets

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGeneratorTest.java
rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

Which issue is this pull request belonging to and how is it solving it? (#975 )
Did you add or update any new dependencies that are required for your change? - No
Issue: Closes: #975 
Test pagination and sorting on `/api/projects` and `/api/projects/{projectId}/releases`
Must:

feat(rest): Adding pagination while listing projects and listing project releases

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/view.jsp
frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
libraries/lib-datahandler/src/main/thrift/licenses.thrift
scripts/migrations/031_update_obligationLevel_from_productObligation_to_projectObligation.py
scripts/migrations/README.md

> Rename product obligation to project obligation
> * Which issue is this pull request belonging to and how is it solving it? (*#998*)
> - Obligation previously with obligationLevel - `PRODUCT_OBLIGATION` should be now `PROJECT_OBLIGATION`
> - Create new obligation of  obligationLevel  - `PROJECT_OBLIGATION` and validate
> - Create Project clearing Report and validate
Must:

feat(obligation): Rename product obligation to project obligation

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ObligationListRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/detail.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftUtils.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
libraries/lib-datahandler/src/main/thrift/projects.thrift
scripts/migrations/032_rename_linkedObligation_to_linkedObligationStatus_in_ProjectObligation.py
scripts/migrations/033_update_type_from_projectObligation_to_obligationList.py
scripts/migrations/034_remove_old_projectObligation_view.py
scripts/migrations/README.md

> Changes in Project Obligation Data Model 
>  * renamed linkedObligations to linkedObligationStatus in ProjectObligation struct
>  * renamed struct ProjectObligation to struct ObligationList
> * Which issue is this pull request belonging to and how is it solving it? (*#1001*)
>  - Create Project with/without obligation -> apply migration script -> open/edit both Project
>  - Create new project with/without obligation , after applying migration script  -> open/edit both Project
>  - Export Excel Sheet
Must:

feat(ProjectObligation): Changes in Project Obligation Data Model

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/Moderator.java

* Closes #1006 
Issue: 
Test approving moderation request which contains release addition or deletion.
Must:

fix(moderation): Project moderation fix

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java

Short fix in wrong method name in release controller. 
Updating release function should be called `patchRelease` instead of  `patchComponent`

typo(rest): fix patchComponent in releasecontroller is patchRelease

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/test/java/org/eclipse/sw360/components/summary/ProjectSummaryTest.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/detail.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administration.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/linkedObligations.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligations.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseMixInForChangeLog.java
libraries/lib-datahandler/src/main/thrift/projects.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
scripts/migrations/037_checkfor_project_todos_in_moderations.py
scripts/migrations/038_convert_ObligationStatusInfo_type_to_obligationType.py
scripts/migrations/039_projecttodo_to_obligationlist.py
scripts/migrations/README.md

> - Renamed type to obligationType ,Changed required licenseIds to optional , Added optional ObligationLevel obligationLevel in ObligationStatusInfo
> - Remove ProjectTodo and UI changes for Obligation and ProjectTodo 
> Create Admin -> Project/Component/Organisation Obligation
> Obligations created should be reflected in Obligation tab of Project.
> Edit Obligation 
> Add/remove release with 1 approved attachment in Project, License Obligation chnages should be reflected.
Must:

feat(ProjectTodo): Remove ProjectTodo and UI changes for Obligation and ProjectTodo 

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java

> Fixed sorting of project clearing state in Project List page
> * Which issue is this pull request belonging to and how is it solving it? (*#1028*)
> Sort Project List based on state . Both Project State and Project clearing state should be sorted properly 
Must:

fix(ProjectListUI): Fixed sorting of project clearing state in Project List page

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectSearchHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp

> Added clearing state filter in Project List
> * Which issue is this pull request belonging to and how is it solving it? (*#1031*)
> Search with Project Clearing state in Project List UI
Must:

feat(ProjectListUI): Added clearing state filter in Project List

---

CHANGELOG.md
build-configuration/resources/couchdb.properties
pom.xml

* changed the search parameter as this was found to be the last issue to be stabilized. if the the àllowleadingwildcard`is not to truein couchdb.properties and the couchdb-lucene.ini, search will not work
* changed the pom.xml
* updated the changelog
Deploy and see

chore(release): make twelve

---

libraries/exporters/bnd.bnd

> Fixed ClassNotFoundException while export Spreadsheet.
> * Which issue is this pull request belonging to and how is it solving it? (*#1060*)
- Download and place [commons-compress-1.20.jar](https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.20/commons-compress-1.20.jar) in `liferay/deploy folder` 
- Export Spreadsheet , Refer - #1060 
Must:

fix(ExportSpreadSheet): Fixed ClassNotFoundException while export Spreadsheet

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

> Fixed update Project API issue - unexpected changes in some fields like moderators ,contributors, etc
> * Which issue is this pull request belonging to and how is it solving it? (*#1057*)
> How should these changes be tested by the reviewer? - Refer #1057 
> Have you implemented any additional tests? - Yes, Testcase for Doc
Must:

fix(rest): Fixed update Project API issue - unexpected changes in some fields like moderators ,contributors, etc

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ChangeLogsDatabaseHandler.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/changelogs/elementView.jsp

> Fixed issue related to null to empty string or collection conversion
> * Which issue is this pull request belonging to and how is it solving it? (*#1053*)
> Update/Create Project component release. Conversions like null to `"", {}, []` or vice-versa should not be shown to user
Must:

feat(ChangeLogs): Fixed issue related to null to empty string or collection conversion

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/add.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/view.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/edit.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailAddTodo.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailOverview.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailTodos.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/licObligations.jsp
frontend/sw360-portlet/src/main/resources/content/Language.properties
frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
libraries/lib-datahandler/src/main/thrift/licenses.thrift
scripts/migrations/042_remove_validForProject_from_Obligation.py

Please refer the mentioned issue.
> * Which issue is this pull request belonging to and how is it solving it? (#1050 )
Issue:  
closes #1050 
> How should these changes be tested by the reviewer? 
* Need to test the editing the license and adding obligation to it.
Must: …

feat(ui-licenseobligation): License obligation changes

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxUtils.java

> * Which issue is this pull request belonging to and how is it solving it? (*#1071*)
Issue: 
Closes: #1071 
Can be tested with a CLI file which contains obligation text for example as below.
`<Text><![CDATA[
]]></Text>`
Must:

fix(clearingreport): Error while downloading clearing report

---

CHANGELOG.md
pom.xml
scripts/migrations/README.md

* changed `pom.xml`
* added entry in `CHANGEOG.md`
* updated `scripts/migrations/README.md`

chore(rel): bumping version to 13.0.0 in files

---

rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

* Added filter based on priorities and project relevance and respective documentation for `projects/{id}/vulnerabilities`
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*) 
Issue: NA
* Need to test the REST endpoint (`projects/{id}/vulnerabilities?priority=xxxx` & …

feat(rest): Added filter for get project vulnerabilities endpoint

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandlerTest.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/LinkedReleasesAndProjectsAwarePortlet.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java

> Optimized loading of license info, source code download, Clearing report page
> * Which issue is this pull request belonging to and how is it solving it? (*#1100*)
> - Generate License Info,
> - Download src code 
> - Export Projects
Must:

fix(LicenseInfo): Optimized loading of license info, source code download, Clearing report page

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java

> Attachments not linked properly from source component/Release during merge component and release.
> * Which issue is this pull request belonging to and how is it solving it? (*#1094*)
- Refer #1094 and merge component and Releases accordingly
Must:

fix(mergeComponentRelease): Attachments not linked properly from source component/Release

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
frontend/sw360-portlet/src/main/resources/content/Language.properties
frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
frontend/sw360-portlet/src/main/resources/content/Language_vi.properties

* Added the `sort` and `search` functionality for `Clearing Status` _Tree View_ table.
> Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
* #1102 
>  Did you add or update any new dependencies that are required for your change?
* No
* Open the project with `linked releases` and `linked projects`, and go to …

feat(ProjectUI): Sort & Filter for ClearingStatus TreeView table

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature_request.md

Issue: 
Create a new issue.
No
Must:
Signed-off-by: Ravindra Kumar kumar.ravindra@siemens.com

feat(issue template): New Issue template for the bug and feature

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/changelogs/elementView.jsp

> Highlight changes between old and new revision of Document
> * Which issue is this pull request belonging to and how is it solving it? (*#1118*)
> - Perform Changes for different fields (Map, Set, String, Object) of Project , Component, Release. 
> - Check whether changelogs register correct data and highlight what has changed
> - Check for escapeXML by inserting text like `<script>alert(123)</script>` in comment fields 
> - Refer Screenshots below.
Must:

feat(ChangeLog): Highlight changes between old and new revision of Document

---

scripts/utilities/004_recompute_clearing_state_of_release.py
scripts/utilities/README.md

> Utility script to recompute clearing state of release.
> * Which issue is this pull request belonging to and how is it solving it? (*#1127*)
> - Validate Recompute logic with `Update/Create Release - autosetReleaseClearingState()` in the code
> - Execute script , only release with incorrect clearing state should be updated
Must:

fix(script): Utility script to recompute clearing state of release

---

CHANGELOG.md
pom.xml

Current master tagging. should pass travis CI. please see CHNAGELOG file for info about 13.1:

bumping version to 13.1.0 in files, changelog

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java

> Fix status code when moderation request is created as a part of an API call
>  * Affected APIs in ProjectController - Update Project, Add/Patch Releases to a project, Patch vulnerabilities of a project, Add Attachment To Project
>  * Affected APIs in ReleaseController - Update Releases, Delete Attachments from releases
>  * Affected APIs in ComponentController - Delete Attachments from component, Delete Components, Update Components, Add Attachment To Component
> * Which issue is this pull request belonging to and how is it solving it? (*#1003*)
>Need to test affected APIs with or without moderation request.
> If moderation request is created …

fix(rest): Fix status code when moderation request is created as a part of an API call

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

> * Which issue is this pull request belonging to and how is it solving it? (*#1160*)
Issue: CLoses #1160 
Need to test the `projects/{id}/vulnerabilities?projectRelevance=APPLICABLE&projectRelevance=IRRELEVANT` endpoint(may be along with other filters) and verify the …

fix(rest): Added support for pagination and retrival using multi value `projectRelevance` param

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java

> Fixed copy of projects removes linked subprojects.
> * Which issue is this pull request belonging to and how is it solving it? (*#1197*)
Issue: closes #1197 
>   - Duplicate Project with Linked sub-project , releases , attachment from Project List Page
>   - Change name/version
>   - Create Project
Must:

feat(ProjectUI): Fixed copy of projects removes linked subprojects

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java

Added the project version to be displayed along with the project name in the Search tab for the Projects.
> * Which issue is this pull request belonging to and how is it solving it? (#1215 )
> * Did you add or update any new dependencies that are required for your change? NA
Issue: closes #1215 
- Search the Projects by passing the project name from the …

feat(ProjectVersion): Added the project version in the Search option for the Projects filter.

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentSearchHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectSearchHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseSearchHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserSearchHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/VendorSearchHandler.java
backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentSearchHandlerTest.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
backend/src/src-search/src/main/java/org/eclipse/sw360/search/SearchHandler.java
backend/src/src-search/src/main/java/org/eclipse/sw360/search/Sw360usersDatabaseSearchHandler.java
backend/src/src-search/src/main/java/org/eclipse/sw360/search/db/AbstractDatabaseSearchHandler.java
backend/src/src-search/src/main/java/org/eclipse/sw360/search/db/Sw360dbDatabaseSearchHandler.java
backend/src/src-users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java

Issue with release search. Have updated the database connector in `LuceneAwareDatabaseConnector.java`
> * Which issue is this pull request belonging to and how is it solving it? (*#1213*)
Issue: closes #1213 
* need to test the release search while linking to project. …

fix(search): search releases while linking to project

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
frontend/sw360-portlet/src/main/resources/content/Language.properties
frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
frontend/sw360-portlet/src/main/resources/content/Language_vi.properties

> Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
* #1209
* No
Issue: #1209 
* Added a new button (`Add License info to Release`) under `Tree View` table of `License Clearing` tab in project details page.
* Clicking on button …

feat(ProjectUI): feature to add License Info to linked releases from License Clearing tab

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java

> * Add function for check licenseId input when update release
Issue: #534 
Must:

Fix: Rest interface can not handle licenses which do not exist in the database #534

---

CHANGELOG.md
README.md
pom.xml

tested with vagrant, changing files for tagging 13.4 a good version.
Must:

chore(rel): changing files for tagging 13.4

---

backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/ModerationHandler.java
backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationRequestRepository.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
libraries/lib-datahandler/src/main/thrift/moderation.thrift

> * Which issue is this pull request belonging to and how is it solving it? (*#1243*)
* The visibility of moderation requests is set for the users in moderators list.
* The count should be shown as open requests/closed requests on the top right corner of the page
* Departments are sorted in the search dropdown list.
Issue: Closes #1243 
> You can suggest reviewers here with …

fix(ModerationRequests): moderation requests visibility

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/Moderator.java

> Accepting Moderation Request fails if it involves deletion of linked release or project from a project or release
> * Which issue is this pull request belonging to and how is it solving it? (*#1252*)
Issue: closes #1252 
> Approve Moderation Request which involves
> - Delete Linked Release from a Release
> - Delete Linked Project from a Project
> - Delete Linked Release from a Project
Must:

fix(ModerationRequest): Accepting Moderation Request fails if it involves deletion of linked release or project from a project or release

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java

Please refer #1278
> * Which issue is this pull request belonging to and how is it solving it? (*#1278*)
Issue: Closes: #1278 
* Create a release via REST. And try to update the same via REST for e.g with this …

fix(rest): Issue updating newly created release via REST and issue with get project by id

---

backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/VulnerabilityHandler.java
backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityDatabaseHandler.java
libraries/lib-datahandler/src/main/thrift/vulnerabilities.thrift
rest/resource-server/src/docs/asciidoc/vulnerabilities.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/Sw360VulnerabilityService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java

> Added rest apis for create, update, delete vulnerability.
>   * create, delete vulnerability release relation
> * Which issue is this pull request belonging to and how is it solving it? (*#1258*)
Issue: closes #1258 
-  **3.9.3. Create a vulnerability**
- Doc - http://localhost:8080/resource/docs/api-guide.html#resources-vulnerabilitie-create
```
curl 'https://sw360.org/api/vulnerabilities' -i -X POST -H 'Content-Type: application/hal+json'
-H 'Authorization: Bearer eyJhbGciOi*******' -H 'Accept: application/hal+json' 
-d '{
"externalId" : "987",
"title" : "Title of vulnerability 12345",
"description" : "Description of vulnerability",
"publishDate" : "01-01-2018",
"lastExternalUpdate" : …
```

feat(rest): Added rest apis for create, update, delete vulnerability and create, delete vulnerability release relation

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligations.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
frontend/sw360-portlet/src/main/resources/content/Language.properties
frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
frontend/sw360-portlet/src/main/resources/sw360.properties

> Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
* #1282
* No
Issue: #1282 
* Only UI changes, Please go through the issue, and screenshot below:
Must:

feat(ProjectUI): Improvements in AddLicenseInfoToRelease & Obligation tab UI

---

backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationRequestRepository.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseRepositoryCloudantClient.java

Replaced the views with mango queries.
> * Which issue is this pull request belonging to and how is it solving it? (*#1271*)
Issue: Closes #1271 
* load requests tab with large number of requests.
* Search …

fix(ModerationRequests): Updated views with queries

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp

> Fixed project list view, License Clearing column not loading
> * Which issue is this pull request belonging to and how is it solving it? (*#1301*)
Issue: closes #1301 
> Test Project List View Table, all columns are getting loaded
Must:

fix(ui): Fixed project list view, License Clearing column not loading

---

scripts/migrations/044_replace_gpl_compatibility_by_osi_approved.py
scripts/migrations/README.md

Added `DRY_RUN` flag and updated readme for migration script `044_replace_gpl_compatibility_by_osi_approved.py`.
Issue: 
> How should these changes be tested by the …

fix(script): Added DRY_RUN and updated readme

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java

> Which issue is this pull request belonging to and how is it solving it? 
* #1306 
* No
Issue: #1306 
* create a project / component / release and delete the field `additionalData : {}` from `couchdb`, try to load that project / component / release. It should load without any …

fix(UI): fix null pointer exception in additionalData sorting

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp

> Fixed js error in edit CR Page.
> * Which issue is this pull request belonging to and how is it solving it? (*#1320*)
Issue: 
> Edit Clearing Request 
>    - with clearing Team - it should be successful - without js error in console.
>    - without clearing team - warning msg should be shown - no js error in console
Must:

fix(ui): Fixed js error in edit CR Page

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/basicInfo.jspf

> User should be able to edit group of project. Enabled group field of Project
> Edit Project - group field - editing of group should be successful.
Must:

fix(ui): User should be able to edit group of project

---

.github/testForLicenseHeaders.sh

just add the two new files `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md`

fix(ci) added new files to license check script

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/UserPortlet.java

> Fixed create/update users with uppercase email or externalid.
> * Which issue is this pull request belonging to and how is it solving it? (*#1325*)
closes #1325 
> Create/Update User with mixed case `(GID - A2133iHG , Email - jai.PALIT@sw360.org` and role - `Clearing Admin` - should be successful with no error message.
>   - Validate User record in Couch DB and Liferay - Control Panel - user and org
Must:

fix(ui): Fixed create/update users with uppercase email or externalid

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
build-configuration/resources/log4j2.xml

Signed-off-by: Shi Qiu <shi1.qiu@toshiba.co.jp>
Added the function of outputting the change log of project, component, and release in real-time.
You can edit "build-configuration\resources\log4j2.xml" for log settings (file name, location, rotation size, etc.).
Issue: #1339 
No.
> …

feat(log): Added output processing of the change log

---

backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ProjectModerationRequestGenerator.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/CompareAttachments.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/CompareTodos.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayComponentChanges.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayProjectChanges.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayReleaseChanges.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/TagUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/urlutils/LinkedReleaseRenderer.java
frontend/sw360-portlet/src/main/resources/META-INF/customTags.tld
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/components/merge.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/licenses/merge.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/projects/merge.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/releases/merge.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/users/merge.jsp

Issue: closes #1343 
> Create Moderation Request for project with changes in External URl - single/multi value.
>   - Validate Moderation Request data is correct.
>   -  Accept Moderation Request.
> Check Open/Closed Moderation Request for Project, Component, Release, License, User. should contain proposed changes. Also need to test Accept/Reject.
Must:

fix(ui): Changes in External urls in Project are not registered in Moderation Request. Closed Moderation Request doesnot show Proposed changes

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeComponent.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeRelease.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/mergeWizard.js

> Fixed js error while  merge component/release with null additional data.
> * Which issue is this pull request belonging to and how is it solving it? (*#1347*)
Issue: closes #1347 
> Merge Component/Release with
> - additionalData -> null
> - with/without linked release and attachments
Must:

fix(ui): Fixed js error while  merge component/release with null additional data

---

backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationRequestRepository.java

> Cleanup moderation request on deleting project/release/component.
> * Which issue is this pull request belonging to and how is it solving it? (*#1349*)
Issue: closes #1349 
> - Create some open and closed moderation request for project/component/release
>    - Delete project/component/release - moderation request should also be cleaned up
> - Create Moderation Request for project/component/release
>    - Edit the document again, changes from previous moderation request should be reflected
>    - Edit few more fields - changes should be appended to same moderation request in Request tab
>    - Repeat obove step with another user - user1@sw360.org - each user should one one moderation request per …

fix(ui): Cleanup moderation request on deleting project/release/component

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java

> Fix the 500 Internal server error from releases API while fetching the attachment.
> * Which issue is this pull request belonging to and how is it solving it? (*#1358*)
Issue: closes #1358
- create a component via rest api.
http://localhost:8080/resource/api/components
- create a release via rest api.
http://localhost:8080/resource/api/releases
- fetch the attachment for the …

fix(RestAPI):500 Internal server error from releases API.

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CommonVulnerabilityPortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/vulnerabilities.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/vulnerabilitiesFetch.jspf

> Display,update vulnerability for linked projects in project details view.
Issue: 
> - Create Projects with linked release and linked projects.
> - Create Vulnerabilities, link to release
> - Verify view of Project Details Page -> Vulnerabilities for Parent and Sub Project
>     -  Update Vulnerabilites for Parent and Sub Project.
>     -  Verify Db that there is overlap between Parent and Sub Project.. `sw360db->ProjectVulnerabilitiesRating`
Must:

feat(ui): Display,update vulnerability for linked projects in project details view

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java

Added logic to perform multiple call (fetch 500 projects per a thrift call)  and aggregate it before sending to the rest clients. 
> * Which issue is this pull request belonging to and how is it solving it? (*#1370*)
Issue: Closes #1370
> How should these changes be …

fix(rest): Fixed projects loading issue in REST

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

> Added rest api to create duplicate of project.
> * Which issue is this pull request belonging to and how is it solving it? (*#1379*)
Issue: closes #1379 
> - Refer Documentation - http://localhost:8080/resource/docs/api-guide.html#resources-projects-create-duplicate
> - Provide Project Id to duplicate
> - Pass atleast name or version in request body to prevent project with same name conflict
> - Pass field value in Request body for which different value is desired.
> - Create duplicate project from UI and Rest for same Project with all possible data like
>    - linked releases projects
>   - attachmnets. obligations, clearing request
>   - compare document in couchdb for duplicate project created by UI and …

feat(rest): Added rest api to create duplicate of project

---

backend/src-common/src/main/java/org/eclipse/sw360/components/summary/ReleaseSummary.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/couchdb/SummaryAwareRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseRepositoryCloudantClient.java

> Optimize views for releases.
> * Which issue is this pull request belonging to and how is it solving it? (*#1395*)
Issue: closes #1395 
> **Release View Optimization**
> - Add/Update Release with/without duplicate name or version
> - Create Release with vendor . Delete/Merge vendor should unlink linked vendor from Releases
> - Link Releases Search dialog
> - View/Edit Vendor should list used releases
> - View vuln of release and component
> - Merge release
> - Component-release related fields should be updated when release is updated. Refer changelogs of comp for fields like OS, Programming Language
> - Delete License used in releases
> **Component View Optimization**
>  - Get Components - Rest - …

fix(views): Optimize views for releases and components

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
backend/src-common/src/main/resources/sw360.properties
build-configuration/resources/log4j2.xml

updated the change log path to LIFERAY_INSTALL/sw360changelog/sw360changelog.log
update the sw360.properties value with the below attribute.
- 	enable.sw360.change.log=true
- 	sw360changelog.output.path=sw360changelog/sw360changelog
- Default path it will take the LIFERAY_INSTALL from the system environment. 
Issue: 
> You can …

fix(changelog):Fixed the file permission issue for sw360 changelog.

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/editRelease.jsp

> Fixed redirect page from Release Edit page to Release Details page.
> * Which issue is this pull request belonging to and how is it solving it? (*#1409*)
Issue: closes #1409 
> Go to Edit page of Release click on cancel, it should redirect to release details page
Must:

fix(ui): Fixed redirect page from Release Edit page to Release Details page

---

pom.xml

> Changing back to 14.1.0-SNAPSHOT.
Issue: 
Must:

chore(rel): Changing back to 14.1.0-SNAPSHOT

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
libraries/lib-datahandler/src/main/thrift/projects.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

> Optimize rest api for get project by tag, type, group.
> * Which issue is this pull request belonging to and how is it solving it? (*#1419*)
Issue: closes #1419 
> Test rest api with large amount of data in DB. Response should contain more that 250 records
>   - 3.3.5. Listing by type - https://sw360.siemens.com/resource/docs/api-guide.html#resources-projects-list-by-type
>   - 3.3.6. Listing by group - https://sw360.siemens.com/resource/docs/api-guide.html#resources-projects-list-by-group
>   - 3.3.7. Listing by tag - https://sw360.siemens.com/resource/docs/api-guide.html#resources-projects-list-by-tag
Must:
Signed-off-by: Jaideep Palit …

fix(rest): Optimize rest api for get project by tag, type, group

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
libraries/lib-datahandler/src/main/thrift/attachments.thrift

> Added a new attachment type "Security Assessment" while uploading a new attachment from the UI, which has the short name "SECA".
> * Which issue is this pull request belonging to and how is it solving it? (*#1397*)
Issue: closes #1397 
Add/update a new attachment from the Project, Components and Release view from the UI. …

feat(NewAttachmentTypeUI):Add a new attachment type Security Assessment.

---

pom.xml

Signed-off-by: Anupam Ghosh <anupam.ghosh@siemens.com>
update the log4j version to 2.15.0 due to 
https://github.com/advisories/GHSA-jfh8-c2jp-5v3q
Issue: 
test the areas that specific to logging

log4j version upgrade to 2.16.0(log4j-vulnerability)

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java

Signed-off-by: He, Albert <albert.he@sap.com>
Fix https://github.com/eclipse/sw360/issues/1223
No
Issue: 
Test the sorting in component page
Must:

fix(ui): Fix component list sorting error

---

rest/rest-common/src/main/java/org/eclipse/sw360/rest/common/PropertyUtils.java

Signed-off-by: He, Albert <albert.he@sap.com>
> * Which issue is this pull request belonging to and how is it solving it? (*https://github.com/eclipse/sw360/issues/1426*)
No
Issue: 
https://github.com/eclipse/sw360/issues/1426
Must:

fix(comm): Fix default config not working issue

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java

> * Which issue is this pull request belonging to and how is it solving it? (*#1443*)
Issue: closes #1443 
> Create new release by rest and ui without mainline state - by default it should have OPEN
Must:

fix(release): Fixed mainline state is empty when creating a release by ui or rest

---

clients/client/src/main/java/org/eclipse/sw360/clients/adapter/SW360Connection.java
clients/client/src/main/java/org/eclipse/sw360/clients/adapter/SW360ConnectionFactory.java
clients/client/src/main/java/org/eclipse/sw360/clients/adapter/SW360VulnerabilityAdapterUtils.java
clients/client/src/main/java/org/eclipse/sw360/clients/adapter/SW360VulnerabilityClientAdapter.java
clients/client/src/main/java/org/eclipse/sw360/clients/adapter/SW360VulnerabilityClientAdapterAsync.java
clients/client/src/main/java/org/eclipse/sw360/clients/adapter/SW360VulnerabilityClientAdapterAsyncImpl.java
clients/client/src/main/java/org/eclipse/sw360/clients/rest/SW360VulnerabilityClient.java
clients/client/src/main/java/org/eclipse/sw360/clients/rest/resource/LinkObjects.java
clients/client/src/main/java/org/eclipse/sw360/clients/rest/resource/vulnerabilities/SW360CVEReference.java
clients/client/src/main/java/org/eclipse/sw360/clients/rest/resource/vulnerabilities/SW360ReleaseVulnerabilityRelation.java
clients/client/src/main/java/org/eclipse/sw360/clients/rest/resource/vulnerabilities/SW360VendorAdvisory.java
clients/client/src/main/java/org/eclipse/sw360/clients/rest/resource/vulnerabilities/SW360VerificationState.java
clients/client/src/main/java/org/eclipse/sw360/clients/rest/resource/vulnerabilities/SW360VerificationStateInfo.java
clients/client/src/main/java/org/eclipse/sw360/clients/rest/resource/vulnerabilities/SW360Vulnerability.java
clients/client/src/main/java/org/eclipse/sw360/clients/rest/resource/vulnerabilities/SW360VulnerabilityList.java
clients/client/src/main/java/org/eclipse/sw360/clients/rest/resource/vulnerabilities/SW360VulnerabilityListEmbedded.java
clients/client/src/main/java/org/eclipse/sw360/clients/utils/SW360ResourceUtils.java
clients/client/src/test/java/org/eclipse/sw360/clients/adapter/SW360ConnectionFactoryTest.java
clients/client/src/test/java/org/eclipse/sw360/clients/adapter/SW360VulnerabilityAdapterUtilsTest.java
clients/client/src/test/java/org/eclipse/sw360/clients/adapter/SW360VulnerabilityClientAdapterAsyncImplTest.java
clients/client/src/test/java/org/eclipse/sw360/clients/rest/SW360VulnerabilityClientIT.java
clients/client/src/test/resources/__files/all_vulnerabilities.json
clients/client/src/test/resources/__files/release_vulnerability_relation.json
clients/client/src/test/resources/__files/vulnerability.json

>  Added Java Client Apis for vulnerability endpoints
> * Which issue is this pull request belonging to and how is it solving it? (*#1276*)
Issue: closes #1276 
> This PR needs to be tested after #1257 is merged
> Have you implemented any additional tests? - Yes
Must:

feat(client): Added Java Client Apis for vulnerability endpoints

---

clients/client/src/main/java/org/eclipse/sw360/clients/rest/resource/vulnerabilities/SW360ReleaseVulnerabilityRelation.java
clients/client/src/test/java/org/eclipse/sw360/clients/rest/SW360VulnerabilityClientIT.java

> Fixed vulnerability IT testcases
Issue: 
> Check github action logs
Must:

fix(ci): Fixed vulnerability IT testcases

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/edit.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/editRelease.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editAttachments.jspf
frontend/sw360-portlet/src/main/resources/content/Language.properties
frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/businessrules/ReleaseClearingStateSummaryComputer.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
libraries/lib-datahandler/src/main/thrift/attachments.thrift
libraries/lib-datahandler/src/main/thrift/components.thrift

> Added new Clearing State and Attachment Type.
> * Which issue is this pull request belonging to and how is it solving it? (*#1390*)
> * Did you add or update any new dependencies that are required for your change?- No
Issue: closes #1390
> Refer #1390
> - Test attachments exisiting/newly uploaded to project release component.
> - Upload attchment to release and test Clearing state as per comment - https://github.com/eclipse/sw360/issues/1390#issuecomment-947448209
> - Test Search sort colors , List/Tree view of License Clearing Tab of Project
Must:

feat(ui): Added new Clearing State and Attachment Type

---

pom.xml

> * Changing back to 15.1.0-SNAPSHOT
Issue: 
Must:

chore(rel): Changing back to 15.1.0-SNAPSHOT

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/VendorRepository.java
backend/src-common/src/test/java/org/eclipse/sw360/components/summary/ProjectSummaryTest.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/basicInfo.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/vendors/vendorDetail.jspf
frontend/sw360-portlet/src/main/resources/content/Language.properties
frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
libraries/lib-datahandler/src/main/thrift/projects.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java

> Added  vendor for project.
> * Which issue is this pull request belonging to and how is it solving it? (*#1446*)
Issue: closes #1446 
> **Affected areas in Project**
```
UI
Get
update,
Create,
Delete,
search vendor
Rest
Get all , by id
Update with correct/incorrect vendor id
Create with correct/incorrect vendor id,
Delete 
Moderation request
Export excel
```
Must:

feat(project): Added  vendor for project

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java

> Fixed pagination of component list with search params.
> * Which issue is this pull request belonging to and how is it solving it? (*#1449*)
Issue: closes #1449 
> Refer #1449 
Must:

fix(ui): Fixed pagination of component list with search params

---

scripts/utilities/003_update_project_field_value_couchdb_2_x.py
scripts/utilities/README.md

Addition to update project field starting with some value to a new value.
Issue: 
Execute …

feat(script): Addition to update project field starting with some value

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp

> Update some fields in a Project in closed state.
> * Which issue is this pull request belonging to and how is it solving it? (*#1461*)
Issue: closes #1461 
> How should these changes be tested by the reviewer? - Refer #1461 
Must:

feat(projectUi): Update some fields in a Project in closed state

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java

* Fixes the issue of project Moderation request not loading.
Issue: N/A
@smrutis1 
Deploy master branch, and moderation request created will fail to load.
Deploy this branch, and moderation request created will load successfully.
Must:

fix(ModerationRequestUI): Fixed project Moderation Request UI is not loading

---

rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

> Get Project Vulnerability by external id and release id.
> * Which issue is this pull request belonging to and how is it solving it? (*#1469*)
Issue: closes #1469 
> Refer - #1469 
Must:

feat(rest): Get Project Vulnerability by external id and release id

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
frontend/sw360-portlet/src/main/resources/content/Language.properties
frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
frontend/sw360-portlet/src/main/resources/content/Language_vi.properties

Issue: #1485 
Use Advance Search function by **Japanese and Vietnamese**
Checking  whether you can set "Created on" & "between" …

fix(ui) : modify translation for search function

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftClients.java
libraries/lib-datahandler/src/main/resources/sw360.properties

Added a custom thrift configure to adopt configurable thrift max message size and max frame size. 
> * Which issue is this pull request belonging to and how is it solving it? (*#1493*)
Issue: 
This would …

fix(thrift): Updated thrift configuration to adopt configurable max message size and max framesize

---

libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/ComponentPermissions.java

Issue: #1489
> How should these changes be tested by the reviewer?  
Please refer #1489 
No
Must:

fix(compoent-visibility): Moderation request for clearing admin

---

backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ReleaseModerationRequestGenerator.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/Moderator.java

> Fixed moderation request for release with version overwrite.
> * Which issue is this pull request belonging to and how is it solving it? (*#1472*)
Issue: closes #1472 
Must:

fix(modReq): Fixed moderation request for release with version overwrite

---

README_DOCKER.md

Related issue: https://github.com/eclipse/sw360/issues/1498

fix(docker): Add better proxy documentation to docker-compose

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/linkedObligations.jsp

> Fixed Obligation count in project view
> * Which issue is this pull request belonging to and how is it solving it? (*#1487*)
Issue: closes #1487 
Must:

fix(ui): Fixed Obligation count in project view

---

.github/workflows/githubactions.yml
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ChangeLogsDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
backend/src/src-changelogs/src/main/java/org/eclipse/sw360/changelogs/ChangeLogsHandler.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/TodoPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/add.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/includes/obligationChangelog.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/includes/searchObligationElements.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/obligationTextTree.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/view.jsp
frontend/sw360-portlet/src/main/resources/content/Language.properties
frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseMixInForChangeLog.java
libraries/lib-datahandler/src/main/thrift/changelogs.thrift
libraries/lib-datahandler/src/main/thrift/licenses.thrift

> New functions for Obligation management
> * Edit one existing obligation
> * Create new obligation based on the information of one existing obligation (Duplicate)
> * View the changelogs of obligations
Issue: https://github.com/eclipse/sw360/issues/513#issuecomment-978775423
> All new functions are available in the screen Admin -> Obligations
> …

feat(obligation): add function Edit/Duplicate/Changelog for Obligation

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
scripts/migrations/049_migrate_admin_obligation.py
scripts/migrations/README.md

Please see the description of issue #1517 
Issue: #1517 
Please follow the steps mentioned in `How to reproduce` in issue #1517 
Must:

fix(Obligation): Save Admin Level Obligation based on Obligation topic

---

.github/workflows/githubactions.yml

Signed-off-by: tuan99123 <tuan2.nguyennhu@toshiba.co.jp>
Issue: #1519
Must:

fix( GitHub action): fix bug Invalid GitHub action 

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java

Signed-off-by: hoangnt2 <hoang2.nguyenthai@toshiba.co.jp>
Issue: #1484 
Please refer to issue: #1484
Must:

Fix(REST): fix visibility of Project Rest API

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/edit.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailAddTodo.jspf

Signed-off-by: hoangnt2 <hoang2.nguyenthai@toshiba.co.jp>
Issue: #1463 
> Please refer to issue: #1463 
Must:

Fix(License): Fix bug one license cound add only 10 obligations

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java

Project filter is not working while exporting to excel.
Issue: 
Filter project based on some filtering …

fix(excel-export): fixed project filter issue while exporting excel

---

backend/src/src-fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
backend/src/src-fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java
backend/src/src-fossology/src/test/java/org/eclipse/sw360/fossology/FossologyHandlerLocalhostIntegrationTest.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/FossologyAwarePortlet.java
libraries/lib-datahandler/src/main/thrift/fossology.thrift
rest/resource-server/src/docs/asciidoc/releases.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

> Add upload description to trigger fossology process.
> * Which issue is this pull request belonging to and how is it solving it? (*#1533*)
Issue: closes #1533 
Must:

feat(rest): Add upload description to trigger fossology process

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/detailOverview.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/summary.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/detailOverview.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/summaryRelease.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/js/components/includes/releases/regexjs.js

…nd Release
Signed-off-by: tuan99123 <tuan2.nguyennhu@toshiba.co.jp>
Issue: #1506 
Please refer issue: #1506
Must:

fix(ui): Display url, email, text  of Additional Data for Component/Release

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java

Fix (Release): Fixed vulnerability can't be deleted when it is linked with a deleted release

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsages.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsagesRows.jspf
frontend/sw360-portlet/src/main/resources/content/Language.properties
frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
frontend/sw360-portlet/src/main/resources/content/Language_vi.properties

Please follow the instructions mentioned in below issue.
Issue: #1525 
Please follow the instructions mentioned in above issue.
Must:

feat(ProjectUI): AttachmentUsages - Added option to filter for releases without source attachments

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissions.java
libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissionsTest.java

> Added write permissions for closed project.
Issue: 
> Test Closed Project should be editable partially by 
- ADMIN
- CLEARING_ADMIN
- Created By
- Project Responsible
- Moderators
- Contributors
- Lead Architect
Must:

fix(project): Added write permissions for closed project

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/UserPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/user/view.jsp

Issue:  User Management : Ability to filter active users
#1589 
- Go to admin tab.
- Then select user, you will see user table with an additional column (Active status).
- This column tells whether user is active or inactive.

feat(ui):filter active users

---

pom.xml

Signed-off-by: Anupam Ghosh <anupam.ghosh@siemens.com>
Issue: 
Must:

chore(dependencies): spring vulnerability - cve-2022-22970,cve-2022-22971

---

CHANGELOG.md
pom.xml

> * Changelog for the release 16.0.0
Issue: 
Must:

chore(rel): changing files for tagging 16.0

---

.github/workflows/githubactions.yml
pom.xml

Signed-off-by: Anupam Ghosh <anupam.ghosh@siemens.com>
Issue: 
Must:

chore(rel): Changing back to 16.1.0-SNAPSHOT

---

backend/src/src-search/src/main/java/org/eclipse/sw360/search/SearchHandler.java
backend/src/src-search/src/main/java/org/eclipse/sw360/search/db/AbstractDatabaseSearchHandler.java
libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java

> * Which issue is this pull request belonging to and how is it solving it? (*#1551*)
Issue: 
* try to search with examples given in the issues
Must:

feat(search): allow searching for external ids

---

scripts/docker-config/portal-ext.properties

Find wrong property file slipped in the liferay docker upgrade commit

bug(docker): Fix invalid commited docker props

---

pom.xml

fix(jenkins): Update old eclipse jarsigner

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java

#1625 
NullPointerException while downloading report.
Issue: 
Must:

fix(report): Nullpointer downloading report

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/preferences/view.jsp
frontend/sw360-portlet/src/main/resources/sw360.properties

> * Which issue is this pull request belonging to and how is it solving it? #1597
Issue: 
No use of write access on preferences page, so we removed write access from UI
> How should these changes be tested by the reviewer? 
1) First reviewer login into sw360 project 
2) Go to preferences tab
3) Go down on the same page and …

fix(UI): Disable write access from UI

---

backend/src/src-cvesearch/src/test/java/org/eclipse/sw360/cvesearch/datasource/json/CveSearchJsonParserTest.java
backend/src/src-licenses/pom.xml
frontend/liferay-theme/pom.xml
frontend/liferay-theme/src/main/webapp/css/_custom.scss
frontend/liferay-theme/src/main/webapp/css/portal/_alert.scss
frontend/liferay-theme/src/main/webapp/css/portlet/_portlet_decorators.scss
frontend/liferay-theme/src/main/webapp/templates/portal_normal.ftl
frontend/sw360-portlet/bnd.bnd
frontend/sw360-portlet/pom.xml

- Updated the Liferay kernel version to `43.0.1` to make it compatible with Liferay 7.4.3-GA18.
- Updated the Liferay theme dependency.
- Minor UI issues like user menu dropdown are fixed.
issue screenshot: 
- Fixed the `src-cvesearch` test case failure in for Asian time zone.
Issue: #1637 
- Build Liferay without skipping testcase,
- Deploy sw360, and test all the portlet UI is loading properly, and able to …

chores(liferay): updated liferay kernel and theme

---

Dockerfile

Jar files are searched in wrong relative path

bug(docker): Fix share location of jar files

---

frontend/pom.xml
frontend/sw360-portlet/pom.xml
libraries/lib-datahandler/pom.xml
pom.xml
rest/resource-server/pom.xml

We had different dependencies used during the build. This PR fix maven plugin versions

fix(maven): Use unique versions for same dependencies

---

frontend/liferay-theme/pom.xml
frontend/sw360-portlet/pom.xml
pom.xml

We had different dependencies used during the build. This PR fix liferay dependency versions

fix(liferay): Use unique versions for same dependencies

---

pom.xml
rest/resource-server/pom.xml

- This PR fixes the REST and MK-Docs generation issue.
Issue: #1678 
Build and deploy, and check whether REST and Mk-Docs are generated successfully.
Must:

Fix(Docs): rest and mk docs

---

pom.xml
scripts/download_dependencies.sh

upd(deps): Update jackson versions

---

.github/workflows/build_and_test.yml
.github/workflows/docker_deploy.yml
Dockerfile
README_DOCKER.md
docker-compose.yml
docker_build.sh
scripts/download_dependencies.sh

upd(docker): Push sw360 docker image to Github Registry

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentUsageRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ChangeLogsRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ConfigContainerRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/CustomPropertiesRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ObligationListRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectVulnerabilityRatingRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/RelationsUsageRepository.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseRepository.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseTypeRepository.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/ObligationElementRepository.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/ObligationNodeRepository.java
backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ClearingRequestRepository.java
backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityRelationRepository.java
rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/client/persistence/OAuthClientRepository.java

1. Changed the `couchdb` view not to emit the whole documents.
Issue: #1604 
Make sure all the SW360 documents are loading (creation / updating / deletion) fine in UI.
Specifically:
1. Attachments,
2. Attachment Usages,
3. Change Logs,
4. Configs,
5. Obligations (Org, Project, Component and License),
6. Vulnerabilities (Rating, Relation),
7. License,
8. License Types,
9. Clearing Request,
10. OAuth tokens.
Must:
Signed-off-by: Abdul Kapti …

fix(CouchDbView): Improve couchdb view performance

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/detailOverview.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf

Signed-off-by: Nikesh kumar <kumar.nikesh@simens.com>
> * Which issue is this pull request belonging to and how is it solving it? #1697 
Issue: 
There is an issue with project list which is not showing in component tab.
1: Login sw360 
2: Go to component tab.
3: select any component and go inside the component.
4:scroll down …

fix(UI): Added code to show the project list in component tab

---

.github/workflows/build_and_test.yml
README_DOCKER.md

Liferay 7.4.x unfortunately move another config option to inside interface

upd(doc): Update docker documentation related to redirects

---

README.md

upd(README): Update with new information

---

.github/workflows/docker_deploy.yml

* Every merged commit will be tagged as <image>:main
* Every tag from sw360-* will be tagged as <image>:latest

upd(docker): Publish push to main commits

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/importBom.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/importBomForComponent.jspf
pom.xml

Signed-off-by: Nguyen Nhu Tuan <tuan2.nguyennhu@toshiba.co.jp>
Issue:  #1732
Use file 
[bom.spdx.rdf.zip](https://github.com/eclipse/sw360/files/10091067/bom.spdx.rdf.zip)
Steps
1. Go to project page
2. Click "Import SPDX BOM" …

feat(SPDX): Upgrade tools-java library to support SPDX 2.3 format

---

.github/workflows/build_and_test.yml

Reduce the amount of resource usage as the same code don't need to be tested twice as already passed by pull request test.

upd(CI/CD): Build and test only during the PR.

---

scripts/migrations/README.md

fix(doc) : update migration Readme

---

backend/src/src-licenses/pom.xml
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/tools/OSADLObligationConnector.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/tools/ObligationConnector.java

Fix bug can not add/update Admin Obligation and import OSADL
Issue: #1734 
Refer to: #1734 
Must:

Fix(Obligation): Fix bug can not add/update Admin Obligation and import OSADL

---

libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java

Signed-off-by: Nikesh kumar <kumar.nikesh@simens.com>
Added a new column and fill the data for respective colunm for export spreadsheet in project tab.
> * Which issue is this pull request belonging to and how is it solving it? #1744 
Issue: 
Few column was not available when we export spreadsheet in project tab.
project responsible
project owner
security responsibles
flag …

fix(UI): Added new column in exprot spreadsheet in project tab

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java

> allDetails parameter added in component call like project and releases.
> 
> * Which issue is this pull request belonging to and how is it solving it? (*#1719*)
Issue: closes #1719 
> while doing component call you have to send a boolean parameter "allDetails" which will fetch all the details about component. 
Must:
- [X ] All …

feat(rest): new param (allDetails) added in component call to get more details of component

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java

Issue: #1677 
Refer to issue: #1677 
Must:

Fix(ProjectUI): Fix bug when editing obligations in a project.

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/vulnerabilities/view.jsp

Issue: #1765 
Select vulnerabilities tab
Expected: Vulnerability view page is loaded as below

Fix(Vulnerability GUI): Fix bug cannot load vulnerability view page

---

CHANGELOG.md
pom.xml

Changelog for the release 17.0.0
* updated the CHANGELOG.md
* updated pom.xml for tagging sw360-16.0.0-M1

chore(rel): changelog for tagging 17.0

---

pom.xml

Signed-off-by: Anupam Ghosh <anupam.ghosh@siemens.com>
Issue: 
Must:

chore(rel): Changing back to 17.1.0-SNAPSHOT

---

backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
scripts/migrations/054_remove_inactiveUsers_from_moderators.py
scripts/migrations/README.md

Closes: #1758 
- Create Moderation Request.
- After creating, check whether deactivated users are present in moderators list or not in Requests Portlet.
Run Script:
To remove deactivated users from the moderators list from database for old data.

fix(UI):remove deactivated users from moderators list

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java

Reused the centrally created thrift client(where the other configurations like MAX_MESSAGE_SIZE is aplicable) in project and release services.
> * Which issue is this pull request belonging to and how is it solving it? (*#1806*)
Issue: 
> How should these changes be …

fix(rest): Reuse centrally created thrift client

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf

Issue: #1778 
Refer to: #1778 
Must:

Fix(Project GUI): Fix bug missing obligation text when change status or comment of component, project, organisation obligation in project edit

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java

Issue: #1776 
Refer to: #1776 
Must:

Fix (REST): Fix bug do not set businessUnit automatically when create component. Get all components always return visibility EVERYONE.

---

scripts/migrations/054_repair_broken_releasevulnerability.py
scripts/migrations/README.md

For some reason(we assume from rest API) the relation between release and vulnerability is missing. This script will recreate the relations where ever applicable.
Issue: 
> You can suggest reviewers here with an …

fix(vulnerability): Script to repair release vulnerability relations

---

frontend/liferay-theme/src/main/webapp/css/portal/_header.scss
frontend/liferay-theme/src/main/webapp/templates/portal_normal.ftl
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CustomFieldHelper.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MySubscriptionsPortlet.java

Signed-off-by: rchopra <rudra.chopra@siemens.com>
Issue:  Add banner to broadcast messages (#1595)
Description : This functionality can be edited by Admins only.
1) Click on 9 dots on the top right section of the page
2) Go to control panel -> click custom fields under configuration
3) Select User under Resource section
4) There you will see BannerMessage custom field.
5) Click on three dots to edit this field. Here you can enter message that you want to be displayed.
6) Right click on three dots and give view permission to all sw360 users/roles and change other permissions too. (Refer the ss for this step)
Click custom field under control panel section
Select User under resource section
Banner Message custom field should look like this
Give view permission to all sw360users/roles and …

feat(ui): Add banner to broadcast messages

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ObligationSearchHandler.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/search/view.jsp
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java

Issue: #1774  
Refer to: #1774 
Must:

Fix(Search): Fix bug can not show result with single quote character and can not search obligations

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/AttachmentAwarePortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayProjectChanges.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editAttachments.jspf
libraries/datahandler/src/main/thrift/projects.thrift

The edit page is retained after 'DUPLICATE' error message is thrown.
Issue: #957
Error on creating/editing duplicate project(existing name and version).
Create:
- Add a new `project`/`component`/`release` with the same name and version as an existing `project`/`component`/`release`.
- Click on Create `project`/`component`/`release` button and check if all the `project`/`component`/`release` related information is retained (**no data loss**).
- In case of …

fix(UI): Error when creating/editing duplicate project/component/release

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/totalVulnerabilities.jsp

Description: Vulnerability Summary Tab in Projects will includes vulnerabilities of all the projects (parent+subProjects).
Issue: 
- Goto Project Portlet
- Then select Vulnerability tab
- There you will see Summary tab which contains total vulnerabilities
Note: If the parent project does not have any subProjects then this Summary tab will not appear.

feat(Project): Added Vulnerability Summary Tab in Projects.

---

pom.xml

Update Apache commons-text to mitigate CVE-2022-42889

fix(project): Update Apache commons-text

---

rest/resource-server/src/docs/asciidoc/releases.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

Issue: #1854 
Description: returns recent created releases.

feat(rest): new endpoint /releases/recentReleases

---

rest/resource-server/src/docs/asciidoc/components.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java

Issue: Subscription list for user in component (MY SUBSCRIPTIONS)
Must:

fix(rest): Added endpoint for mysubscriptions for component

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java

Issue: #1769 
Refer to: #1769
Must:

Fix(Project): Can't disable CR based on Japanese group

---

.github/workflows/build_and_test.yml
.pre-commit-config.yaml

- Add merge conflict check on pre-commit
- Add conventional-commit check on CI

Update pre-commit and ci hooks

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserSearchHandler.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/includes/searchAndSelectIds.js
libraries/datahandler/pom.xml
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java

> * Which issue is this pull request belonging to and how is it solving it? (#1857)
Issue: Searching for user name does not provide usable result
1. Edit a project and go to 'add contributors'
2. Search for the user 'Thomas Graf'
3. The result will contain the best results in descending order (based on score)

fix(UserSearch) : Modified the user search operation

---

rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

Issue: #1880 
Run this endpoint to get list of linked projects.

feat(rest) : endpoint for linked projects

---

rest/resource-server/src/docs/asciidoc/releases.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

Signed-off-by: Nguyen Nhu Tuan <tuan2.nguyennhu@toshiba.co.jp>
Issue: #1571
- Get vulnerability information through Release API
- curl  'https://sw360.org/resource/api/releases/{releasesID}/vulnerabilities’​
- Output:
```
{ …
```

Feat(Release): GET VULNERABILITIES from Release by API #1571

---

backend/src/src-users/src/main/java/org/eclipse/sw360/users/UserHandler.java
backend/src/src-users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
backend/src/src-users/src/test/java/org/eclipse/sw360/users/UserHandlerTest.java
libraries/datahandler/src/main/thrift/users.thrift
rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360GrantedAuthoritiesCalculator.java
rest/resource-server/src/docs/asciidoc/api-guide.adoc
rest/resource-server/src/docs/asciidoc/users.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/basic/Sw360CustomUserDetailsService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/basic/Sw360GrantedAuthoritiesCalculator.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/basic/Sw360GrantedAuthority.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/basic/Sw360UserDetailsProvider.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
scripts/docker-config/etc_sw360/authorization/application.yml
scripts/docker-config/etc_sw360/rest/application.yml
scripts/docker-config/etc_sw360/sw360.properties
scripts/docker-config/portal-ext.properties

* Fix Liferay Company ID that prevents REST operations works properly.
* Extend login timeout to 90 minutes allowing more breath time during development work. 
* Move default of CORS on Rest server to allow all connections instead of deny all connections. This was making the default docker container confuse to setup.

Fix Docker defaults

---

scripts/migrations/053_remove_whitespace_component_name.py

Signed-off-by: Eldrin <eldrin.sanctis@siemens.com>
Added a script that 
1. Identifies and updates the whitespaces in a component's name
2. Links releases of the duplicate component into the existing component
3. Delete the duplicate component
> * Which issue is this pull request belonging to and how is it solving it? (#1827 )
Issue: 
@ag4ums

fix(Script): Modified script such that it removes trailing and leading whitespaces and additonally  link releases of duplicate components

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/js/components/includes/releases/regexjs.js

Issue: #1772 
Refer to: #1772 
Must:

Fix(Component UI): Can not load component detail page with long text of additional data

---

pom.xml
rest/resource-server/pom.xml

Issue: https://github.com/eclipse-sw360/sw360/issues/1808

Normalize javax.activation version

---

libraries/datahandler/pom.xml
pom.xml

Old 4 series is deprecated and non maintained anymore.
Reference: [httpcore](https://mvnrepository.com/artifact/org.apache.httpcomponents/httpcore)

Update to current httpcore5 release

---

rest/resource-server/src/docs/asciidoc/releases.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

Issue: #1860 
This PR is attempt to recover original changes from #1859
The commit is available at: 4d01c9f208e6faead16cd57f19e0fec9daacb5ee

fix(rest): added endpoint for release subscriptions

---

rest/resource-server/src/docs/asciidoc/components.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java

New endpoint for my components
> * Which issue is this pull request belonging to and how is it solving it? (#1855 )
Issue: #1855 
It can be tested using postman or any other supporting API platform. 
URL : …

feat(rest):New end point for my components

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/filter/EndpointsFilter.java
rest/resource-server/src/main/resources/application.yml

Added a property in `application.yml` to put endpoints(endpoints URIs) and  http methods to be blacklisted in the format as shown below.
> * Which issue is this pull request belonging to and how is it solving it? (*#1924*)
Issue:  …

chore(rest): Making endpoints configurable

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java

fix(EditCR): Not able to edit CR

---

rest/resource-server/src/docs/asciidoc/components.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java

- Run this Download Attachment Bundle of Release
Issue: #1955
```
$ curl 'https://sw360.org/api/components/17653524/attachments/download' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4NDIwNTA1NSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6ImdaWjBHaElRMGNLMjlwb0F0Vk56d05NWXBhQSIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.K9HK3NjDl6xHe3e5VUp7RYVU …
```

feat(REST): Endpoint for Download Attachment Bundle of Component

---

rest/resource-server/src/docs/asciidoc/releases.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

- Run this Download Attachment Bundle of Release
Issue: #1955
```
$ curl 'https://sw360.org/api/releases/17653524/attachments/download' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4NDIwNTA1NSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6ImdaWjBHaElRMGNLMjlwb0F0Vk56d05NWXBhQSIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.K9HK3NjDl6xHe3e5VUp7RYVUBH …
```

feat(REST): Endpoint for Download Attachment Bundle of Release

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
libraries/datahandler/src/main/thrift/components.thrift
libraries/datahandler/src/main/thrift/sw360.thrift
rest/resource-server/src/docs/asciidoc/components.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java

- Run this endpoint to get list release overview of a component
Issue: #1912
```
$ curl 'https://sw360.org/api/components/17653524/releases' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4NDQ4OTg3MywiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6InZGRldGYmdaeGFJMEJfSzdWRE10dTc3UTNQRSIsImNsaWVudF9pZCI6InRydXN0ZWQ …
```

feat(api): create new end point get release overview by component

---

backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/VulnerabilityHandler.java
backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityDatabaseHandler.java
libraries/datahandler/src/main/thrift/vulnerabilities.thrift
rest/resource-server/src/docs/asciidoc/releases.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/Sw360VulnerabilityService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

- Run API  update vulnerabilities of a release.
Issue: #1939
```
$ curl 'https://sw360.org/api/releases/3765276512/vulnerabilities' -i -X PATCH \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4NDQwNTg4MSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6InYxeEJUNTFHRXZ0dzZPS0ZMbTV4YkxfYUNZMCIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2 …
```

feat(api): create new endpoint update vulnerabilities of a release

---

backend/src-common/src/main/java/org/eclipse/sw360/spdx/SpdxBOMImporter.java
rest/resource-server/src/docs/asciidoc/components.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java

_Endpoint import SBOM in component page._
Issue:  #1940
```
$ curl 'https://sw360.org/api/components/prepareImport/SBOM?type=SPDX' -i -X POST \
-H 'Content-Type: multipart/form-data' \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4NDczMDM4MywiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6ImhBUzEySkJvNHNwUks3N21XaWxtcF9aa2Z4MCIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY …
```

feat(api): create new endpoint import bom for component

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java

Issue: #1978
```
$ curl 'https://sw360.org/api/components/17653524' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4NTYyMDI0MCwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6ImZUeUV5bktKR19NZE9FMWF1WExWbnBFSkg1VSIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.KVoo7vqIae2M1vDp-Gxi4rFbco6uThR1c1ApDgwoN6b-QZumyGIE1AKdcExRUdQthhk2NpCprTYSqZ6uQOVfi5CLHgag45 …
```

feat(update): update response api get single component

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java

Description : Add Description field for myProjects and myComponents endpoints for homepage
Added 3 more fields(State, ClearingState, ProjectResponsible)  in response structure.
Issue: #1984

fix(rest): Add Description field for myProjects and myComponents.

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java

Issue: #1993
```
$ curl 'https://sw360.org/api/vendors' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4NjMwMTI5MCwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6ImNvLVVEc2ZDNUJfTk51WmtvSFlUTHdpaUI2YyIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.Deh9YtdnQQrsE4iYxEkPQB1A8rq9SjvYQRF9xKjDy4mJ9mkEweYuMfF0iyIF1Mp_gPV7wMHNXqHpkhB-tBC9gofq4KyWwPK0-aeSzMuy7g …
```

feat(rest): update response API Listing vendors

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

Issue: #1976
```
$ curl 'https://sw360.org/api/releases/987456/attachments' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4NTYxOTE5OSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6IlVqdWQxa2ZmcFp0T25JUW8yOUk1ZFpwbEJhSSIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.jCaEtC0k7f_MwN8RId55isYGH7YoHtcbdeHXR2y3FDdQuC62xCHvX_ZigB9LM6na4YkOVUY8YvaeTaac9Fc2vH …
```

feat(REST): Update response endpoint get attachments by release

---

rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java

Issue:  #2026
Command line to Build: 
```
mvn clean package -P deploy -Dbase.deploy.dir=. -Dliferay.deploy.dir=${LIFERAY_INSTALL}/deploy -Dbackend.deploy.dir=${LIFERAY_INSTALL}/tomcat-9.0.56/webapps -Drest.deploy.dir=${LIFERAY_INSTALL}/tomcat-9.0.56/webapps …
```

fix(rest): fix test rest api of component

---

rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

Issue: #1880 
Description: added a query parameter in order to get linked projects of sub-projects also when &transitive=true.

feat(rest): To list linked projects of sub-projects.

---

rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

Adding new fields to get list of project vulnerability
#2035 
NO
Use postman to verify this. 
Sample URL : 
http://localhost:8080/resource/api/projects/{projectId}/vulnerabilities?priority=1+-+critical&priority=2+-+major&projectR …

feat(rest):Adding new fields to get list of project vulnerability

---

rest/resource-server/src/docs/asciidoc/attachments.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/AttachmentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/AttachmentSpecTest.java

- New endpoint create attachments
Issue: #2054
```
curl 'https://sw360.org/api/attachments' -i -X POST \
-H 'Content-Type: multipart/form-data' \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiY …
```

feat(rest): New endpoint create attachments

---

.github/workflows/build_and_test.yml

fix(sw360Build): build failing because of invalid CEN header

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

```
curl 'https://sw360.org/api/releases?allDetails=true' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY5MjAwMjgwOSwiYXV0aG9ya …
```

feat(rest): Add Information Vendor to response Get all Releases detail

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java

```
curl 'https://sw360.org/api/components/17653524' -i -X PATCH \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYW …
```

feat(rest): Add information user to attachment when change status attachment by edit component 

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java

Issue:
- Currently, Response CostDetails of Release is array:
```
"sw360:cotsDetails" : [ {
"usedLicense" : "MIT",
"licenseClearingReportURL" : "http://licenseclearingreporturl.com",
"containsOSS" : true,
"ossContractSigned" : false,
"ossInformationURL" : "http://ossinformationurl.com",
"usageRightAvailable" : false,
"cotsResponsible" : "admin@sw360.org",
"clearingDeadline" : "2016-12-18",
"sourceCodeAvailable" : false,
"_embedded" : {
"sw360:cotsResponsible" : {
"email" : "admin@sw360.org",
"deactivated" : …
```

feat(release): Fix response api get single release with cotsDetails

---

backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorDatabaseHandler.java
backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
libraries/datahandler/src/main/thrift/vendors.thrift
rest/resource-server/src/docs/asciidoc/vendors.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java

Issue:  #2124 
No 
It is a rest end point. It can be tested using Postman client, as follows.
URL : http://localhost:8080/resource/api/vendors/exportVendorDeatails
Click on Send and Download and check the downloaded excel file. …

feat(rest) : End point for export vendor spreadsheet

---

rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/SearchSpecTest.java

> * Which issue is this pull request belonging to and how is it solving it? (#2148)
Issue: Update the sw360 REST API Guide for Search Endpoint

feat(Rest): Modifying the document for search endpoint

---

libraries/exporters/src/main/java/org/eclipse/sw360/exporter/utils/ConvertRecord.java

Issue: #2151 
1: Login with admin user.
2: Go to admin license tab and upload the license file.
Must:

fix(UI) : Fix upload license file in admin tab.

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java

@KoukiHama 
- Execute API  link project to package
```
$ curl 'https://sw360.org/api/projects/3765276512/link/packages' -i -X PATCH \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY5ODY1MjA0NCwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6InM0X2dySURjTmVwUHlIclZsVGdGX0hEYWZHRSIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.f8cmeyOf683xicwDhgh …
```

fix(package): Can't link project to package by API

---

backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageRepository.java

Description:
Now, before creating a new component we will check whether this component already exist in the database or not, on the basis of VCS URL.
Similarly, we also check for the duplicate packages using the purl.
Closes: #2142

feat(importCDX): enhanced sw360 CDX importer

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java

Issue: #2157 
Sample URL : 
Sample response : 
No
Must:

feat(rest) : Add enableSvm field in response to projects api

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java

fix(Moderation): Fix bug could not open Release and Component moderation request

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageRepository.java

Description: 
Two non-functioning view BY_VCS_LOWERCASE and BY_PURL_LOWERCASE has been removed.
Issue:  Closes #2170

fix(importCDX): Remove view BY_VCS_LOWERCASE and BY_PURL_LOWERCASE

---

libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
rest/resource-server/src/docs/asciidoc/vulnerabilities.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java

Issue:  closes #2164 
Description : adding pagination for listing vulnerabilities endpoint.

fix(rest) : adding pagination for listing vulnerabilities endpoint

---

libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
rest/resource-server/src/docs/asciidoc/users.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java

Issue:  Closes #2168 
Description: Adding pagination for listing users endpoint

fix(rest) : adding pagination for listing users endpoint

---

CHANGELOG.md
pom.xml
scripts/migrations/README.md

chore(rel-18): changing files for tagging 18.0

---

backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
rest/resource-server/src/docs/asciidoc/licenses.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java

```
$ curl 'https://sw360.org/api/licenses/Apache-2.0' -i -X PATCH \
-H 'Authorization: BearereyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY5OTQxOTQ0OSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6ImlyaWwxUDF5Rm1uY2kzaThyNlROWFZJemVvTSIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.ggC1M326qKTL6WZhGX-oW-Ti8DGYGNO31g10mFxmgoiT9tIYvZOFnalGBECD5Zcm …
```

feat(license): Create new api update license

---

backend/src/src-fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java

fix(rest-fossology): applied changes for upload endpoint

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java

Document different response codes for `DELETE /projects` endpoint.
@ag4ums
Check the Swagger documentation.
Must:

docs(project): response codes DELETE /projects

---

backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
libraries/datahandler/src/main/thrift/licenses.thrift
rest/resource-server/src/docs/asciidoc/licenses.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java

- Run command.
```
curl 'https://sw360.org/api/reports?module=licenses' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTcwMDQ1NDQ0OSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6InNTMl9GMWdMTFJhM3lPZFM1WFBmVmFFQkJZVSIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.h-0IrjxI1iQ3UREeODRNIJrUIZ9LkB7GJsYERYcaXQ9RKqxENeHK1t8VlfvhIEoXnc3X8u0sbRwR2soIapKMmVnCJtisYzVaNcPZLe3Wiii56N6 …
```

feat(license): Create API Export License

---

scripts/migrations/059_delete_MR_for_user.py

The user email can be hardcoded in the script. All MR's created by that email address will be deleted on successful execution of the script.
Closes: #2193

feat(Script): Delete MR's for a specific user

---

libraries/datahandler/src/main/resources/sw360.properties

Correct file number in properties file

fix(config): Correct file number

---

rest/resource-server/src/docs/asciidoc/api-guide.adoc
rest/resource-server/src/docs/asciidoc/fossology.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/admin/fossology/FossologyAdminController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/admin/fossology/Sw360FossologyAdminServices.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/FossologySpecTest.java

Issue: #2198 
http://localhost:8080/resource/api/fossology/saveConfig
Must:

fix(rest): create a new endpoint to save fossology connection in admin tab.

---

scripts/migrations/060_migrate_project_dependency_network.py

Migration script **060_migrate_project_dependency_network.py** does not work with Python3

fix(script): Fix migration script not working with python3

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/includes/moderationHeader.jspf

Issue: Closes #2228
Description: message "You are the last moderator for this request - you are not allowed to unsubscribe." will be displayed when last moderator try to remove himself from moderator list.

fix(mod): show message when only moderator choose remove me option

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java

Updated the previous error message to: **A component with the same name or VCS already exists.**
Issue:  closes #2215

fix(importCDX): Update failed component creation error message

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java

Updated the query parsing for release external id via rest endpoint
Issue: The code initially was unable to fetch results for external Id that has multiple "="  
Closes #2294 
> @ag4ums 
Must:

fix(release): modify the externalId query parsing

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/LinkedReleasesAndProjectsAwarePortlet.java
frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
libraries/datahandler/src/main/thrift/projects.thrift

- Add configuration **enable.flexible.project.release.relationship=true** to /etc/sw360/sw360.properties
**1. Generate License Info:**
- Select a project to view detail
- Select **License Clearing** tab
- Click on **Generate License Info**
- Select **Project only** (or **Project with sub projects**) to open Generate License screen
**Expect**: Screen will show all the releases in the license clearing tab with attachments and licenses
- Select licenses, click **Download** and choose file format
**Expect**:  Downloaded file will contain all selected licenses
**2. Generate Source Code Bundle:**
- Select a project to view detail
- Select **License Clearing** tab
- Click on **Generate Source Code Bundle**
- Select **Project only** (or **Project with sub projects**) to open **Generate Source …

feat(Project): Extract license and Download source code bundle from all releases in dependency network

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp

Clearing Type field column is now also available for closed clearing request tab.
Closes: #2296

feat(UI): Add clearing type column in closed clearing request tab

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/vulnerabilities.jsp

fix(UI) : Issue fix for vulnerability not displaying for project

---

frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp

feat(UI): enhanced date filter for open and closed clearing requests tab

---

rest/resource-server/src/docs/asciidoc/vulnerabilities.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java

Issue: 
Closes #2303 
URL : http://localhost:8080/resource/api/vulnerabilities/trackingStatus/8b3aa2f81a764fb482d6391516d153db?sortBy=releaseId&sortOrder=false
Sample response : 
Must:

feat(rest) : Pagination for vulnerability tracking status

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java

Issue: Closes #2314 
http://localhost:8080/resource/api/projects/{project_id}
Must:

fix(rest): Added modifiedBy field in project search by project id.

---

.github/actions/docker_control/action.yml
.github/actions/docker_control/check_image.py
.github/workflows/docker_deploy.yml

feat(docker): Improve output of check_image script.

---

scripts/migrations/061_add_modifiedBy_modifiedOn_project.py
scripts/migrations/README.md

Issue: Closes #2316 
resource/api/projects/{id}/summary/administration
ex: resource/api/projects/c109935d14e846c4afe03a8f3e97798b/summary/administration
will not give 500 error(internal server error)
> How should these changes be …

fix(script): update modifiedBy/modifiedOn project fields.

---

.github/workflows/docker_deploy.yml
docker-compose.yml
docker_build.sh

fix(docker): Fix broken binaries context inclusion

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
libraries/datahandler/src/main/thrift/projects.thrift
rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

closes : #2248 
#2248 
No
URL : http://localhost:8080/resource/api/reports?withlinkedreleases=false&module=projects&projectId=bf1570a235414de486eb1043d4b0c0a8&mailrequest=false …

feat(Rest) : Download license clearing spreadsheet.

---

frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf

Issue: Closes #2320
- Edit project and go to obligations
- Click on Add Obligations from License Database
- There you can see obligationType of different license obligations.
- Click on Add button and then update the project, same data will reflect on license obligation table.
###Screenshots

feat(Obligation): adding obligation type data in lic obligation table

---

backend/src/src-users/src/main/java/org/eclipse/sw360/users/UserHandler.java
backend/src/src-users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
libraries/datahandler/src/main/thrift/users.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java

Issue: Closes : #2334 
http://localhost:8080/resource/api/users/?page=true&page_entries=10&sort=name&givenname=test&luceneSearch=true
> Have you implemented any additional …

feat (Rest): Rest endpoint to search User Byname using lucene search.

---

rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

Issue: Closes #2291 
Description: Add license obligations to a project

feat(obligation): add license obligations to a project

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageDatabaseHandler.java
backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageRepository.java

Description:
This pull request enhances the process of component and package creation by implementing case-insensitive comparison during the validation of existing components and packages based on Version Control System (VCS) and Package URL (PURL).
Closes: #2370

fix(importCDX): Add check for existing comps and package using case-insensitive comparison of vcs and purl

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java

Issue: 
https://github.com/eclipse-sw360/sw360/issues/2310
> @afsahsyeda 
Must:

fix(SRCUploadService): Source upload should work for release versions having alphanumeric characters

---

.github/workflows/build_and_test.yml

fix(sw360): changing mkdocs version

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java

Issue: Closes #2406 
Description: Adding pagination feature for vulnerability tracking status endpoint.

feat(rest): added pagination for vulnerability tracking status page.

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

Issue: Closes #2397 
Description: Added release field & pagination for licenseObligation get endpoint
Run the endpoint for licenseDbObligations,
http://localhost:8080/resource/api/projects/{projId}/licenseObligations

feat(project): Added release field & pageable for licenseObligation endpoint

---

pom.xml

Reverts eclipse-sw360/sw360#2325
Closes #2386

Revert "build(deps): bump org.apache.commons:commons-compress from 1.21 to 1.26.0"

---

backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/Sw360ModerationRequestService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

**Description**:
REST API Endpoint to create clearing request for a project.
Closes #2272

feat(REST):Create clearing request for a project

---

CHANGELOG.md
pom.xml

chore(rel-18.1): changing files for tagging 18.1

---

.github/issue_template.md
.github/pull_request_template.md

Restore pull_request_template.md and create issue_template.md from changes in 73ea0cf32630304a3903d13db2b587b76af23279

fix(github): restore pull_request_template.md

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java

Issue: 
Closes : #2531 
http://localhost:8080/resource/api/packages?page=0&page_entries=3&allDetails=true
Must:

fix(rest): Added a missed field in package endpoint for allDetails.

---

pom.xml
rest/resource-server/pom.xml
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
rest/resource-server/src/main/resources/application.yml
rest/resource-server/src/test/resources/application.yml

> * Which issue is this pull request belonging to and how is it solving it? (*[Refer to issue here](https://github.com/eclipse-sw360/sw360/issues/2543)*)
> * Did you add or update any new dependencies that are required for your change? - 
Yes, Upgraded the jakarta xml bind and spring docs openapi versions
Issue: https://github.com/eclipse-sw360/sw360/issues/2543
Link to test the swagger UI: …

fix(rest): Fixed the swagger issue

---

pom.xml
rest/resource-server/pom.xml
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
rest/resource-server/src/main/resources/application.yml
rest/resource-server/src/test/resources/application.yml

Reverts eclipse-sw360/sw360#2548

Revert "fix(rest): Fixed the swagger issue"

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/packages/PackageController.java

Issue: Closes: #2539 
http://localhost:8080/resource/api/packages/{id}
Must:

fix(rest): Added modifiedBy field in get package_by_id endpoint.

---

backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxUtils.java

fix(backend) : Product clearing report generated has strange numbering issue fix.

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java

Closes : #2477 
fix(rest) : Non uniform link format in attachmentUsage end point

fix(rest) : Non uniform link format in attachmentUsage end point

---

rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/client/service/Sw360OidcUserInfoService.java
rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/SecurityConfig.java
rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360TokenCustomizerConfig.java
rest/authorization-server/src/main/resources/application.yml
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/jwt/Sw360JWTAccessTokenConverter.java

> * Which issue is this pull request belonging to and how is it solving it? ([#2558 ](https://github.com/eclipse-sw360/sw360/issues/2558))
Issue: Closes #2558
1. Kindly add the redirect URL(`http://localhost:3000/api/auth/callback/sw360-backend`) in the Oauth2 client as below for the connection to the new UI. …

fix(rest): Added the OIDC user info customizer and token customizer

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java

fix(rest): Add null check for linkedProject field to prevent Internal Server Error on GET request to fetch the linked projects of a project

---

backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
rest/resource-server/src/docs/asciidoc/licenses.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/obligation/ObligationController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ObligationSpecTest.java

- Add API listing LicenseType
- Add pageable for License
- Add pageable for Obligations
```
curl 'https://sw360.org/api/licenseTypes' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTcxMjkxMjE1NSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6Imc4aFpNTTFTcVQ5U0pOZFhHVDhIV2ZidGUtTSIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.D10d5BWiJUscAlja_26mUYNmSp-9 …
```

feat(License): Add API Listing LicenseType and Add pageable for licenses, obligations

---

rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

Issue: Closes #2418 
Test:
Run the endpoint to get the releases of the linked projects for a project.
http://localhost:8080/resource/api/projects/71057adec8094a98baf7c16524ea1f62/linkedProjects/releases

feat(rest): Adding new endpoint to get releases of linked projects.

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/packages/PackageController.java

Issue: #2533 
Description: fixing pagination for packages get endpoint.

fix(rest): fixing pagination for endpoint '/packages'

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java

…maryAdministraion endpoint.
Issue: Closes: #2546 
http://stage.sw360.siemens.com/resource/api/projects/{ID}/summaryAdministration
Must:

fix(rest): Added code to resolve the server error while fetching a summaryAdministraion endpoint.

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java

The commit from #2568 is in latest main but the changes are missing. Adding back the changes with cherry-pick.

fix(rest): Add null check for linkedProject field

---

backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMExporter.java
pom.xml

Description:
Fixes vulnerability caused by old version of cyclone-dx-core java #2495.
Updates related dependencies and functions.
1. Import CDX SBOM
2. Export CDX SBOM

feat(CycloneDX): Update cyclonedx-core-java and jackson version

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java

closes : #2617 
**Endpoint** : http://localhost:8080/resource/api/vulnerabilities/trackingStatus/{projectId}

fix(rest): Resolved null value returning for svm tracking status.

---

keycloak/README.md
keycloak/event-listeners/pom.xml
keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/listener/Sw360CustomEventListenerProvider.java
keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/listener/Sw360CustomEventListenerProviderFactory.java
keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/listener/service/Sw360KeycloakAdminEventService.java
keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/listener/service/Sw360KeycloakUserEventService.java
keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/listener/service/Sw360UserService.java
keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/model/Access.java
keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/model/Attribute.java
keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/model/Group.java
keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/model/UserEntity.java
keycloak/event-listeners/src/main/java/org/eclipse/sw360/keycloak/event/model/UserProfileMetadata.java
keycloak/event-listeners/src/main/resources/META-INF/services/org.keycloak.events.EventListenerProviderFactory
keycloak/pom.xml
keycloak/register.ftl
keycloak/user-storage-provider/pom.xml
keycloak/user-storage-provider/src/main/java/org/eclipse/sw360/keycloak/spi/Sw360UserStorageProvider.java
keycloak/user-storage-provider/src/main/java/org/eclipse/sw360/keycloak/spi/Sw360UserStorageProviderFactory.java
keycloak/user-storage-provider/src/main/java/org/eclipse/sw360/keycloak/spi/model/UserAdapter.java
keycloak/user-storage-provider/src/main/java/org/eclipse/sw360/keycloak/spi/model/UserEntity.java
keycloak/user-storage-provider/src/main/java/org/eclipse/sw360/keycloak/spi/service/Sw360UserService.java
keycloak/user-storage-provider/src/main/resources/META-INF/services/org.keycloak.storage.UserStorageProviderFactory
pom.xml
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/jwt/Sw360JWTAccessTokenConverter.java
rest/resource-server/src/main/resources/application.yml
rest/rest-common/pom.xml

As we are not completely offloading our users to keycloak storage yet, hence it is useful to use these libraries or keycloak custom service provider interfaces to make use of our couchdb `sw360user` database as the user storage and at the same time we can use the other features of keycloak like creating client, managing users, etc and adding external identity providers etc.
> * Which issue is this pull request belonging to and how is it solving it? (*#2586*)
> * Did you add or update any new …

feat(keycloak-spis): Added the custom keycloak SPIs

---

rest/resource-server/src/docs/asciidoc/users.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java

create a new to  fetch the group list component in project add and edit page.
Closes : #2469
Add screenshots to help explain your problem.

feat(rest): Create a new rest api to fetch group list in project add and edit page.

---

backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
libraries/datahandler/src/main/thrift/projects.thrift
rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

Turn on feature by adding this property into /etc/sw360/sw360.properties: **enable.flexible.project.release.relationship=true**
Step 1: Create a new project with dependency network:
- Url: http://localhost:8080/resource/api/projects/network
- Method: POST
- Body: 
```
{
"name": "Test_PR",
"dependencyNetwork": [
{
"releaseId": "${release_id_1_in_sw360}", // Replace this by an existing release id in sw360
"releaseRelationship": "CONTAINED",
"mainlineState": "OPEN",
"comment": "",
"createOn": "2024-07-05",
"createBy": "admin@sw360.org",
"releaseLink": [
{
"releaseId": "${release_id_2_in_sw360}", // Replace this by an existing release id in sw360 (difference from above)
"releaseRelationship": "OPTIONAL",
"mainlineState": "MAINLINE",
"comment": "",
"createOn": "2024-07-05",
"createBy": …
```

feat(Project): Create new endpoint to serve list view of dependency network (New GUI)

---

rest/resource-server/src/docs/asciidoc/projects.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

feat(rest) : Rest end point for generate source code bundle

---

keycloak/event-listeners/pom.xml
keycloak/pom.xml
keycloak/user-storage-provider/pom.xml
pom.xml

fix(pom): fixed the java version in kc module pom.xml

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/Sw360ModerationRequestService.java

Closes: #2503 
Upon clicking the "Accept Request" button for a moderation request, the REST API response returns a 202 (Accepted) status. However, the database is not being updated with the proposed changes. For example, if a project page is edited and a moderation request is created, accepting the proposed changes does not update the project page with the new values; it still shows the old values.
Please describe your issue in few words here.
Describe the bug and list the steps you used when the issue occurred.
Add screenshots to help explain your problem.
* Docker version OR
* Last commit id on main
* With docker through `docker logs sw360`
* From bare metal / vm install system under /var/log/sw360/sw360.log and /var/log/tomcat/error.log

fix(rest) : modified accept request to see the proposed changes in Project/Component/Release to moderation request rest Api.

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java

https://github.com/eclipse-sw360/sw360/security/code-scanning/80
https://github.com/eclipse-sw360/sw360/security/code-scanning/81
Must:

Fix CodeQL vulnerability warning

---

keycloak/event-listeners/pom.xml
keycloak/pom.xml
keycloak/user-storage-provider/pom.xml
pom.xml

- Move all versions from keycloack pom to superpom
- Adjust version or spring.security to be unique
- Replaced jaxb javax to jakarta
- Removed duplicate maven-sources entry

Adjust Maven dependency declarations

---

backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java

feat(importCDX): enhance CDX importer to sanitize VCS URLs for non-GitHub domains

---

backend/moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java

Fix creation of moderation request when there is no moderation request for a project/component exists.
@smrutis1
Modify a project/component from non-admin user which does not have pre-existing moderation request.

fix(moderation): fix moderation creation

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java

Issue: #2763 
Description:
adding additional fields(release clearing state and component type) to attachmentUsage endpoint.

fix(rest): adding additional fields to attachmentUsage endpoint.

---

rest/resource-server/src/docs/asciidoc/moderationRequests.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationRequestController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ModerationRequestSpecTest.java

Closes: #2794 
http://localhost:8080/resource/api/moderationrequest/validate?entityType=" "&entityId={ID}
entityType = PROJECT/COMPONENT/RELEASE
entityId= PROJECTID,COMPONENTID,RELEASEID …

fix(rest): Validate whether a user is a moderator.

---

rest/resource-server/src/docs/asciidoc/schedule.adoc
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/ScheduleAdminController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/Sw360ScheduleService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ScheduleSpecTest.java

Issue: #2882 
api/schedule/scheduleSourceUploadForReleaseComponents
Must:

fix(Rest): Updated the REST endpoint to schedule the upload of release component attachments.

---

backend/common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
backend/users/src/main/java/org/eclipse/sw360/users/UserHandler.java
backend/users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
libraries/datahandler/src/main/thrift/users.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/UserTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java

Add 2 new endpoints for
- Updating user
- Listing all existing departments
- **Method**: PATCH
- **Url**: http://{ip}:8080/resource/api/users/{user_id}
- **Request**:
```json
{
"email": "clearingex001@sw360.org",
"givenName": "clearingex001",
"lastName": "test",
"department": "DEPARTMENT1",
"fullName": "clearingex001 test",
"userGroup": "CLEARING_EXPERT"
}
```
- **Example response**:
```json
{
"email" : "clearingex001@sw360.org",
"userGroup" : "CLEARING_EXPERT",
"externalid" : "sw360clearingex001",
"department" : "DEPARTMENT1", …
```

feat(User): Add 2 new endpoints for updating user and listing existing departments

---

scripts/addUnsafeDefaultClient.sh

Closes #2608
@amritkv
Create default user and client by running `./scripts/addUnsafeDefaultClient.sh`

fix(script): fix addUnsafeDefaultClient.sh script

---

backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMExporter.java

This PR updates the CycloneDX exporter dependency from version 1.4 to 1.6 to ensure compatibility with the latest features and improvements

feat(exportCDX): update CycloneDX exporter dependency from v1.4 to v1.6

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/SimpleAuthenticationEntryPoint.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/apiToken/ApiTokenAuthenticationFilter.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/apiToken/ApiTokenAuthenticationProvider.java

fix(Token): Fix bug authentication by user token not working

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/AttachmentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/HalResource.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/search/SearchController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

Fix typo in
`/api/projects/{id}/addLinkedRelesesLicenses` to
`/api/projects/{id}/addLinkedReleasesLicenses`
Must:

chore(controller): fix typo in endpoint name

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java

Set the required release fields in `Sw360ProjectService:getLicenseObligationData()`
Add obligations to project using `POST /projects/{id}/licenseObligation` endpoint.

fix(project): set fields getLicenseObligationData

---

rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/TestHelper.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java

* Implemented test cases for update and download endpoints,
* Ensured proper response validation using TestRestTemplate and MockMvc.

feat(rest): Added tests for upload and download components

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/admin/fossology/FossologyAdminController.java

Fix OpenAPI docs for `/fossology/saveConfig`
Test the OpenAPI doc for the endpoint.

fix(docs): fix OpenAPI docs /fossology/saveConfig

---

libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

Return list of releases which were effected by call to `POST /addLinkedReleasesLicenses` endpoint.
Closes #2844
Make a call to the endpoint and check if all the updated releases are returned.
Must:

fix(project): return updated releases

---

rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/admin/attachment/AttachmentCleanUpControllerTest.java

This Pull Request contains Unit Test for AttachmentCleanUpController
No

Unit test for attachment cleanup controller

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentMergeSelector.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java

Validate if component merge selection contains all of required fields. If not, throw a bad request exception.
Closes #3107
Check #3107

feat(component): validate merge selection

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/ImportExportController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/importexport/Sw360ImportExportService.java

Download Users in CSV format.
Closes #3109 
by calling new GET endpoint `importExport/downloadUsers`

feat(rest): download users endpoint in CSV format

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java

Issue: #3131 
Description: run the endpoint (/releases/{id}/licenseData/{attachmentContentId}) to get the license data present in release attachment.

feat(rest): getting license data from release attachment.

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java

Allow passing attachments to merge selection body.

fix(component): read list of attachments for merge

---

backend/licenses-core/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
backend/licenses-core/src/main/java/org/eclipse/sw360/licenses/db/LicenseTypeRepository.java
backend/licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
libraries/datahandler/src/main/thrift/licenses.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java

Issue: #3113 
Get: http://localhost:8080/resource/api/licenseTypes?search=test&page=0&page_entries=5
Must:

Fix(Rest): Add quick search for license type.

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/Sw360ScheduleService.java

Fix "Check for Admin access"  before hitting admin schedule endpoints.
Make a request to any one of the schedule endpoints using admin credentials.

fix(rest): fix permission check

---

backend/common/src/main/java/org/eclipse/sw360/datahandler/db/spdx/document/SpdxDocumentDatabaseHandler.java
backend/spdxdocument/src/main/java/org/eclipse/sw360/spdxdocument/SPDXDocumentHandler.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
libraries/datahandler/src/main/thrift/spdx/spdxdocument.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java

continue working in pr https://github.com/eclipse-sw360/sw360/pull/3092 after rebase with main

feat(rest): add SBOM file validation for SPDX and CycloneDX formats

---

backend/common/src/main/java/org/eclipse/sw360/datahandler/db/PackageSearchHandler.java
backend/packages/src/main/java/org/eclipse/sw360/packages/PackageHandler.java
libraries/datahandler/src/main/thrift/package.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/packages/PackageController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/packages/SW360PackageService.java

https://github.com/eclipse-sw360/sw360/issues/3067
Issue: 
Closes : #3067 
API to test :
http://localhost:8080/resource/api/packages?allDetails=true&luceneSearch=true&name=django
Must:

feat(Rest): Advance search for packages

---

libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/obligation/ObligationController.java

Issue: 
Sample URL : http://localhost:8080/resource/api/obligations?search=compo&page=0&page_entries=5
Sample respo : 
```json
{
"_embedded": {
"sw360:obligations": [
{
"text": "Component_Obgn_1 Component_Obgn_1",
"whitelist": [],
"title": "Component_Obgn_1", …
```

feat(rest) : QuickFilter for Obligation page.

---

backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
backend/common/src/main/java/org/eclipse/sw360/datahandler/db/SW360ConfigsDatabaseHandler.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360ConfigKeys.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
libraries/datahandler/src/main/thrift/sw360.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java

> * Added a new config parameter to provide RegEx pattern of trusted url which will be persisted to couch DB
> * Code validates sources code against the trusted urls and then checks if the url is reachable to validate its existance
Closes #3176
@GMishx 
> on providing invalid source code url UI shows error
Must:

feat(Release) : Automate_check_for_Source_Code_Download_URL

---

rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseMergeSelector.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java

Closes #3160 
PATCH: http://localhost:8080/resource/api/releases/mergereleases?mergeTargetId=730e1c64f66715a2868ced346b00697f&mergeSourceId=730e1c64f66715a2868ced346b005dc6
Body :
```json
{
"name": "Final Release Name",
"createdOn": "2025-05-14",
"createdBy": "emailId", …
```

fix(rest): add endpoint to  merge two releases.

---

backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
libraries/datahandler/src/main/thrift/components.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java

Issue: #3187 
Get: http://localhost:8080/resource/api/components/{Id}
Must:

fix(rest): handle missing component ID with 404 response.

---

libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseRepositoryCloudantClient.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/NouveauLuceneAwareDatabaseConnector.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceListController.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationRequestController.java

This PR is part of group of PRs for fixing pagination in controllers.

feat(datahandler): prepare for paginated queries

---

backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
backend/common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
backend/common/src/main/java/org/eclipse/sw360/datahandler/db/UserSearchHandler.java
backend/users/src/main/java/org/eclipse/sw360/users/UserHandler.java
backend/users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/NouveauLuceneAwareDatabaseConnector.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
libraries/datahandler/src/main/thrift/users.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/UserTest.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java

Paginate /user endpoint on DB.
1. Check if `/users` endpoint is paginated without parameter.
2. Check if different type of searches are working on the `/users` endpoint.

chore(rest): paginate users endpoint on DB

---

rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/UserTest.java

This PR adds the IT for user endpoints.
Summary: As part of migrating the REST API test cases from Spring-Doc to open API, have migrated all the Integration tests for user endpoints from UserSpecTest to UserTest. 
@GMishx
How To Test?
Must:

test(integration): added user integration tests in UserTest

---

rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ImportExportTest.java

This PR adds the IT for importExport endpoints.
Summary: Added additional tests in  importExportTest file. 
@GMishx
How To Test?
Must:

test(integration): added additional importExport integration tests in ImportExportTest

---

rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/VendorTest.java

This PR adds the IT for vendor endpoints.
Summary: Created VendorTest file and add the integration tests by extending the TestIntegrationBase class.
@GMishx
How To Test?
Must:

test(integration): Added Vendor integration tests in VendorTest

---

rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/VulnerabilityTest.java

This PR adds the IT for Vulnerability endpoints.
Summary: Created VulnerabilityTest file and add the integration tests by extending the TestIntegrationBase class.
@GMishx
How To Test?
Must:

test(integration): Added Vulnerability integration tests in VulnerabilityTest

---

rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ChangeLogTest.java

This PR adds the IT for ChangeLog endpoints.
Summary: Created ChangeLogTest file and add the integration tests by extending the TestIntegrationBase class.
@GMishx
How To Test?
Must:

test(integration): Added ChangeLog tests in ChangeLogTest

---

rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/DepartmentTest.java

This PR adds the IT for Department endpoints.
Summary: Created DepartmentTest file and add the integration tests by extending the TestIntegrationBase class.
@GMishx
How To Test?
Must:

test(integration): Added Department tests in DepartmentTest

---

backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMExporter.java
backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
libraries/datahandler/src/main/thrift/projects.thrift
libraries/datahandler/src/main/thrift/sw360.thrift
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
scripts/migrations/062_update_packagIds_to_map.py

Closes #3339
> 
Run scripts/migrations/062_update_packagIds_to_map.py script to migrate the data structure from set to map.
Before :
"packageIds": ["31d1f90490cfab584b781114190d8219","097ac95305f9224516068b4b438576b5"]
After :
"packageIds": {
"31d1f90490cfab584b781114190d8219": {
"comment": "",
"createdBy": …

feat(Rest): Added comment for package table in LinkedPakages
