eclipse-sw360/sw360

- .gitignore
> chore(git): restore .gitignore that's gone missing during the move

- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseHelper.java
- adds new column "project mainline state" to the release spreadsheet export file
closes eclipse/sw360#130
> feat(release): Add project mainline state to export spreadsheet (clearing status)

- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- add "Delivery Start" field to REST API guide (project)
closes eclipse/sw360#264
> chore(rest): Add delivery start date to REST API guide

- frontend/sw360-portlet/src/main/webapp/css/dataTable_SiemensHomepage.css
- frontend/sw360-portlet/src/main/webapp/html/homepage/mycomponents/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/homepage/myprojects/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/homepage/mytaskassignments/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/homepage/mytasksubmissions/view.jsp
- truncates the datatable content on homepage
closes eclipse/sw360#156
> fix(homepage): Truncate long document names in homepage datatables

- frontend/sw360-portlet/src/main/webapp/html/projects/ajax/linkedProjectsAjax.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/linkedProjectsEdit.jspf
- frontend/sw360-portlet/src/main/webapp/html/utils/ajax/linkedReleasesAjax.jsp
- frontend/sw360-portlet/src/main/webapp/html/utils/ajax/linkedReleasesRelationAjax.jsp
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/editLinkedReleases.jspf
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/linkedReleasesEdit.jspf
this pull request fixes the table styling (column width, column overlap) for:
- linked projects, Project, EDIT Mode
- linked releases, Projects, EDIT Mode
- linked releases, Components, EDIT Mode
closes eclipse/sw360#112
> fix(ui): Fix table styling for components and projects

- backend/src/src-attachments/src/test/java/org/eclipse/sw360/attachments/AttachmentHandlerTest.java
- libraries/lib-datahandler/src/main/thrift/users.thrift
- libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/jgivens/WhenComputePermissions.java
- libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/jgivens/WhenComputeVisibility.java
- change the user id field to optional
Note: Only `email` and `department` is required for a `User` object.
closes eclipse/sw360#277
(requires new sw360 release version?)
> fix(user): Change user id field to optional

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/AttachmentPortletUtils.java
- libraries/commonIO/src/main/java/org/eclipse/sw360/commonIO/AttachmentFrontendUtils.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/AttachmentStreamConnector.java
- libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/common/CommonUtilsTest.java
- libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/couchdb/AttachmentStreamConnectorTest.java
- handles duplicate attachment names in source code bundle generation zip
- switched to unsafeAttachmentDownload for single attachment selection / **WORKAROUND**
_(user select only one attachment in the source code bundle generation)_
Example of source code attachments with duplicate name:
- example.zip
- example (1).zip
- example (2).zip
- source.tar.gz
- source (1).tar.gz
closes eclipse/sw360#126
> fix(datahandler): Handle duplicate names in source code bundle generation

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
this Pull Request updates the autoset functionality for releases. Added the following check:
- Only update (autoset) ECC options if the release is a OSS component
closes eclipse/sw360#272
> chore(components): Autoset ECC options should check if component is OSS

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/VendorPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
The file name of a spreadsheet for a specific project contains now:
- project (constant value)
- project name and version
- created on date
e.g.
**Filename (export spreadsheet in a view):** 
`projects-2018-06-14.xlsx` or `components-2018-06-14.xlsx`
**Filename (selected project):**
`project-MyTestProject-V1.2-2018-06-14.xlsx`
closes eclipse/sw360#223
> chore(projects): Change the file name of export spreadsheet

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectSearchHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseSearchHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserSearchHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/VendorSearchHandler.java
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- backend/src/src-search/src/main/java/org/eclipse/sw360/search/db/AbstractDatabaseSearchHandler.java
- backend/src/src-users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
- backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/searchReleases.jsp
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
- libraries/lib-datahandler/src/main/thrift/components.thrift
- libraries/lib-datahandler/src/main/thrift/projects.thrift
- remove all special characters (sanitizeQueryInput)
- lucene search for linked releases or projects
- set focus to search button (enter) for linked releases
- advanced search attributes for projects should be sticky
- add sw360 out tag for project advanced attributes
closes eclipse/sw360#129
> fix(search): Remove wildcard in advanced search for projects and components

- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/Sw360AuthorizationServer.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360AuthenticationProvider.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360AuthorizationServerConfiguration.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360SecurityEncryptor.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360WebSecurityConfiguration.java
- rest/authorization-server/src/main/resources/application.yml
- rest/authorization-server/src/test/java/org/eclipse/sw360/rest/authserver/ClientCredentialsGrantTest.java
- rest/authorization-server/src/test/java/org/eclipse/sw360/rest/authserver/IntegrationTestBase.java
- rest/authorization-server/src/test/java/org/eclipse/sw360/rest/authserver/ResourceOwnerCredentialsGrantTest.java
- rest/authorization-server/src/test/java/org/eclipse/sw360/rest/authserver/SecurityEncryptorTest.java
- rest/resource-server/src/docs/asciidoc/api-guide.adoc
- enable to store client id and client secret in the sw360.properties file
**keys:**
- "rest.security.client.id"
- "rest.security.client.secret"
closes eclipse/sw360#239
> feat(rest): Read client id and client secret from configuration file

- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
- validates the obligation object before `ThriftUtils.getIdMap`
closes eclipse/sw360#287
> fix(licenses): Validate obligation list in LicenseDatabaseHandler

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/AttachmentPortletUtils.java
Set content encoding to identity for gzip files.
closes eclipse/sw360#299
> fix(attachments): Set content encoding to identity in case of gzip files

- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
the search limit used to be not applied to release, user, and vendor search
> fix(search): impose the defined search limit on all searches by default

- backend/src-common/src/main/java/org/eclipse/sw360/components/summary/LicenseSummary.java
- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/licenses/detail.jsp
- frontend/sw360-portlet/src/main/webapp/html/licenses/edit.jsp
- frontend/sw360-portlet/src/main/webapp/html/licenses/includes/detailSummary.jspf
- frontend/sw360-portlet/src/main/webapp/html/licenses/includes/editDetailSummary.jspf
- frontend/sw360-portlet/src/main/webapp/html/licenses/view.jsp
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/LicensePermissions.java
- libraries/lib-datahandler/src/main/thrift/licenses.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
This allows everyone to create licenses, but the created licenses are marked as unchecked.
Since there is no owner concept on licenses, everyone is able to modify every unchecked license, and no moderation requests are generated.
closes #190
> feat(licenses): allow to create unchecked licenses

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
@mcjaeger 
I found a bug at editing a component:
* assume a component with two releases
* in the releases, you have some values for aggregation, such as programming languages
* on the component record, the values for the releases show up there in the "release aggregated data" section
* if you then edit the component at a plain attribute, such as "homepage" and save, then the release aggregated data is lost 7 empty.
Here is solution - we can update component properties if they are in request. If not, we will not setup empty data from request to component entity before save.
> fix(component): Do not update component properties if they are not in request

- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
For advanced search with `group` or `tag` phrase searches should be used.
closes eclipse/sw360#337
> fix(projects): Enable phrase search for group and tag in projects

- frontend/sw360-portlet/src/main/webapp/html/projects/includes/attachmentSelectTable.jspf
Sending license texts in the request to generate license info file is unnecessary. In some cases, it makes the request body so large that the tomcat refuses to serve it and the user receives HTTP 502 from the reverse proxy server.
> fix(licenseInfo): remove the hidden license text input field from license info generation page

- backend/src/src-attachments/src/main/java/org/eclipse/sw360/attachments/AttachmentHandler.java
- backend/src/src-attachments/src/test/java/org/eclipse/sw360/attachments/AttachmentHandlerTest.java
fix assertion exception when requesting attachment uses with empty ids set
closes eclipse/sw360#346
> fix(projects): fix assertion exception when requesting attachment uses with empty ids set

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
Fix `createEmbeddedUser` (moderators) logic to prevent error messages
closes eclipse/sw360#355
> fix(rest): Correct REST embedded User to prevent error messages

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
- backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseRepository.java
- libraries/lib-datahandler/src/main/thrift/projects.thrift
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- new REST API endpoint to list projects based on external ids
- added documentation (project page)
closes eclipse/sw360#247
> feat(rest): Add externalId endpoint (projects) to REST API

- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
Currently the following request will throw an NPE:
`GET /components?page=0&sort=ownerCountry`
This PR will fix this bug.
> fix(rest): Trying to sort components by an unsupported property causes NPE

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/licenses/includes/editDetailSummary.jspf
currently it is not possible to modify and update licenses via the UI, due to
the problem that the `disabled` checked-flag is not send back to the server in
the post request. Changing it to `readonly` fixes the problem.
> fix(license): fix problem in editing licenses

- backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityRepository.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/vulnerabilities/VulnerabilitiesPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/vulnerabilities/view.jsp
In our specific vulnerability management system we don't have any information about last external update of the vulnerability. For SW360 the last external update value is necessary to list all vulnerabilities in the `vulnerability tab`. <br> <br>
This PR supports also vulnerabilities without any `lastExternalUpdate` information.
> chore(vulnerabilities): Improve handling of null values in lastUpdate

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserResourceProcessor.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/UserTest.java
Use the correct endpoint `/users/byid/:id` to access a user by id.
Signed-off-by: Andreas Greimel <external.andreas.greimel@bosch-si.com>
> fix(rest): Fix self link for user resource

- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceListController.java
Currently, if there are no components, one gets 404 with every request. This simple PR fixes that and returns an empty response if one asks for (the first) elements of an empty list.
> fix(rest): do not answer with 404 if resource list is empty

- frontend/sw360-portlet/src/main/webapp/js/modules/codeScoop.js
Codescoop have new feature: we describe categories as hierarchical tree.
After intro of such feature we need to match sw360 API data interface
> feat(codescoop): support new subcategories model

- backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/domain/WsProjectVitalInformation.java
- backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/entitytranslation/WsLicenseToSw360LicenseTranslator.java
- backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/rest/WsImportService.java
- backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/rest/WsRestClient.java
- backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/service/WsImportHandler.java
- backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/thrift/ThriftUploader.java
- backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/utility/TranslationConstants.java
At the moment Whitesource sees for example maven project submodules as components in other submodules so this PR goes through the project list and ensures that projects are not created as components in sw360. Also includes small code refactoring.
Signed-off-by: Kalle Soranko <ksoranko@verifa.io>
> fix(wsimport): remove projects from components that are created

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/RepositoryUtils.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseRepository.java
- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java
- allows to search for externalId keys without values like (.../searchByExternalIds?external-id-key or .../searchByExternalIds?external-id-key=)
- added some tests for missing API docs (create project, create release, externalIds for components...)
- some small bugfixes regarding vulnerability/vendor ids (URL selflink was null)
closes #361 
> feat(rest): Allow to search only by externalId-Key (without specific value)

- backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/VulnerabilityHandler.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- fix bug if user creates a project without linked releases over rest
- added visibility to rest interface (project mixin)
closes eclipse/sw360#434
> chore(vulnerabilities): Linked releases can be empty or null (rest create project)

- .travis.yml
- libraries/lib-datahandler/pom.xml
- pom.xml
- scripts/install-thrift.sh
- sw360dev.Dockerfile
It would also possible to update to thrift 0.12.0, but the corresponding libthrift is not yet available on maven central.
This also implies that one needs to update the thrift compiler on the build host to version 0.11.0, this can be done via the script `scripts/install-thrift.sh` (e.g. on ubuntu).
> chore(thrift): update thrift version to 0.11.0

- frontend/sw360-portlet/src/main/webapp/js/modules/ajax-treetable.js
- fix endless loop in the attachment usage view
- projects needs to have sub project
- the sub project has no releases linked nor sub projects
- it is about an empty "leaf node"
closes #445
> fix(ui): Fix infinity loop by expanding empty projects in AttachmentUsage

- backend/src/src-licenseinfo/pom.xml
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- backend/src/src-licenseinfo/src/main/resources/textLicenseInfoFile.vm
- backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGeneratorTest.java
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/attachmentSelectTable.jspf
* the new version of tools does not contain dom4j as dependency anymore. As we use it in the tests it is now directly declared with scope test
* the template for text license info files was modified to ensure that every release is on its own line
* deprecated and removed jquery api was fixed (error replaced by fail)
Closes #128
> refactor(velocity): update to new version

- frontend/sw360-portlet/src/main/webapp/css/jquery.treetable.theme.sw360.css
`<sw360:out>` tag adds a `<span>` around the text when it is necessary to abbreviate it. Padding such `span`s inside treetables leads to inconsistent and misleading indentation.
Removing the padding seems to have no drawbacks.
> fix(treetables): fix inconsistent indentation in treetables

- backend/src/src-licenseinfo/pom.xml
- backend/src/src-licenses/pom.xml
- fix velocity dependencies problem
`
NoSuchMethodError: org.apache.commons.lang3.StringEscapeUtils.escapeXml
`
> fix(licenseinfo): Exclude old commons-lang3 dependencies

- .travis.yml
- scripts/compileWithDocker.sh
- scripts/install-thrift.sh
This minor change. We do not need to build with the `--with-java` flag, since we get the java libraries from maven. We only need the core compiler.
If this java is not disabled, the thrift build step tries to download a jar dependency while compiling.
##
This can be tested by running 
```
$ mvn clean
$ scripts/compileWithDocker.sh
```
and is also used by travis, so travis also tests the changes here.
> chore(thrift): build thrift with `--without-java` flag

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360AuthenticationProvider.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ProjectTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ReleaseTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/AttachmentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java
This PR adds the possibility to use the rest auth server using the screen name (or ldap name) instead of the email address. This is necessary e.g. if someone configured SW360 to use the screen name as login.
To test that one could use an existing instance, change the login to "login via screen name"  and try to use rest-auth. Instead of the email address one then needs to pass the screen name in the request.
> fix(auth): fix screen name auth problem

- backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasink/VulnerabilityConnector.java
- backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/VulnerabilityHandler.java
- backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityDatabaseHandler.java
* fixed the storage db of the cve search which stored vuls and their relations in the standard db while the thrift service tried to read them from the vm db
fixes eclipse/sw360/#401
Testing: On a clean installation one should be able to schedule the cve search (Admin -> Schedule) and after a successful run there should be vulnerabilities in the application that are visible at the releases or on the Vulnerabilities page.
The bad thing: I guess the start time for the scheduler is only changeable via code. So maybe one want to change org.eclipse.sw360.schedule.timer.Scheduler.getNextSyncDate(int, int) before deploying the branch (careful: the time entered is GMT).
> fix(vul-scheduler): fixed an issue where vulnerabilities were stored in the wrong db

- scripts/install-thrift.sh
the script was missing the dependency `build-essential` which provides `make`
> fix(scripts): add missing dependency to scripts/install-thrift.sh

- backend/svc/pom.xml
- frontend/sw360-portlet/pom.xml
- frontend/sw360-portlet/src/main/webapp/META-INF/context.xml
This commit is an addition to the quick deploy PR sw360/sw360-chores#55
In order to prevent the Tomcat from creating a temp directory for the webapp
from which the webapp is service, the following context settings are
necessary:
- antiJARLocking=false
- antiResourceLocking=false
If the webapp provides no context file, liferay generates such a file with
both settings set to true.
This commit introduces an own context file which is filled based on properties.
These propterties are "true" by default but can be set to "false" by using
the maven profile "develop" on building.
> chores(quick-deploy): add quick deploy for portlet

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/attachmentUsages.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/attachmentUsagesRows.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/vulnerabilities.jspf
**Summary:**
Restrict users, without any WRITE access from modifying the attachment usage.
**Changes:**
"Save Usages" button is hidden and all the checkboxes are disabled for the users, without any WRITE access.
Closes: #426 
> feat(attachment-usage): Restrict modification of the attachment usage

- frontend/sw360-portlet/src/main/webapp/html/components/edit.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/detailOverview.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/detailOverview.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/detailOverview.jspf
Show selected Project/Component Name in Browser Tab
Added project or component name to page title.Now on selecting project or component the page title for Project will be "(ProjectName) : Projects - Liferay " and similarly on selecting of component the title will be ""(ComponentName) : Components - Liferay"
1. Go to Projects tab and click on any of the project from the list.
2. Go to Components tab and select any of the existing component.
1.Selected Project or Component  name should be coming on page title.
Closes #140
> feat(UI:PageTitle): Show selected Project/Component Name in Browser Tab

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandlerTest.java
- backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- libraries/lib-datahandler/src/main/thrift/sw360.thrift
* added detection of duplicates during edit of objects
* therefor added new status "duplicate" in thrift layer for update methods
closes eclipse/sw360/#98
During testing it might be interesting which fields lost during the round trip. In generel, edit of projects, components and releases should be tested.
> feat(duplicates): added support to prevent duplicate projects/components/releases

- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/clearingStatus.jspf
Added edit button to edit release during project details view and edit. Earlier user was only able to add or delete release , now user will be able to edit the release as well from project details. 
1. Click on Projects tab and edit project.
2. Go to Linked releases and projects and  click on edit button for the linked releases to edit the release. 
closes #372
> feat(UI-Project):Jump to edit release from ProjectDetails

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
Signed-off-by: Nutan Das <nutan.das@siemens.com>
Vendor Id null check was missing for new release .As exception handling was not proper so there was a abnormal termination from code flow which was causing the issue. 
1.Create a new release with any of the existing version name.
1.It should give a error message for duplicate release and it should display the same new release window.
Closes  : #468
> fix(UI-Release): UI error on duplicate release creation

- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
Self links should be forbidden at all
Added logic to remove the release from the LinkedReleases list ,if the parent and child release Id is same.
1. From the "Components" tab select any of the listed component.
2. Goto Release Overview and click on  Release Revision of any of the listed release.
3. Goto to Linked Releases tab of the selected Release and try to expand the Linked Releases Hierarchy and observe the structure. 
Self link should  not be present under same Release. 
Closes: #410
> fix(ReleaseLink): Remove self link from LinkedReleases hierarchy

- frontend/sw360-portlet/src/main/webapp/js/utils/includes/searchAndSelectIds.js
* added functionality to multi item search dialog (user search and
license search) to keep chosen items between different searches
closes eclipse/sw360#134
> feat(search-dialog): improved multi item search dialog

- backend/src/src-licenseinfo/pom.xml
- backend/src/src-licenses/pom.xml
- frontend/sw360-portlet/src/main/webapp/html/admin/licenseAdmin/view.jsp
Due to the changes in https://github.com/eclipse/sw360/commit/8fee82570cc54018540dc1e53457cfa08216c8b3#diff-522eb230e2bc520bfed39d0abf54dd21 (for https://github.com/eclipse/sw360/pull/459) the **import all SPDX licenses** feature is broken:
This PR adds a replacement for the excluded dependency.
The added dependency `org.apache.commons:commons-lang3:3.8.1` is already in the eclipse system, and we can piggyback of `[CQ18249] Apache commons-lang3 3.8.1` (see: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19043)
> fix(license-import): add missing dependency

- frontend/sw360-portlet/src/main/webapp/html/homepage/mytasksubmissions/view.jsp
**Summary:**
User is not able to delete the submitted task under "My Task Submission" in homepage.
**Changes:**
Fixed the jQuery-confirm loading issue by adding require js support in the jsp.
**Steps to Test:**
Go to Home screen -> "My Task Submissions" -> Try to delete any existing task.
**Expected result:**
The confirm dialog box should appear, after clicking on the "confirm", the task should be removed from the list.
closes: #481
> fix(UI): Deleting submitted task under My Task Submission section.

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/TextGenerator.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGenerator.java
- backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGeneratorTest.java
- backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGeneratorTest.java
- Development Detail table
- Additional Requirement table
Signed-off-by: Johannes Amorosa <johannes.amorosa@endocode.com>
>  chore(licenseinfo): Reporting Improvements Part 2 #433 

- backend/src-common/src/main/java/org/eclipse/sw360/components/summary/ComponentSummary.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/VendorRepository.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayVendorEdit.java
- frontend/sw360-portlet/src/main/webapp/WEB-INF/customTags.tld
- frontend/sw360-portlet/src/main/webapp/html/admin/bulkReleaseEdit/view.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/editBasicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/summary.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/editReleaseInformation.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/mergeComponent.jsp
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
- libraries/lib-datahandler/src/main/thrift/components.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
* added default vendor handling
* default vendor can be added and updated in component details edit mode
* default vendor can be seen in component details view
* default vendor id will be handled in moderation requests
* default vendor is part of component merge
* default vendor is part of REST
* default vendor is part of vendors list in component list view
* default vendor is added to new release edit view
* default vendor is NOT yet part of import/export functionalities
closes eclipse/sw360#267
@mcjaeger what about import/export functionalities? Should we add the new fields there as well? If yes, in which parts exactly?
> feat(default vendor): added possibility to save a default vendor for components

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/AttachmentPortletUtils.java
- libraries/commonIO/src/main/java/org/eclipse/sw360/commonIO/AttachmentFrontendUtils.java
Currently multiple attachment upload is supported, but due to some concurrency fault, sometimes the upload gets stalled in between. 
**Changes:**
I have fixed this issue by applying synchronization mechanism. Now, we could select multiple attachments and upload the same.
**Testing Steps:**
1) Select/drag and drop multiple attachments and upload the same.
2) Upload attachments from multiple browsers at the same time(to simulate the multi-threaded environment).
closes: #249 
> fix(attachment): Multiple attachment upload stall issue

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
- backend/src/src-users/src/main/java/org/eclipse/sw360/users/UserHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/UserPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/UserPortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/UserUtils.java
This tries to fix #477, but it fails to fix existing instances. The problem is that in existing instances there is already a user with multiple email addresses. There is no direct way to differentiate that user back into individual users.
This might also collide with other approaches, where the `openId` of a liferay user is actually used, for storing the external ID.
> fix(users): write screenname into externalID field

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyComponentsPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyProjectsPortlet.java
If a user changes the e-mail, the view of the projects (and components) within the Home page is not showing the projects and components referring to the old e-mail.
In home page earlier the search was based on  user email because of which when we change the email application is not able to find any result for that.As per latest changes projects and components are searched based on user id.
1.Login to the application and check the projects and components list on the home page.
2.Now go to "My Account" and change the email address for the logged in user and save the changes.
3.Now go back to home page and refresh the page.
1.It should show the same list of  all projects and components associated to the user. 
Closes #302
> fix(ui): MyComponents and MyProjects does not list in Home page if email is changed

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/AttachmentConnector.java
- libraries/lib-datahandler/src/main/thrift/sw360.thrift
Restrict users from uploading multiple attachments with same file name.
If user tries to upload multiple attachments with same file name , then during upload it will restrict the user from uploading  with warning message "Attachment with <i> filename</i> already exist"
1.Try to upload an attachment with same file name and extension , listed on the attachment list.
It should give an warning message "Attachment with  <i> filename</i> already exist"
closes #417
> fix(Attachments-UI):Restrict from duplicate attachment upload

- frontend/sw360-portlet/src/main/webapp/html/homepage/mytasksubmissions/view.jsp
After removing a task from Home page, the task is back in the list when navigating back.
1. In home page delete any of the task from "My Task Submissions".
2.Now click on any of the task from the "My Task Submissions" list.
3.It will open the task and then click on browser back button to go back to home page.
1."My Task Submissions" list in home page should display the updated list of tasks.
Closes: #121
> fix(ui): After removing a task from Home page, the task is back in the list when navigating back

- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExcelExporter.java
**Summary:**
If the cell value exceeds 32,767 characters then application should not display error page
Instead it should put value as "Export to spread sheet"
Added check for maximum cell limit during writing the values into row. 
**Steps to reproduce:**
1.Create a project and and link around 460 releases to the project so that when user user select export to spreadsheet for the project then "releases with usage" column will have more then 32767 characters.
2.Now try to export all projects from projects tab by selecting "Export to spread sheet".
**Actual Result:**
If the cell value exceeds 32767 (max allowed) characters then when just display an error message inside #cell has exceeded max number of characters.
Closes: #519
> fix:Project spreadsheet export failure due to maximum cell length reached

- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExcelExporter.java
**Summary:** Added indentation fix and message text 
During spread sheet generation If the cell content exceeds 32,767 characters then it should display a message "#cell has exceeded max number of characters".
> fix(report): fix indentation and message text

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentDatabaseHandler.java
- backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/AttachmentDatabaseHandlerTest.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
- frontend/sw360-portlet/src/main/webapp/css/sw360.css
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/attachmentSelectTable.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/licenseInfo.jsp
- libraries/lib-datahandler/src/main/thrift/attachments.thrift
* changed page behavior: same attachments of same releases are no longer
coupled in the tree if they belong to different subprojects
* license file contains the union of all selected licenses (so if the
same license is not selected on one leaf but is selected on another, it
will be part of the license file)
* added new field in LicenseInfoUsage to store the project path to this
attachment
* added button to take over the license selection of a subproject in a
fire and forget manner
* added loading spinner row
* source code bundle generation should still be the same
closes eclipse/sw360#483
The basic idea of the new license info file generation page is, that licenses are identified by the pattern …
> feat(subproject licenses): added possibility to take over license selection from subproject

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyComponentsPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyProjectsPortlet.java
Reverts eclipse/sw360#501 because it turned out not to be compatible with productive deployments.
> Revert "fix(ui): MyComponents and MyProjects does not list in Home page if email is changed"

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/AttachmentPortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/links/DisplayDownloadAttachmentBundle.java
- libraries/commonIO/src/main/java/org/eclipse/sw360/commonIO/AttachmentFrontendUtils.java
**Summary:**
During attachment bundle download , if there is only one file to download then on click of download button it directly download the file without zip container and the tooltip for the same shows "Download AttachmentBundle.zip". 
**Steps to reproduce:**
1.Open any of the project or component then go to "Attachment" tab.
2.Make sure you have only one attachment to download then click on the download attachment bundle icon to download all the attachments.
**Result:**
1.It should download the attachments into zip container even though there is only one file to download. 
Closes :  #127
> feat(UI-attachment): Create attachment bundle zip container, even for only one attachment

- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/TestRestDocsSpecBase.java
Added logic to add REST API documentation for attachment upload to project,component and release which records a CURL request and response in the documentation.
Please search for the end point with sub heading ""Upload Attachment" under the corresponding section of Projects and Components and Releases
> fix(REST API): Attachmentupload endpoint documentation

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParser.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java
- backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/CombinedCLIParserTest.java
- backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTest.java
- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/licenses/LicensesPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/clearingDetails.jspf
- libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
* added additional infos to existing licenseinfo object (filled only from spdx parsers)
* added portlet methods to get an array of concluded license ids and to use this info as input for a release update
* implemented in a way that can be extended if other information should be handled as well
* added some javascript handling in clearing details tab of releases to offer actions and show results
* added POST-redirect-GET pattern to release update to avoid duplicate release updates when triggering a reload because of the new functionality after coming from edit mode
* improved error message for not found licenses
closes eclipse/sw360#92
> feat(spdx-import): added functionality to view and use spdx information

- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftClients.java
This adds the capability to set a proxy for the thrift client which enables liferay or other clients to reach a thrift service behind a proxy.
> feat(thrift): add http proxy for thrift clients

- frontend/sw360-portlet/src/main/webapp/html/projects/includes/attachmentUsages.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/attachmentUsagesRows.jspf
**Summary:** changes to display 'uploaded By' and 'Project/Release Relation' in Attachment Usages tab under project portlet.
**Steps to test:**
```
- Login to SW360, and open project portal
- Select a Project which is having 'Linked Release / Projects'
- Go to 'Attachment Usages' tab, and expand the Release/Project.
- You should see 'Relation' for each release / project, and 'uploaded by' for each attachment.
- Additional attachment info should be displayed on mouse hover for each attachment table row.
```
closes: #370 
> feat(Projects): display 'uploadedBy' & 'Relation' in Attachment Usages tab

- backend/src-common/src/main/java/org/eclipse/sw360/components/summary/ComponentSummary.java
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/helper/ReleaseHelper.java
**Summary:** Added "Categories" field of component to spreadsheet export of "Project with linked releases".
**Steps to reproduce:**
1. Go to Projects tab and select "Projects with linked releases" from the drop own and click on "Export Spreadsheet".
**Result:**
1.Categories column should be present on the spreadsheet with value as corresponding component categories of the linked release to project.
closes : #530
> feat(spreadsheet): Added component categories field on spreadsheet export of Project with linked releases

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/EmbeddedProject.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
* White listed "homepage" field at component level.
* White listed "enableSvm" and   "enableVulnerabilitiesDIsplay" at project level.
closes #487 , closes #516
> feat(rest): Whitelisting Fields in the REST API Response

- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/administrationEdit.jspf
Issue: Under Project>>Administration, if user click on "Set To default text" of License info header then License info header text will display only till first double quote.
Reason: When html encounters the first double quote then it considers that as end of default text and display only till that point.
Fixed the issue by using the text area value in side java script which is  formatted as per html.
Closes : #559
> fix(Project UI): Fixed "Set To Default Text" feature for project license info header

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
* There were some additional fields exposed through project listing ( `api/projects`) endpoint.  
> fix(rest): Hiding unwanted fields in project listing response in REST

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
- Fetched the attachment usages of the original project.
- Persisted the same by associating the new project(cloned project) id to it.
closes #573 
> feat(attachment-usages): Take over the attachment usages from the original project.

- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ReleaseTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
I have also tried to add a test to upgrade the license list of a release to `ReleaseTest.java`, but for example the following has not worked for me and I do not know how to represent the information correctly in the test case
```diff
diff --git a/rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ReleaseTest.java b/rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ReleaseTest.java
index 7031999c..fcd9a498 100644
--- a/rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ReleaseTest.java
+++ b/rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ReleaseTest.java
@@ -103,6 +103,7 @@ public class ReleaseTest extends TestIntegrationBase {
Map<String, String> …
```
> test(REST): add documentation for Licenses in Releases

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/resources/sw360.properties
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/basicInfo.jspf
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/summary.jspf
- libraries/lib-datahandler/src/main/thrift/projects.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Summary:
Added new field "domain" to project summary
Field domain" will be a dropdown and the values will be fetched from sw360.properties file
Added rest api support for the field.
Added the field to rest api documentation
Steps to test:
-Create new project and look for a field with name "domain" under project summary.
-The field should of type dropdown and the values should be fetched from sw360.properties file.
-User should be able to select and save the field value.
-User should be able to add the field values by create project from rest end point.
-On entering invalid values rest end point should give error response. 
closes : #539
> feat(Projects): Added new field "domain" to project summary

- backend/src-common/src/test/java/org/eclipse/sw360/components/summary/ProjectSummaryTest.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ComponentModerationRequestGenerator.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ProjectModerationRequestGenerator.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ReleaseModerationRequestGenerator.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
- frontend/sw360-portlet/src/main/webapp/html/components/edit.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/editRelease.jsp
- frontend/sw360-portlet/src/main/webapp/html/components/includes/components/summary.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/includes/releases/summaryRelease.jspf
- frontend/sw360-portlet/src/main/webapp/html/components/mergeComponent.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/edit.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/includes/projects/summary.jspf
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/editAdditionalData.jsp
- frontend/sw360-portlet/src/main/webapp/html/utils/includes/editExternalIds.jsp
- frontend/sw360-portlet/src/main/webapp/js/modules/mergeWizard.js
- libraries/lib-datahandler/src/main/thrift/components.thrift
- libraries/lib-datahandler/src/main/thrift/licenses.thrift
- libraries/lib-datahandler/src/main/thrift/projects.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
maps for licenses are currently supported by the backend and rest, but not by the frontend or moderation requests (already true for external IDs).
This is a **partial** fix to https://github.com/eclipse/sw360/issues/554. it allows to store generic data but without typing or configuration possibilities.
TODOs:
> Add additionalData maps to releases, components, projects and licenses 

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/webapp/css/sw360.css
- frontend/sw360-portlet/src/main/webapp/html/projects/detail.jsp
- frontend/sw360-portlet/src/main/webapp/html/projects/view.jsp
- libraries/lib-datahandler/src/main/thrift/sw360.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- Only Admin should be allowed to edit a closed project.
- Added restriction, if the user is not admin and project clearing state is "Closed" then 
user will not be allowed to edit the project.
closes : #567
> fix(Project): Only users with Admin access should be allowed to edit a closed project

- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/Sw360AuthorizationServer.java
- rest/authorization-server/src/main/resources/application.yml
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
- rest/rest-common/src/main/java/org/eclipse/sw360/rest/common/PropertyUtils.java
This commit allows the resource server and authorization server to be
configured via an external file in the following directories:
- /etc/sw360/authorization/
- /etc/sw360/rest/
The configuration files must be named according to the defaults of
Spring Boot ('application.yml', 'application-{profile}.yml').
Of course, standard property files (*.properties) can be used as well.
Closes #614
> chores(configuration): allow external files

- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/basicauth/Sw360LiferayAuthenticationProvider.java
- rest/authorization-server/src/main/resources/application.yml
The liferay rest request returns now a number in qoutes instead of a raw number. We have to strip the quotes first.
Also the default company Id has changed (is this id deterministic?)
based on: https://github.com/eclipse/sw360/pull/616
>  fix(rest): auth server is broken due to liferay api change

- backend/svc/pom.xml
- frontend/sw360-portlet/pom.xml
- pom.xml
- rest/authorization-server/pom.xml
- rest/resource-server/pom.xml
Before this commit, the maven dependency plugin was activated with
the 'deploy' profile for every module, even for the parent pom. Since
there is a configuration to copy some information from the
'build-configuration'-submodule, an initial build with active profile
failed.
This fix moves the configuration of the plugin for the 'deploy'-profile
into a 'pluginManagement'-section. This way it is only activated for
relevant modules.
This also removes the old profile sections.
Closes #621
> chores(build): Fix deploy profile

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/editReleaseInformation.jspf
There were two fields for "Licenses" in edit release page. I have removed one entry to fix the same.
Signed-off-by: Nutan Das <nutan.das@siemens.com>
> fix(EditRelease UI): Removed duplicate field 'Licenses' from edit release

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/AttachmentController.java
Corrected the the download attachment link for project,component  and release.
Steps to reproduce:
1. Try to access attachment info with the attachment id. The request URL should look similar to
http://localhost:8080/resource/api/attachments/5037abe393379e786693b7385400295e4
2. Look for the "sw360:downloadLink" on the response and try to download the attachment with the given link.
3. User should be able to download the attachment successfully.
closes : #465 
Signed-off-by: Nutan Das <nutan.das@siemens.com>
> fix(REST-API): Corrected download link for attachments

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
**Issue Description:** `License Info Header` text and `obligation` text won't get copied when duplicating a `Project` from Project List table.
**Testing Description:** 
- Duplicate the existing project, and see that ( _**add mode**_) `Obligation` text and `License Info Header` text is getting copied from the source project as it is. Clicking on "Set To Default Text" button should set the Obligation / License Info Header text to default.
- Create a new project, and see that (_**add mode**_) `Obligation / License Info Header` text field are populated with default text.
closes: #631 
Signed-off-by: Abdul Kapti abdul.mannankapti@siemens.com
> Fix(Project UI): Fixed Lic Info Header & Obligation when duplicating Project

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Steps to reproduce:
- Try to make a GET request for component or project with the user details different then the user who created the component or project.
- Created by field should display the details of user who created the resource.
Closes: #612 
Signed-off-by: Nutan Das <nutan.das@siemens.com>
> fix(Rest-API): Corrected 'createdBy' field value for Project and Component

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
*   When user save the attachment usage  then project path was not getting saved in DB because of which license selection for the selected attachment was not appearing on download license info tab.
*  Now saving the project path, also during attachment usage save.
Closes: #643
> fix(DownloadLicenseInfo): Corrected license selection based on attachment selection on attachmentusage

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
- backend/src/src-licenseinfo/src/main/resources/textLicenseInfoFile.vm
- backend/src/src-licenseinfo/src/main/resources/xhtmlLicenseInfoFile.vm
Formatted the order of items in disclosure documents:
Ordering for each components:
* acknowledgements + license conditions
* Listing of licenses:
* in alphabetical order
* Added with a counting/running number of corresponding license text.
* Each line represents a link to the corresponding license texts
* multiple recurrent identical licenses shall be listed only once !
* Copyrights
* Added a hyperlink to the start of the start of the referring section
> feat(License Disclosure): Change order of listed items in disclosure documents

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
The field 'owner country' was not merged during component merge.
Closes: #627
> fix(merge): Some fields were not merged

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- frontend/liferay-theme/src/main/webapp/css/portlet/_components.scss
- frontend/sw360-portlet/src/main/resources/META-INF/resources/css/portlets/components/_merge.scss
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeComponent.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/mergeWizard.js
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/sw360Wizard.js
Before this commit, one of the owner get lost during merge. Therefore one of
the owner couldn't edit the component anymore.
This commit adds functionality to automatically add the not selected owner
to the list of moderators.
Fixes #199
> chores(merge): Retain owner as moderator

- frontend/liferay-theme/src/main/webapp/css/sw360/components/_table.scss
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/databaseSanitation/duplicatesAjax.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/clearingStatus.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/vulnerabilities.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeComponent.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/ecc/view.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailRisks.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/eccStatus.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/vulnerabilities.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/usingProjectsTable.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/vulnerabilities/view.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/bridges/datatables.js
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/datatables-renderer.js
This commits adds an option to the generic create-method for datatables as
well as fixes the print button on some pages.
* Filter Box
There is no one more parameter to the create-method of the bridges/datatables
module. Giving true as last parameter will add a filter box at the top right
for the datatable.
This option has been set on many pages now, except where explicit quick filters
already exist.
* Fix print button
When adding a print button, the additional option 'orthogonal' has been set.
With this option in place, all render methods are called with type set to
'print' when printing. This way renderer can omit html tags or links when
rendering for print view. Renderes has been adapted as necessary.
Closes #657
> feature(table-filter): add filter box, fix print

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/clearingDetails.jspf
The below issue is fixed:
For **`XML CLI`** files, Clicking on **`Show License Info`** button in _**Reelase -> Clearing Details**_ tab always gives error message: `Cannot load license information: parsererror (200).`
Attached screenshot for reference:
**BEFORE:**
**STEP 1:**
**STEP 2:**
**AFTER:**
closes #636 
> fix(Component UI): Fixed SPDX License import functionality for XML CLI files

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
- backend/src/src-licenseinfo/src/main/resources/textLicenseInfoFile.vm
- backend/src/src-licenseinfo/src/main/resources/xhtmlLicenseInfoFile.vm
This change will add ordering and formatting for all three types (docx,html,txt) of license disclosure document. 
- Copyrights to be displayed for each component.
- Running number for each license name of corresponding license text on the license listing.
- Provided license name and link to the corresponding license text.
> fix(LicenseDisclosureDocument): Ordering and formating license disclosure document.

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
This commit fixes a view name that is used during editing vendors.
Closes #672
> fix(vendor): fix view name used when editing vendors

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
Before this commit the aggreated fields of a componente were not
updated on save of the component. This commits ensures that the
aggregated fields are up-to-date even after update.
Closes #682
> fix(components): Recompute aggrated fields on save

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
1. From rest end point when user was requesting `get all components`  based on component type, it was failing with 500 error.
2. Corrected the same by adding necessary checks.
> fix(Rest-Component): Corrected components by type rest end point

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentUsageRepository.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectVulnerabilityRatingRepository.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
- backend/src/src-attachments/src/main/java/org/eclipse/sw360/attachments/AttachmentHandler.java
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/VulnerabilityHandler.java
- backend/src/src-vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityDatabaseHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayBoolean.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_merge.scss
- frontend/sw360-portlet/src/main/resources/META-INF/resources/css/main.scss
- frontend/sw360-portlet/src/main/resources/META-INF/resources/css/portlets/admin/_buttons.scss
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/detailRelease.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/clearingStatus.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/detailOverview.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/vulnerabilities.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/clearingDetails.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/detailOverview.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/editReleaseClearingInformation.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeComponent.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeRelease.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/mergeWizard.js
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/sw360Wizard.js
- libraries/lib-datahandler/src/main/thrift/attachments.thrift
- libraries/lib-datahandler/src/main/thrift/components.thrift
- libraries/lib-datahandler/src/main/thrift/vulnerabilities.thrift
This commit adds a merge wizard for releases. It is build upon the merge framework therefore
it works the same as the component and the vendor merge wizard: click merge on the target, select
a source and takeover the needed fields.
Merging releases is only possible inside a single component. In addition both releases need to have
at least on pair of equal source attachemnts nor no source attachments at all.
The fossology status is not merges since it will be superseeded by external tool requests in the
near future.
> feature(release): add release merge wizard

- backend/src-common/src/main/java/org/eclipse/sw360/common/utils/BackendUtils.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/mail/MailUtil.java
- backend/src-common/src/main/resources/sw360.properties
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
- backend/src/src-projects/src/test/java/org/eclipse/sw360/projects/ProjectHandlerTest.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/editRelease.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/editReleaseInformation.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesAjax.jsp
Summary: Changes of the Project/Release Mainline State is only allowed for the role Clearing Admin.
**Steps to test:**
**_Scenario 1:_**
```
1. Login with USER role.
2. Go to Projects tab and edit a Project which is having linked releases.
3. Select "Linked Releases And Projects" on left.
4. Verify that "Project Mainline State" drop-down is disabled. 
5. Click on "click to add Release" -> search for a release and add it to the "Linked Releases".
6. Verify that "Project Mainline State" drop-down is disabled. 
```
**Result:**
`1. User should not be able to change the "Project Mainline State" drop-down. in "Linked release and projects" tab.`
**_Scenario 2:_**
```
1. Login with USER role.
2. Go to Components tab and edit a component which is having release ("Release Overview" tab).
3. Select …
```
> feat(Projects): enabled Project/Release mainline state change only for clearing admins

- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- backend/src/src-components/src/test/java/org/eclipse/sw360/components/ComponentHandlerTest.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/editBasicInfo.jspf
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
1. Added a fix to make the component type field as mandatory. 
2. This fix is  both for SW360 UI and Rest end point. 
3. From rest end point user might not get the exact error response with field name,  if component type input is left  blank.  Rest end point field validation  will be taken care as part of issue fix for  
#584 .
closes: #676
> fix(Componnet): ComponentType field should be mandatory

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
* While creating project through rest endpoint, some of the fields( like contributors, moderators, lead architect) were not able to de-serialized. added support to de-serialize the same. 
* Exposed leadArchitect, moderators, contributotrs as hypermedia resource.
> feat(rest): Added support to upload role category fields while creating project

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
Edit Project , under administration tab "set to default" for obligation not working properly if default Obligation message contains quotes
Closes : #582 
> fix(Project/Admin): Set to default text feature is not working correctly for Obligation

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
While uploading attachments through REST API , createdComment field was not updating. Changes done to resolve the issue.
closes: #646 
> fix(REST): added support for createdComment field for uploadAttachements

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorDatabaseHandler.java
- backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/VendorPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/vendors/mergeVendor.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/vendors/view.jsp
- libraries/lib-datahandler/src/main/thrift/components.thrift
- libraries/lib-datahandler/src/main/thrift/vendors.thrift
This commits adds an merge wizard for vendors. In the vendor overview,
one can click on the merge action, select a source vendor and then
merge the fields.
All dependening components and releases are adapted automatically.
Closes #629
> feature(merge): add wizard for merging vendors

- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
* Previously the moderation requests were going to the clearing admins of the same group. These changes send the moderation request to all clearing admins.
> feat(moderation): Moderation requests to all clearing admin irrespective of their BU

- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Created three rest end points like
* http://sw360.com/resource/api/projects/usedBy/b7b07cadabb084a68c746b0c0705581d
* http://sw360.com/resource/api/components/usedBy/b7b07cadabb084a68c746b0c07007b99
* http://sw360.com/resource/api/releases/usedBy/ac8a53df29af6391bd76f61aea001336
which will display a short detail of the project/component/release usage summary along with the hyperlink to navigate to the resource . 
closes : #704
> feat(Rest): New end points for project/component/release usage summary

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
- frontend/sw360-portlet/src/main/resources/sw360.properties
**Summary:** removed `Unknown` option from the Project Clearing Team drop down.
**Steps to test:**
```
- Login to SW360, and open project portal
- Edit any Project listed under Project tab.
- Go to 'Administration' tab, and check the "Clearing Team" drop down.
- You should not see 'Unknown' option in drop down.
```
closes: #563 
> Fix(Project UI): Removed 'Unknown' from Project Clearing Team dropdown

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/edit.jsp
Fixed incorrect release edit link in component edit page
closes: #703 
> fix(component): incorrect release edit link in component edit page

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
Check that `extIdMap` is not null, before accessing it.
closes #715
Signed-off-by: Kalle Soranko <ksoranko@verifa.io>
> fix(LicenseInfo): NPE in ProjectPortlet.prepareLicenseInfo and downloadLicenseInfo

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/Sw360LicenseInfoService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
* License information generation from rest endpoint based on the persisted attachment usages.
Closes: #686
> fix(rest): License information generation based on attachment usages from rest

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
When requesting a single release, immediate child releases are embedded
When requesting all releases (transitive) for a project, entire release hierarchy is included
closes: #515 
> feat(REST): linked release hierarchy is included in the response

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/detail.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/linkedObligations.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsByReleases.jspf
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
fixed NPE in  SW360Utils.getApprovedClxAttachmentForRelease.
The issue was caused due to absence of `createdOn` field for old attachments.
closes #719
> fix(projectUI): NPE in SW360Utils.getApprovedClxAttachmentForRelease

- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/businessrules/ReleaseClearingStateSummaryComputer.java
Fix NullPointerException which is thrown in main Projects view by clearingStateSummaryComputer.
closes #713 
Signed-off-by: Kalle Soranko <ksoranko@verifa.io>
> fix(businessrules): NPE in clearingStateSummaryComputer

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/todos/view.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/ajax/linkedProjectsAjax.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesAjax.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editAdditionalData.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editExternalIds.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/mapEdit.jspf
* Fixed the tool tip by converting the title attribute to title tag and added the missing tool tip for clearing state and project active state in the project listing page.
> fix(ui): Added missing tooltip

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Added Rest API to get attachmentUsages of a Project.
> feat(rest): get attachmentUsages for a project

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/AbstractCLIParser.java
- backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandlerTest.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/detail.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/editObligations.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/linkedObligations.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsByReleases.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/viewByObligations.jspf
- frontend/sw360-portlet/src/main/resources/sw360.properties
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
- libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
- libraries/lib-datahandler/src/main/thrift/projects.thrift
Changes included:
- Added config key `project.obligations.enabled` to _enable/disable_ the project obligations feature in sw360.properties. By default the feature is **disabled**.
- Delete the project obligations associated with individual `linked release`, if:
1. Previously accepted CLI.xml file is **rejected** _or_ **deleted**.
2. Accepted more than **ONE**  CLI.xml file at later point of time.
- To display the message if there is any changes in previously accepted CLI.xml file of `linked release`.
- Commented the code for `Action` field of obligation (to hide it in UI), until action select options are provided.
closes #726 
> fix(ProjectUI): Obligation view for changes in linked release attachment

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
* While getting component or project using id, it's giving an 500 error response, if the user does not exist in the system anymore and some refractoring.
> fix(rest): Error getting component/project with unknown creator

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRelationsUsageRepository.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
- backend/src/src-licenseinfo/src/main/resources/textLicenseInfoFile.vm
- backend/src/src-licenseinfo/src/main/resources/xhtmlLicenseInfoFile.vm
- backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentSelectTable.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/licenseInfo.jsp
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftUtils.java
- libraries/lib-datahandler/src/main/thrift/projects.thrift
* User can chooses to exclude the releases with specific project release relationship while generating license disclosure document.
* Added warning message to the generated document, if no selection has been chosen.
> feat(licenseinfo): Added filter to exclude releases based on selected relationship

- backend/src/src-fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/FossologyAwarePortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/fossologyClearing.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/includes/fossologyClearing.js
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
- libraries/lib-datahandler/src/main/thrift/fossology.thrift
* Added an extra button to pull the report from from fossology, in case uploading and scanning of the report already done to prevent redundant upload and scanning.
* Moved the `auto-refresh` section to the left and added hyperlink to view fossology job for the respective source file.
> feat(fossology-pull-report): Pull already generated report from the fossology

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/signup/SignupPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/welcome/WelcomePortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/signup/success.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/signup/view.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/welcome/view.jsp
- frontend/sw360-portlet/src/main/resources/welcomePageGuideline.html
Description: Display configurable content for guidelines on welcome page
To configure guidelines on welcome page, 
- set `custom.welcome.page.guideline = true` in `sw360.properties`
- put the content for guidelines in `welcomePageGuideline.html` 
> feat(WelcomePageUI): display configurable content for guidelines on welcome page

- scripts/utilities/001_update_project_field_value.py
- scripts/utilities/README.md
Migration script to migrate a project field to new value.
Following variables needs to be updated based on requirement
`fieldName` = "field_to_be_migrated"
`oldValue` = "old_value"
`newValue` = "new_value"
For updating ClearingTeam Field in Project - `clearing.teams` property in `sw360.properties` file should be updated accordingly
> feat(ProjectMigration): script to migrate a project field to new value

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Assert.java
- libraries/lib-datahandler/src/main/thrift/projects.thrift
- libraries/lib-datahandler/src/main/thrift/sw360.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
If user doesn't have access to a Project or its LinkedProject or some of project dependencies are missing . It gives generic Error.
Show proper error message ,when loading of project fails due to access denied or dependencies not found.
closes: #746 , #240 
> fix(ProjectUI): Show proper error msg ,when loading of project fails due to access or dependency not found.

- README.md
- scripts/startCouchdbForTests.sh
This is a super simple PR which just adds a simple script which is useful for lightweight testing
> test: add script to start temporary couchdb with docker

- .travis.yml
- pom.xml
Using the command:
```
git rev-list  `git rev-list --tags --no-walk --max-count=1`..HEAD --count
```
which returns the number of commits since last tag on this branch, we would like to increase the patch level version which should be increased automatically.
Making it a PR beause we would like to see travis working on it.
> Adding rolling versions based on commit count

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- libraries/lib-datahandler/src/main/thrift/components.thrift
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Added a new request parameter `&patch=<true|false>` in-order to patch releases to existing releases in a Project.
> feat(REST): Patch Releases to Project

- backend/src/src-fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
- Issue Fixed: Reload Report(FOSSology) from UI generates new report but tries to attach old report to Release.
> fix(ReleaseUI): fixed reload report in FOSSology Process

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
* Fixed the adding component and release from ui
* Prevent adding empty release reference in the `/projects/{id}/releases` endpoint while linking releases to the project.
> fix(component/release): Add component/release error.

- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/TestRestDocsSpecBase.java
- Updated Upload Attachment documentation for Project , Component, Release.
- Added description for missing parameters attachmentType, checkStatus, createdComment and updated description of attachmentContentId.
> fix(REST): Updated upload attachment documentation

- rest/resource-server/src/docs/asciidoc/attachments.adoc
- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/AttachmentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/TestHelper.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/AttachmentTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ReleaseTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/AttachmentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
* Get attachments by sha1 via `/attachments?sha1=XXXX`
* Listing releases by attachment sha1 via `/releases?sha1=XXXX`
> feat(rest): Attachement sha1 improvement

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
* components listing limited to 200 entries both in UI and spreadsheet export.
closes #791 
> fix(components): components listing limited to 200 entries

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src/src-components/src/test/java/org/eclipse/sw360/components/ComponentHandlerTest.java
- backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/editBasicInfo.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/editReleaseInformation.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/basicInfo.jspf
- libraries/lib-datahandler/src/main/thrift/sw360.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Remove Trailing and leading whitespace for all fields in component ,release and project during add or update through UI or REST
Validation for fields which should not contain only white space while creating or updating through UI or REST
- Name field for Project
- Name and Category field for Component
- Name and Version field for Release
> fix(UI/REST): Remove Trailing and leading whitespace for all fields in component, release and project

- CHANGELOG.md
- README.md
- pom.xml
This is the PR for making the release 8.1-M1. Please see the changelog for details on the changes.
a number of tests was done:
* creation of releases
* creation of projects
* linking projects with releases
* making another hierarchical project
* generation of various readme files (html, word, with hierachy and not)
* adding vendor
* opening views
* exporting spreadsheets
* creating moderation request
* accepting moderation request
* creating clearing request
* accepting clearing request
* editing components and releases
> chore(release): making files for 8.1

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editAttachments.jspf
> * #805, fixed it using **jQuery** to change the order of `select options` as mentioned in issue.
> * No changes in dependencies.
Issue: #805 
> * Check the order is as mentioned in issue, and newly added attachments are being saved as **type** `source`.
> * No additional tests implemented.
Must:
> feat(UI): Reorder attachment types dropdown

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
* Fixed the incorrect element id in the jsp page.
> * Which issue is this pull request belonging to and how is it solving it? (*#https://github.com/eclipse/sw360/issues/841*)
Issue: 
Go to projects listing page -> click on "Export Spreadsheet" -> Verify both for …
> fix(spreadsheet-export): Project spreadsheet export returns blank spreadsheet

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
> * Which issue is this pull request belonging to and how is it solving it? (*#844*)
> Create or Update Release without providing clearing state info in request body. Default value should be saved instead of null
> No additional tests were implemented
Must:
> fix(REST): Added default value(NEW_CLEARING) for Clearing status while create and update Release

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/AbstractCLIParser.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsages.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligations.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
* `Edit` icon will be showed for all the users with role `Clearing Expert` and above in `Open / Closed` Clearing Request tab. 
* Text truncate (`ellipsis`) is now working for `comment` row in `Project Obligation` table.
* Fixed `Expand` icon not visible for component name under `Obligations` tab in `Release view`.
* Fixed `js` error on `attachmentUsage.jspf` page.
Issue: #853 
* Login with user role `Clearing expert` or above and you should be able to see edit icons for clearing request in `Open / Closed` …
> fix(UI): Clearing Request and Obligations fixes

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/mail/MailUtil.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
* Enabled `Email Notification preference` for `Requesting User` in `Clearing request`.
* Email notifications for `Clearing Team` will always get triggered.
Issue: #866
* Requesting User should receive an email, if email subscription is enabled under Clearing tab.
* Email will get triggered upon: Creation of CR, updating a CR, adding comment in CR, changes in Linked release for a project linked with CR.
Must:
Signed-off-by: Abdul Kapti …
> feat(PreferenceUI): Enabled Email notification for Requesting User in CR

- scripts/migrations/017_update_empty_release_clearing_state_to_default_value.py
- scripts/migrations/README.md
> Migration script to update releases with empty clearingState to default value - NEW_CLEARING.
> * Which issue is this pull request belonging to and how is it solving it? (*#844*)
> Execute the script with `DRY_RUN = True` to get the list of releases which needs to be updated.
> Execute the script with `DRY_RUN = False` to update the releases 
Must:
> fix(MigrationScript): Update releases with empty clearingState to default value - NEW_CLEARING

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingRequest.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/validation.js
* Enable `Create Clearing Request` button under `Clearing Status` tab of project details view.
Issue: #875 
* User should be able to `create/view` the `Clearing Request` from `Clearing Status` tab in project details page. (as shown in below screenshot)
* Also, test that existing functionality of creating the `Clearing Request` from `project list page` …
> feat(ProjectUI):Add Clearing Request button in project Details page

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
* Witelisted project `state` and `phaseOutSince` and added respective documentation.
Issue: 
#891 
* Get  request on `api/projects/{id}` endpoint should include `state` and `phaseOutSince` field in response.
Must:
> feat(rest): Whitelisting project 'state' and 'phaseOutSince' field

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/entitlement/ProjectModerator.java
> Fixed isWriteActionAllowedOnProject check for project update
> * Fixed incorrect value for Visibility in Edit Project view which has existing moderation request
> * Which issue is this pull request belonging to and how is it solving it? (*#909*)
> - Steps mentioned in issue #909 
> - To test - `incorrect value for Visibility in Edit Project view which has existing moderation request`
Create a project with visibility as `Everyone` . Create moderation request without making any changes to visiblity.
On Editing the project. The Project with moderation request changes should load , and visibility should be correct `Everyone`.
Must:
Signed-off-by: Jaideep …
> fix(ProjectModeration): Fixed isWriteActionAllowedOnProject check for project update

- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/ThriftAttachmentServiceProvider.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/ThriftServiceProvider.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/TestHelper.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentServiceTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ReleaseTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Fixes #897  
This PR adds the ability to delete attachments from components and releases.
The functionality is implemented by the controllers for components and releases with a helper function for checking whether an attachment can be deleted in the Sw360AttachmentService. (According to discussions in the SW360 tech call, attachments must not be deleted when they are used by a project; this is checked by evaluating the attachment usage relations.)
To test the new method of the attachment service, I added a unit test for the service layer. In order to allow injecting mock thrift services, a new service provider interface was introduced, which is basically a factory for thrift services. The factory can be injected by Spring. (As thrift client services are not thread-safe, new instances must …
> Oheger bosch/feat/attachments delete

- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ClearingRequestRepository.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
* Whitelisted `clearingRequestId` field in REST API response for project.
* Added check for `CR Id` while updating/adding a project.
* Did you add or update any new dependencies that are required for your change? **No**
Issue: #918 
* Getting project details via REST endpoint (`GET` request `api/projects/<projectId>` and …
> feat(REST): Whitelisting field in REST API response

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentSearchHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
- libraries/lib-datahandler/src/main/thrift/sw360.thrift
* Added two new filters in Advanced Search for Components.
* Filter by `Created By (Email)` and `Creation Date` of `Component`.
Issue: #902 
* User should be able to search the components based on two new filters `Created By (Email)` and `Creation Date` in Component list page.
* `Created On` filter should have 4 options 
1. _=_   --> where component creation date is equal to user search date.
1. _<=_   --> where component creation date is less than or equal to …
> feat(ComponentUI): Added new filters in Advance search

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsages.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsagesRows.jspf
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
* Added `Expand All` and `Collapse All` button in `AttachmentUsageTable`. 
* `Expand All` and `Collapse All` button will expand `Directly Linked Releases and Projects` only. (and `sub-projects` if it is previously loaded).
* Added `Search` box in `AttachmentUsageTable` top right corner.
* `Search` will work only for `Directly Linked Releases and Projects` based on `Name` column.
* Fixed empty lines between `Status` and `CheckedBy` in `attachmanetUsage` …
> feat(ProjectUI):Added Expand/Collapse All and Search in AttachmentUsageTable

- build-configuration/resources/couchdb.properties
- build-configuration/test-resources/couchdb.properties
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/DatabaseSettings.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
> Support CouchDb Lucene 2.1.0 with CouchDb 2.1.2 and backward compatibility
> * Which issue is this pull request belonging to and how is it solving it? (*#415*)
Issue: 
> Install `CouchDb lucene 2.1.0 - Couch DB 2.1.2` follow [wiki](https://github.com/eclipse/sw360/wiki/Deploy-Natively#deploy-couchdb), 
> Search Functionality should be working fine
> `couchdb.lucene.url = http://localhost:8080/couchdb-lucene` can be added to `couchdb.properties` in `/etc/sw360` to override default value
> **Backward Compatibility**
> Install `CouchDb lucene 1.0.2 - Couch DB 1.6.0` follow [wiki](https://github.com/eclipse/sw360/wiki/Deploy-Natively#deploy-couchdb), Add `_fti` hook to `/etc/couchdb/local.ini` of couchdb …
> chore(couchdb): Support CouchDb Lucene 2.1.0 with CouchDb 2.1.2 and backward compatibility

- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
For adapting  to [Refer to http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/ and add your datatables language]
#948 
Change to Japanese
Datatable language:
https://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json
> …
> fix(Language_ja): change datatables.lang's URL

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedProjectsRows.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesAjax.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleasesClearingStatusRows.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/linkedReleasesEdit.jspf
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseMixInForChangeLog.java
- libraries/lib-datahandler/src/main/thrift/components.thrift
- libraries/lib-datahandler/src/main/thrift/sw360.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/serializer/JsonReleaseRelationSerializer.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
> Added new Field comment, createdOn, createdBy in ProjectReleaseRelation
>   - comment field is available in UI, REST and Excel
>   - createdOn , createdBy is not available in UI but available in REST and Excel.
> * Which issue is this pull request belonging to and how is it solving it? (*#946* , *#225*)
> Create or Update Project with Linked Release, add some comment.
> - Excepted behaviour, comment , createdOn, createdBy fields should be reflected in Excel , REST, ChangeLogs.
> - Note 
>     - Comment is available in UI, Excel and REST. 
>        - In UI, it should be available in `Project Edit Page` and `Clearing Status tab - Tree and List View`.
>     - `createdOn` and `createdBy` is not available in UI …
> feat(ProjectReleaseRelation): Added new Field comment, createdOn, createdBy in ProjectReleaseRelation

- rest/resource-server/pom.xml
> * Fix #973 
> * Did you add or update any new dependencies that are required for your change? 
Yes, excluded logback, slf4j, and spring-boot-starter-logging from resource-server dependency
> Can open https://sw360server/resource/docs/api-guide.html 
Must:
> fix(resource-server): Resolve logback conflict.

- scripts/install-thrift.sh
The script checks whether thrift is currently installed on the local
machine. If so, the thrift version is determined, and this version is
uninstalled.
This is useful when the thrift version is updated. Then the old
version needs to be uninstalled first before the new one can be
installed.
The install-thrift.sh script has been extended to print a message
referring to the new script if an incorrect version is detected.
> chore(script): Added a script to uninstall the current thrift version.

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/resources/sw360.properties
> Allow access to merge/split of component and release based on user role configured in properties
> * Which issue is this pull request belonging to and how is it solving it? (*#977*)
> Set value for `user.role.allowed.to.merge.or.split.component` and validate user with those roles are able to merge or split component.
```
#user.role.allowed.to.merge.or.split.component=ADMIN 
```
Must:
> feat(ui): Allow access to merge/split of component and release based on user role configured in properties

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligations.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/render.js
> Expand/Collapse all columns including comment using single leftmost toggle button for a row
>   * Remove truncate for Obligation Text
>   * Added expand collapse column feature for comments
> * Which issue is this pull request belonging to and how is it solving it? (*#1016*)
> In Project -> Obligation
> - There should be single leftmost toggle button for a row , to expand row content along with comment
> - There should be no truncate for Obligation Text
> - Delete Individual orphaned obligation, should work
Must:
> fix(Obligation): Expand/Collapse all columns including comment using single leftmost toggle button for a row

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/CompareAttachments.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/Moderator.java
> Fixed Moderation Request not opening when associated attachment deleted
> * Which issue is this pull request belonging to and how is it solving it? (*#1026*)
> - Login as user - Create project/component/release moderation request with changes in attachment info.
> - Login as admin - deleted the attachment for which attachmentinfo changes were made.
> - Open and accept Moderation request
Must:
> fix(ModerationRequest): Fixed Moderation Request not opening when associated attachment deleted

- backend/src-common/pom.xml
- backend/src/src-attachments/pom.xml
- backend/src/src-cvesearch/pom.xml
- backend/src/src-fossology/pom.xml
- backend/src/src-health/pom.xml
- backend/src/src-licenseinfo/pom.xml
- backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGeneratorTest.java
- backend/src/src-licenses/pom.xml
- backend/src/src-vulnerabilities/pom.xml
- backend/src/src-wsimport/pom.xml
- backend/utils/pom.xml
- libraries/commonIO/pom.xml
- libraries/exporters/pom.xml
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExcelExporter.java
- libraries/lib-datahandler/pom.xml
- pom.xml
Issue: None - cleanup
This PR aims to simplify the dependency tree for the backend. To obtain a less memory-intensive setup it would be great to package all backend-services together. This requires only one set of dependencies for all backend services to work reliably.
While trying to solve issues with different versions of dependencies, I also noticed that some of the dependencies are used in several places but not referenced from the dependencyManagement section of the parent pom, while others are. This PR …
> Cleanup dependencies for backend services

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/detailOverview.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
Closes: #1044 
> * Did you add or update any new dependencies that are required for your change? - 
No
Issue:  #1044 
Add some user as moderator to a project. Make the project clearing state to closed. Login with user which is added as a moderator and edit the project. All fields …
> feat(projectEdit): Project creators and moderators can edit few fields in a closed project

- backend/src-common/src/main/java/org/eclipse/sw360/components/summary/ReleaseSummary.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/splitComponent.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/mergeWizard.js
> Add tooltip for releases of component with SourceCodeDownloadUrl and BinaryDownloadUrl during split feature
> * Which issue is this pull request belonging to and how is it solving it? (*#1066*)
> Split Component with releases and attachments . Check tooltip of individual releases should show respective `SourceCodeDownloadUrl and BinaryDownloadUrl`
Must:
> feat(SplitComponent): Add tooltip for releases of component with SourceCodeDownloadUrl and BinaryDownloadUrl during split feature

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/summary.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/summaryRelease.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/summary.jspf
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Displayed unique id(DB Ids) of project, component and release in respective the summary page.
> * Which issue is this pull request belonging to and how is it solving it? (*#1076*)
Issue: Closes: #1076 
> How should these changes be tested by the reviewer? - Need to test the UI, if it displayed correctly.
> Have you implemented …
> feat(ui): Display Id in summary page of project, component and release

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
> Create/Update Release with name same as component name
> * Which issue is this pull request belonging to and how is it solving it? (*#1078*)
> Create/Update Release with name different than component name - Expected behavior Release name should remain same as Component Name.
Must:
> fix(rest): Create/Update Release with name same as component name

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentDatabaseHandler.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/LicenseInfoParser.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParser.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java
- backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandlerTest.java
- backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/LicenseInfoParserTest.java
- backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTest.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/LinkedReleasesAndProjectsAwarePortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentSelectTable.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsages.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsagesRows.jspf
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
- frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtilsTest.java
- libraries/lib-datahandler/src/main/thrift/attachments.thrift
- libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/Sw360LicenseInfoService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
> Provided option in attachment usage to include/exclude concluded licenses during LicenseInfo Generation
> * Which issue is this pull request belonging to and how is it solving it? (*#1074*)
> - Change Attachment Usage with different file types from Attachment Tab and From LicenseInfo/Report Generation Page.
- Verify Attachement Usage with proper info are getting created and deleted from DB based on selection. 
> - Old Attachement Usages should function normally - by default conclusions are included.
> - Download LicenseInfo and Report in different format with/without conclusions from UI and Rest
Must:
> feat(ui-rest): Provided option in attachment usage to include/exclude concluded licenses during LicenseInfo Generation

- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseConnector.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/client/persistence/OAuthClientRepository.java
- queryView(query, type) seems to be not supported in CouchDB v3 instead only queryView(query) is supported
- This changes is backward compatible with couchDB v2 as well
> * Which issue is this pull request belonging to and how is it solving it? (*#1084*)
Issue: 
1) Need …
> fix(datahandler): Modified ektorp queryView call to support CouchDB 3

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/JsonGenerator.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/TextGenerator.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGenerator.java
- backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGeneratorTest.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayOutputFormats.java
- frontend/sw360-portlet/src/main/resources/META-INF/customTags.tld
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/licenseInfo.jsp
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
- frontend/sw360-portlet/src/main/resources/sw360.properties
- libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/Sw360LicenseInfoService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
> * Which issue is this pull request belonging to and how is it solving it? (*#1104*)
Added two new properties `org.eclipse.sw360.licensinfo.projectclearing.templatemapping` and `org.eclipse.sw360.licensinfo.projectclearing.templateformat` in `sw360.properties` file where we can place template mapping(such as template:filename) and formats. Accordingly the templates along …
> feat(clearingreport): Feature to select template for Project Clearing Report

- backend/src-common/src/main/java/org/eclipse/sw360/components/summary/ReleaseSummary.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/couchdb/SummaryAwareRepository.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/helper/ProjectHelper.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/DatabaseRepository.java
Sometime if due to some reason, the release reference is present in project document, how ever it is not actually available in DB, then the whole export is not working. In this PR, fixed the null pointer and added a message like "Release not available" in the columns of excel report corresponding to the release fields. …
> fix(excelexport): Projects with linked releases excel export error

- jenkins.eclipse/Dockerfile
- jenkins.eclipse/Jenkinsfile
- jenkins.eclipse/buildContainer.sh
- pom.xml
Add the necessary infrastructure for publishing SW360 artifacts in the Eclipse Maven Repository.
Contains:
- Dockerfile for a build container published to Docker Hub, that is used in the Eclipse environment for the build. The container has to be published manually, a script for doing that and a readme for the container is provided additionally
- Jenkinsfile that is used by the EF Jenkins infrastructure
Issue: #981
Issue is not completely solved, since this pr only adds snapshot releases, real releases and milestones will be added with an additional change.
n/a
Test is to run the SW360 build on our Jenkins server https://ci.eclipse.org/sw360/
Must:
> chore(eclipse): Publish SW360 artifacts in Eclipse infrastructure

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParser.java
- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java
- backend/src/src-licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTest.java
Issue: 　https://github.com/eclipse/sw360/issues/1011
spdx/tools takes a lot of time and resources to parse big rdf file (ie. >15M).
Use javax.xml.parsers and org.w3c.dom.Document for faster rdf reading,
and implement parser to …
> fix(spdx): import large spdx rdf files

- jenkins.eclipse/Jenkinsfile
- pom.xml
fixes #981 
Insert mechanism to run either a commit count or a release build in the Eclipse CI Jenkinsfile. A boolean parameter allows to state that the build is a release build, the default case is a commit count build. The artifacts are deployed to the Eclipse Nexus. Builds are all release builds, so the build break during deployment, if a version is created for a second time. This is the standard behavior for a release build in the maven sense.
Issue: #981  
@mcjaeger 
Run the build and check the artifacts being deployed one Eclipse Nexus
Must:
> chore(eclipse): Enable release and milestone builds

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MyProjectsPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/myprojects/view.jsp
- Added additional filter logic for My Projects based on the project Clearing State.
> * Which issue is this pull request belonging to and how is it solving it? (*#1136*)
Issue: 
- Login to SW360.
- Navigate to My Projects in the Home Page.
- Check the additional filter in …
> feat(MyProjectsUI):Add additional filter to My Projects homepage based on project clearing state.

- .travis.yml
- jenkins.eclipse/Jenkinsfile
- pom.xml
Issue is that the maven flatten module is not able to handle the
double definition of variable patchlevel in the pom correctly.
The generated pom files have the wrong version.
Solution: Put the minor version in the revision variable and
reduce the standard patchlevel content to the idea from the "ci"
profile. Remove the "ci" profile and adapt the travis and jenkins
build files.
Removed the version handling from travis build because it was obsolete.
The whole mechanism was only used to define the name of the build, but not
the version of the mvn call. Since the variable did not make sense, I removed 
the whole mechanism.
Signed-off-by: Lars Geyer-Blaumeiser <lars.geyer-blaumeiser@bosch.io>
Fixes #1144 
@mcjaeger 
Check Travis and Eclipse build log for the right version to be build
Must:
> fix(build): Fix issue with overwriting of patchlevel variable in pom.xml

- backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/AttachmentDatabaseHandlerTest.java
- backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandlerTest.java
- backend/src/src-attachments/src/main/java/org/eclipse/sw360/attachments/AttachmentHandler.java
- backend/src/src-attachments/src/test/java/org/eclipse/sw360/attachments/AttachmentHandlerTest.java
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
- backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentSearchHandlerTest.java
- backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ProjectDatabaseHandlerTest.java
- backend/src/src-fossology/src/test/java/org/eclipse/sw360/fossology/FossologyHandlerLocalhostIntegrationTest.java
- backend/src/src-health/src/main/java/org/eclipse/sw360/health/HealthHandler.java
- backend/src/src-health/src/main/java/org/eclipse/sw360/health/db/HealthDatabaseHandler.java
- backend/src/src-health/src/test/java/org/eclipse/sw360/health/HealthHandlerTest.java
- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
- backend/src/src-licenses/src/test/java/org/eclipse/sw360/licenses/LicenseHandlerTest.java
- backend/src/src-moderation/src/test/java/org/eclipse/sw360/moderation/testutil/DatabaseTestSetup.java
- backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- backend/src/src-projects/src/test/java/org/eclipse/sw360/projects/ProjectHandlerTest.java
- backend/src/src-users/src/test/java/org/eclipse/sw360/users/UserHandlerTest.java
- backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
- backend/src/src-vendors/src/test/java/org/eclipse/sw360/vendors/TestVendorClient.java
- backend/src/src-vendors/src/test/java/org/eclipse/sw360/vendors/VendorHandlerTest.java
- backend/utils/src/test/java/org/eclipse/sw360/attachments/db/RemoteAttachmentDownloaderTest.java
- build-configuration/test-resources/couchdb-test.properties
- libraries/importers/src/test/java/org/eclipse/sw360/importer/ComponentAndAttachmentAwareDBTest.java
- libraries/lib-datahandler/src/main/thrift/health.thrift
- libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/TestUtils.java
- libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/common/DatabaseSettingsTest.java
Added a new `DatabaseSettingsTest` class which will be used for test cases and renamed the `couchdb.properties` to `couchdb-test.properties` in test resources of build-configuration module which is used to keep the test database names and credentials.
> * Which issue is this pull request belonging to and how is it solving it? (*#1125*)
Issue: Closes #1125 
> You can suggest …
> fix(test): Use test databases in maven test phase

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/clearingDetails.jspf
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
> Which issue is this pull request belonging to and how is it solving it?
* #1129 
* No
Issue: closes #1129 
* `Show License Info` button in `Clearing Details` tab under `Release Details Page` should display the license with `+` sign.
* Should display `Other Licenses` as well. …
> fix(ReleaseUI): fix Spdx parser for License withh + sign

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/css/utils/_tagautocomplete.scss
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/basicInfo.jspf
- frontend/sw360-portlet/src/main/resources/sw360.properties
- created the new predefined tags for the Tag field in the Projects.
> * Which issue is this pull request belonging to and how is it solving it? (#1141 )
Issue: 
- Add a project in SW360 and select the tag from the auto-populated tag values.
-  we can also write our own tag …
> feat(PredefinedTags):Predefined tags per group in the Projects Tag field.

- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
Issue:   #1145 
I checked code and it seem that only adding 1 line , "add  CommonUtils.addAll(moderators, dbcomponent.getModerators());", is OK for solving them. 
(Follow …
> fix(moderation): Moderator can get moderation request

- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
> * Did you add or update any new dependencies that are required for your change? 
For couchdb 2.x users there will always be an exception while searching which is using `_fti` which consumes some resource. Hence removed support for `_fti` hook based lucene search for couchdb 1.x or earlier version. Ref: #926 
Issue: 
> How should these changes be tested by the …
> fix(search): Removing support for `_fti` hook based lucene search for couchdb 1.x

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src-common/src/main/resources/sw360.properties
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/AttachmentPortletUtils.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/AttachmentStreamConnector.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
> Store the attachments to local file system for the virus scan.
> * Which issue is this pull request belonging to and how is it solving it? (#1173 )
Issue: Closes #1173 
- We need to test this from the sw360 UI when we upload a attachment for a Project, Component or Release. 
- We need to test this from the Rest API as well for the below:
Add Attachment To Project
POST - http://localhost:8080/resource/api/projects/{ProjectId}/attachments
Add Attachment To Component
POST - http://localhost:8080/resource/api/components/{componentId}/attachments
Add Attachment To Release
POST - http://localhost:8080/resource/api/releases/{releaseId}/attachments
- Set …
> feat(AttachmentVirusScan): Store the attachments to local file system for the virus scan.

- CHANGELOG.md
- pom.xml
just PR to have the CI running to tag 13.3.
See changelog for details. 13.3 is about replacing ektorp with clouding.
> chore(rel): changing files for tagging 13.3

- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
> Added new endpoints to update attachment info of Project, Component, Release.
> * Which issue is this pull request belonging to and how is it solving it? (*#1189*)
Issue: closes #1189 
> Refer Rest Documentation
http://localhost:8080/resource/docs/api-guide.html#resources-project-attachment-info-update
Example Request -
```
curl 'https://sw360.org/api/projects/98745/attachment/1234' -i -X PATCH 
-H 'Content-Type: application/hal+json' -H 'Authorization: Bearer **********' -H 'Accept: application/hal+json' 
-d '{
"attachmentType" : "BINARY",
"createdComment" : "Created Comment",
"checkedComment" : "Checked Comment",
"checkStatus" : "ACCEPTED"
}'
```
> …
> feat(rest): Added new endpoints to update attachment info of Project, Component, Release

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
> The Filter for Group in Advanced Search should read from the Project List Group not from the user table.
> * Which issue is this pull request belonging to and how is it solving it? (#1194 )
Issue: closes #1194 
- To Test this, go to the Projects tab Advanced Search option and select the filter by Group and search the projects.
- The values populated in the Group in …
> feat(ProjectGroupFilter):Filter the projects in Advanced Search based on Projects Group.

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentOwnerRepository.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentRepository.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseRepositoryCloudantClient.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CustomThriftDeserializer.java
The boolean fields and timestamp being ignored in the middle layer. Hence the values are not being rendered correctly in the UI.
> * Which issue is this pull request belonging to and how is it solving it? (*#1211*)
Issue: 
closes #1211 
* Need to verify the dates are appearing correctly in moderations and clearing requests …
> fix(backend): Issues with boolean and timestamp field deserialization and get attachment REST

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/tags/DisplayMapOfExternalIdsString.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseRepositoryCloudantClient.java
Issue: 
500 Error fetching releases by external id with value from rest. If the release contains any external id with value null, then it breaks the release view.
* Need to test the endpoint …
> fix(ui/rest): Issue fetching releases by external ids from REST and null value in external id breaks the release view

- frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_tooltips.scss
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/add.jsp
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
>   Added a help text for the obligation level in admin obligations tab for the user.
> * Which issue is this pull request belonging to and how is it solving it? (#1226 )
> * Did you add or update any new dependencies that are required for your change? NA
Issue: closes #1226 
- To Test this go to Admin->Obligations->Add obligation
- Validate the different help text for the Obligation Level.
> Have you …
> feat(obligationlevelhelptext):Provide info text for different obligation Level.

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
**Issue:** 
It is observed some of the project documents having linked obligation (with field `linkedObligationId` in database). However without any any proper linked obligation status(field: `linkedObligationStatus`) in the corresponding linked  document(reason unknow).
like
`{
"_id": "4ac36b2711dd4d63a7fc7fcb967bd2b2",
"_rev": "19-c1c61973923d83ea3732ee77fcff8804",
"type": "obligationList",
"projectId": "4a0860307fae44a18bbc978042cf8fd1"
}`
which causes the null pointer downloading readme_oss and it breaks …
> fix(readmeossdownload): Null pointer while downloading readme_oss

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
Signed-off-by: Nguyen Phuong Nam <nam1.nguyenphuong@toshiba.co.jp>
Add 
`return RequestStatus.INVALID_INPUT`
when call to 
`deleteComponent`
Issue: #851 
Must:
> fix REST: Wrong error handling when deleting multiple components #851

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ModerationSearchHandler.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/ModerationHandler.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/ModerationServlet.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationRequestRepository.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
- libraries/lib-datahandler/src/main/thrift/moderation.thrift
Issue: 
It is observed the "Requests" tab taking longer time to load if the number of requests are higher.  This changes adds the paginated view response for loading moderation requests instead off getting all the moderations on a single hit upon clicking on "Requests" tab which might decrease the loading time. 
Note: 
- Had to remove the data table quick filter …
> feat(moderations): Paginated view for requests tab for moderations

- scripts/compileWithDocker.sh
- sw360dev.Dockerfile
> Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
Issue: 
Build failure of sw360dev.Dockerfile and compileWithDocker.sh #1230 
- Use maven:3.6.3-openjdk-11-slim. It’s the same base image version of Dockerfile.
- Use "-u" option for docker run
su-exec command is not available for Debian based maven image. Instead of it, "-u $(id -u):$(id -g)" option can be used for docker run command. For reference, please see https://hub.docker.com/_/maven
- Pass user.home directory and maven config directory for docker run
Otherwise, the following error is displayed and build failed.
[ERROR] Failed to execute goal com.liferay:com.liferay.portal.tools.theme.builder:1.1.8:build (default) on project liferay-theme: URI has a query component -> [Help 1]
- Remove …
> fix(script): Build failure of compileWithDocker.sh #1230

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligations.jspf
> * Which issue is this pull request belonging to and how is it solving it? (#1237)
Issue: closes #1237 
> How should these changes be tested by the reviewer? 
- To Test this go to Projects->Obligations 
- Validate the different help text for the License Obligation, Project obligation, Component obligation, Organistion …
> feat(ObligationHelpTextforProject): Provide the different obligation help text from the Projects Screen under Obligations tab.

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
> Support map of release id to usage as request body in addition to previous array of release id for - Link/Patch Releases to a Project API.
Issue: closes: 
- **3.3.19. Link Releases to the project**
- Doc - http://localhost:8080/resource/docs/api-guide.html#resources-project-link-releases
- Request structure 1 - Array of Release Ids (Existing)
```
curl 'https://sw360.org/api/projects/376576/releases' -i -X POST 
-H 'Content-Type: application/hal+json'  -H 'Authorization: Bearer ************' 
-d '[ "3765276512", "5578999", "3765276513" ]'
```
- Request structure 2 - Map of Release Ids to usage (New)
``` …
```
> feat(rest): Support map of release id to usage as request body in addition to previous array of release id for - Link/Patch Releases to a Project API

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
Issue: 
Release clearing state should be automatically set based on attachments and it's type in release, which is working fine in UI, however from REST it can be set manually.
This change is to ignore clearing state value while creating or updating release via REST, which is handled automatically in backend([here](https://github.com/eclipse/sw360/blob/8f7caf8aa02a0b7a28dcb23863eb52116466da4b/backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/Com …
> fix(rest): Auto-set release clearing state

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
> - Update private pages to fix friendly license url
> - Update generate main license url function
Issue: #1130 #1164 
> Add Main Licenses to Component and click the License links
> ![image](https://user-images.githubusercontent.com/85483077/121880751-949b4b00-cd38-11eb-88c1-e45ae55a652d.png)
Must:
> fix(ui): Link to main license detail page

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CommonVulnerabilityPortletUtils.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_tooltips.scss
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/vulnerabilities.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/vulnerabilities.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/vulnerabilities/view.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/bridges/datatables.js
> Issue: After changing the relevance of a CVE within the project's vulnerability view, the relevance rating in the pop-up box is not displayed properly.
>
> Solution: Correct the mechanism how relevance rating (DataTable tooltip) is rendered and displayed.
Issue:  #1042 
> 1. Setup CVE Search server follow the installation manual: [SW360-CVE-mannual-20210621.md](https://github.com/eclipse/sw360/files/6698844/SW360-CVE-mannual-20210621.md)
> 2. Update …
> fix(ui): Vulnerabilities relevance rating (tooltip) is not shown properly

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
> Fixed Moderation Request for Project is not opening.
>  * Optimized loading for Project/Component/Release Moderation Request Edit Page.
>  * Optimized REST API for search Project By Name, since common backend api is used.
>  * Optimized REST APIs for search Project by externalId, since common backend api is used.
>  * Optimized REST APIs "Resources using the project/release", since common backend api is used.
>  * Optimized Project/Release Details/Edit/Duplicate page to get usingProjects, since common backend api is used.
>  * Optimized merge releases which are used by some Project, since common backend api is used.
> * Did you add or update any new dependencies that are required for your …
> fix(ModerationRequest): Fixed Moderation Request for Project is not opening

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeComponent.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/mergeRelease.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/mergeWizard.js
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/CommonUtils.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
> * Issue: Additional data of Project/Component/Release are sorted by unclear algorithm
> * Solution: Sort the additional data of Project/Component/Release follow alphabet order (based on key values)
Issue: #1096 
> 1. Project:
> - Add new or edit existing Project, change the Additional data
> ![image](https://user-images.githubusercontent.com/85483077/124575711-d326b000-de75-11eb-964b-803ba71279d0.png)
> - After finish adding/editing, Additional data …
> feat(ui): sort the additional data of Project/Component/Release follow alphabet order

- backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
> Which issue is this pull request belonging to and how is it solving it?
- #1292 
- No.
Issue: #1292 
- `Project name`, and `business unit` should load for closed clearing request tables, If there are more CR in closed state.
- `Clearing Team` should be able to update the …
> fix(RequestUi):BU & ProjectName not loading for Closed CR table

- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissions.java
Signed-off-by: Shi Qiu <shi1.qiu@toshiba.co.jp>
Issue: 
#1281 
Create two projects named as "Department" and "Department1", the member of each department can not see the project which is not themselves'.
Refer to this commit : https://github.com/eclipse/sw360/issues/1281#issue-928930066
Must:
> fix(ui): fix visibility of the group

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentSelectTable.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/licenseInfo.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/sourceCodeBundle.jsp
- frontend/sw360-portlet/src/test/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtilsTest.java
> Fixed Generate License Info, Clearing Report and Source Code Download with/without subproject and showAll/onlyApproved filter
Issue: 
>  Generate License Info, Clearing Report and Source Code Download with/without subproject and showAll/onlyApproved
>  - Validate downloaded content.
>  - Reload page and validate attachmentUsage/selection is saved.
>  - Toggle between `showAll/onlyApproved` view, verify list content is ok
>     - (from discussion) - for download from `only approved` tab. attachementUsage for selected approved attachment + existing(in DB) attachementUsage for non-approved attachment , …
> fix(ui): Fixed Generate License Info, Clearing Report and Source Code Download with/without subproject and showAll/onlyApproved filter

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Adding a contributing.md file for describing contributiomn guidelines. The guidelines are specific to the sw360 projects
Also added a code of conduct description to make this clear, based on the publicly available contributor covenant.
closes #102 
> Adding contribution guidelines and code of conduct

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
This PR fixes the issue #1314 
No.
Issue: #1314 
* Login with user with role `user` and group as `Department` and then create a project `P1`.
* Set the `Additional Data` field with Key as `BA BL` and …
> fix(ClearingUI): ClearingExpert can't edit the CR

- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
> Implement Rest API for linking release to release
Issue: #863 
> Refer to:
> Link Release to Release API doc: http://localhost/resource/docs/api-guide.html#resources-release-link
> Have you implemented any additional tests? - Yes
Must:
> feat(rest): Add Rest API for linking release to release

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
> Make the REST API getReleaseByName case insensitive, to fetch all the releases for a component.
> * Which issue is this pull request belonging to and how is it solving it? (*#1327*)
> * Did you add or update any new dependencies that are required for your change? NA
Issue: #1327
- http://localhost:8080/resource/api/releases?name=ECHARTS
> Have you implemented any additional tests? No
Must: …
> fix(Rest):make SW360 REST API Get Releases by Name Case-Insensitive.

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
>  Rename the error message from "Error:Error fetching project. Project or its Linked Projects are not accessible. " to "Error:Project or its Linked Projects are restricted and / or not accessible."
> * Which issue is this pull request belonging to and how is it solving it? (*#1329*)
Issue: #1329 
One way to test this.
- …
> fix(MyProjectErrorMessageUI):update the error message in UI for the project which is not accessible.

- scripts/startCouchdbForTests.sh
Issue:  #1287 
Update couchdb docker image from version 1 to version 3.1 with password
I used the same password settings and couchdb's vesrion as here.
https://github.com/eclipse/sw360/blob/1bda34fa3625e7cdc66fc0875384adc01c792b1 …
> fix(script): Update CouchDB version and add password and user

- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/basicauth/Sw360LiferayAuthenticationProvider.java
Signed-off-by: Shi Qiu <shi1.qiu@toshiba.co.jp>
Just added a simple exception processing for the liferayAuthCheckRequest() method in Sw360LiferayAuthenticationProvider.java.
Issue: #1340 
No. …
> fix(rest): Added exception processing for authorization

- Dockerfile
- scripts/docker-config/etc_sw360/authorization/application.yml
- scripts/docker-config/etc_sw360/couchdb.properties
- scripts/docker-config/install_scripts/build_couchdb_lucene.sh
- scripts/docker-config/install_scripts/download_liferay_and_dependencies.sh
- scripts/docker-config/install_scripts/entry_point.sh
- scripts/docker-config/install_scripts/install_configure_couchdb.sh
- scripts/docker-config/install_scripts/install_init_postgres_script.sh
Issue: #1322  #1331
Build docker image by using this commad
> docker build -t …
> fix(docker):Update couchdb3.1 ubuntu20.04 liferay7.3.4 postgresql12

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
> Component details not shown for the Security Admin Role.
> * Which issue is this pull request belonging to and how is it solving it? (*#1368*)
Issue: closes #1368 
- Select the Site Role for the sw360 user as Security Admin.
- Open Components link in the UI.
- Open a component details.
> Have you implemented any additional tests? No
Must:
Signed-off-by: ravi110336 …
> fix(UI):Component details are not shown for the Security Admin Role.

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
> Added new parameter luceneSearch to Get Project List Api, to get project list based on lucene search.
Issue: 
> Refer Rest Documentation - `3.3.3. Listing by lucene search` - http://localhost:8080/resource/docs/api-guide.html#resources-projects-list-by-lucene-search
```
curl 'https://sw360.org/api/projects? 
name=Test&type=PRODUCT&group=sw360+AR&tag=project+test+tag+1&luceneSearch=true' -i -X GET \
-H 'Authorization: Bearer ******************'
```
> Pass parameters with different combination like name, group, tag, type
>  - Verify output should be same as in UI Project Listing Page with Advanced Search …
> fix(rest): Added new parameter luceneSearch to Get Project List Api, to get project list based on lucene search

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
> Fixed hateoas link not showing correct protocol.
> * Which issue is this pull request belonging to and how is it solving it? (*#1385*)
Issue: closes #1385 
> Perform sanity check of all rest apis.
> verify if ssl is enabled then response body link should be `https` instead of `http`
Must:
> fix(rest): Fixed hateoas link not showing correct protocol

- backend/src/src-licenseinfo/src/main/resources/xhtmlLicenseInfoFile.vm
> Links in ReadmeOss as HTML are not rendered properly.
> * Which issue is this pull request belonging to and how is it solving it? (*#1383*)
Issue: closes #1383 
> Generate ReadmeOss as html.
> Escaping of html should be prevented if content contains
>  -  link - `<a href="link">text</a>`
>  -  no script tag - `<script> ***** </script>`
>  -  Verify links are rendered correctly in Copyrights, Acknowledgements and License Content
Must:
> fix(ui): Links in ReadmeOss as HTML are not rendered properly

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsagesRows.jspf
Signed-off-by: Shi Qiu <shi1.qiu@toshiba.co.jp>
Fix the bug that attachments usages in project can not show "other" line correctly.
Issue: #1354 
Just add two TD tags.
No. …
> fix(ui): Fix the bug that attachments usages in project can not show "other" line correctly

- rest/resource-server/src/main/resources/application.yml
- scripts/docker-config/etc_sw360/rest/application.yml
> Change base url of health api from /actuator to /.
> * Which issue is this pull request belonging to and how is it solving it? (*#1404*)
Issue: closes #1404
> Place `application.yml` in `/etc/sw360/rest/application.yml`
>  - Test Health, Info, Get Project by Id api as per documentation
Must:
> fix(rest): Change base url of health api from /actuator to /

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- backend/src/src-wsimport/src/main/java/org/eclipse/sw360/wsimport/thrift/ThriftExchange.java
- libraries/lib-datahandler/src/main/thrift/components.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
Issue: 
-  Need to test the listing components by name endpoint w.r.t case sensitivity. 
> Have you implemented …
> fix(rest): Get component by name case insensitive

- CHANGELOG.md
- README.md
- pom.xml
This PR is change log for release 14.0.0
Issue: 
Must:
> chore(rel): changing files for tagging 14.0

- README.md
Update release badge to always point to latest release from GitHub.
> No preference
Check the badge on README. It should point to latest release.
Must:
> No related issues available
Signed-off-by: Gaurav Mishra <gmishx@gmail.com>
> chore(readme): Update release badge to latest

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/eccStatus.jspf
> Added new column for ECCN in ECC status tab of project details view.
> * Which issue is this pull request belonging to and how is it solving it? (*#1414*)
Issue: closes #1414 
> A new column(`ECCN`) needs to be added to `project details page` -> ECC tab ![image]
`ECCN` data can be fetched and updated from the release record
Must:
> feat(ui): Added new column for ECCN in ECC status tab of project details view

- CHANGELOG.md
- pom.xml
This PR is change log for release 15.0.0
Issue: 
Must:
> chore(rel): changing files for tagging 15.0

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/search/SearchPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/search/view.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/images/icons.svg
> In Search screen, if you leave the Keyword empty, there will be no data in the table after searching finished.
> 
> But if Keyword is filled with some space characters, depend on which Type is checked, all the data of that Type will be displayed.
>
> Expectation: if Keyword is empty, returns all data of selected Type.
Issue: https://github.com/eclipse/sw360/issues/1430
> 1. From Main menu, open 'Search' screen.
> 2. Leave Keyword empty, and not check …
> fix(ui): Search function does not work if Keyword is empty

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
- backend/src-common/src/main/resources/sw360.properties
> * When new Release is created by using API, if Source Code download URL is provided, the ECC status is automatically set as 'Approved';
> * ECC should be approved manually by user
> * With this PR, this automation setting can be configured in the file: backend/src-common/src/main/resources/sw360.properties - key 'auto.set.ecc.status'
> * auto.set.ecc.status = true: ECC status will be automatically set …
> fix(api): Correct the ECC status when release is created by API

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
> Optimized code to check for write permission of release and components before starting to merge.
> As per changelogs, It is observed that in some cases, after merge of component . 
> The corresponding releases are not updated with new component Id.
> Thereby creating orphaned Release.
> Maybe Merge is failing in the middle due to permission issue of Release
> As a solution, check has been added for WRITE permission of all releases before actual merge is started.
Issue: 
> Test General functionality of merge/split component
Must:
Signed-off-by: Jaideep Palit …
> fix(merge): Optimized code to check for write permission of release and components before starting to merge

- README_DOCKER.md
Just a typo in the documentation, the `docker run` command option `--name` doesn't have the double hyphen
> typo in the docker run command

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/mail/MailConstants.java
- backend/src-common/src/main/java/org/eclipse/sw360/mail/MailUtil.java
- backend/src-common/src/main/resources/sw360.properties
- backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExcelExporter.java
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/helper/ProjectHelper.java
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/helper/ReleaseHelper.java
- libraries/lib-datahandler/src/main/thrift/projects.thrift
> Generate and save excel to file system, Download generated file with token.
> * Which issue is this pull request belonging to and how is it solving it? (*#1475*)
closes: #1475 
Must:
> feat(exportExcel): Generate and save excel to file system, Download generated file with token

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
Fixed the incorrect open components count in Open Clearing request table.
Issue: #1523 
Follow the steps mentioned in issue #1523 
Must:
> fix(CR-UI): fixed the count mismatch in Open Components column of CR table

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src-common/src/main/resources/sw360.properties
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ComponentExporter.java
- libraries/lib-datahandler/src/main/thrift/components.thrift
* Enable mailing for exported "component" and "component with releases" spreadsheet functionality.
Issue: 
* Set …
> feat(export): Enable mailing for exported spreadsheet for components

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentAwareDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorDatabaseHandler.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/editBasicInfo.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/summary.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/editReleaseInformation.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/summaryRelease.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/basicInfo.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/summary.jspf
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
- libraries/lib-datahandler/src/main/thrift/components.thrift
- libraries/lib-datahandler/src/main/thrift/projects.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
Added `ModifiedBy` and `ModifiedOn` fields for `Project`, `Component` and `Release.
Issue: #1479 
- Modify / Update the project , component and release from UI and REST API. You should be able to see the `ModifiedOn` and `ModifiedBy` fields values in UI.
- Merge / Split the `Component`, Only the component that got merged should have appropriate `ModifiedOn` and `ModifiedBy` fields values, and not the linked releases.
- These 2 fields are not exposed via `REST` …
> feat(UI): ModifiedOn & MOdifiedBy fields for Project/COmponent/Release

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/VendorRepository.java
- backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorDatabaseHandler.java
- backend/src/src-vendors/src/main/java/org/eclipse/sw360/vendors/VendorHandler.java
- backend/src/src-vendors/src/test/java/org/eclipse/sw360/vendors/VendorHandlerTest.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ErrorMessages.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/Sw360Portlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/BulkReleaseEditPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/VendorPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/vendors/edit.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/components/includes/vendors/addVendor.js
- libraries/importers/src/main/java/org/eclipse/sw360/importer/ComponentImportUtils.java
- libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
- libraries/lib-datahandler/src/main/thrift/vendors.thrift
- rest/resource-server/src/docs/asciidoc/vendors.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java
Issue: #1554
1. All the 3 fields of vendor object -> `full name`, `short name` and `url` should get trim from both end before being saved in database.
2. User should NOT be able to create a duplicate Vendor from REST API, Admin portlet, Editing of project / component and release. …
> feat(Vendor):Trim fields, Restrict vendor duplication & create Vendor via REST

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
Signed-off-by: Nikesh kumar <kumar.nikesh@simens.com>
This is due to License not being present in SW360 license database.   
These license (at times invalid) are added into Release / Components via CLI XML without any validations at SW360 end.  
Once can add these license into SW360 database via REST or UI.
> * Which issue is this pull request belonging to and how is it solving it? #1566
> * Did you add or update any new dependencies that are required for your …
> fix(rest): Added release main licenses in the response

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
Issue: #1223 
Currently, if the user goes to the component page at the first time, the components will be sorted by "CreatedOn". After that, the user goes to the next page, the components will be sorted by "Name".
The behavior is not incorrect, but it will cause misunderstanding for users.
Refer to #1223 
Must:
> Fix (Component): Fix bug component list sorting

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ReleaseTest.java
1. `Main License Id` validation will happen only if there has been any modifications in `Main License Id` while updating the `release` over `REST` API.
2. `Release` update will fail, if `Main License` field is modified in update operation and validations fails in step 1.
3. `Release` update will be successful, if `Main License` validations is successful or if there is no modifications in `Main License Id` in update operation.
Issue: #1536
1. Create a `release` …
> fix(REST): fixed release update issue for releases with invalid licenses

- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseTypeRepository.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/licenses/includes/detailText.jspf
- Restrict the duplication of `License Type` - by adding case insensitive check and trimming the leading and trailing whitespaces.
- Changed the `License Text` format in `License Details page` to retain the new line and whitespaces.
Issue: #1562 
- User should not be able to create a duplicate `License Type` by changing case and adding trailing / leading whitespaces.
- `License Text` in `License Details page` should retain whitespace and new lines to improve …
> fix(AdminUI): Prevent license type duplication with case insensitive check

- frontend/liferay-theme/src/main/webapp/css/portal/_header.scss
- frontend/liferay-theme/src/main/webapp/js/banner.js
- frontend/liferay-theme/src/main/webapp/templates/portal_normal.ftl
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/CustomFieldHelper.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/homepage/MySubscriptionsPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/init.jsp
Signed-off-by: rchopra <rudra.chopra@siemens.com>
Issue:  Add banner to broadcast messages (#1595)
Description : This functionality can be edited by Admins only.
1) Click on 9 dots on the top right section of the page
2) Go to control panel -> click custom fields under configuration
3) Select User under Resource section
4) There you will see BannerMessage custom field.
5) Click on three dots to edit this field. Here you can enter message that you want to be displayed.
6) Right click on three dots and give view permission to all sw360 users/roles and change other permissions too. (Refer the ss for this step)
Click custom field under control panel section
Select User under resource section
Banner Message custom field should look like this
Give view permission to all sw360users/roles and …
> feat(ui): Add banner to broadcast messages

- frontend/sw360-portlet/src/main/resources/META-INF/resources/css/main.scss
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/summary.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/clearingDetails.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/commercialDetails.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/eccDetails.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/summaryRelease.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/vendors/vendorDetail.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administration.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/summary.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/vendors/vendorDetail.jspf
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Made the table header collapsible in project, components and release details page. (only in read mode and not in edit mode)
Issue: #1584 
- Hover over any table header of `summary` tab in projects, components or release and it should display tooltip `click to expand or collapse`
- Clicking on header should expand or collapse the table body.
Must:
> feat(UI):Made the table header collapsible wherever possible

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- libraries/lib-datahandler/src/main/thrift/licenseinfo.thrift
- `License Info Header` text can be configured based on project group, using the property `org.eclipse.sw360.licensinfo.header.by.group` in `sw360.properties` file.
Issue: #953 
- Define a property key `org.eclipse.sw360.licensinfo.header.by.group` in `sw360.peoperties` files, with value as `GroupName : LicenseHeaderInfoTextFileName.txt` (comma separated for multiple group)
- For example: `org.eclipse.sw360.licensinfo.header.by.group = …
> feat(ProjectUI): Load License info header text based on project group

- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/components/includes/releases/linkProject.js
Issue: 
User able to link the component to a closed project.
(#1583)
* Go to Release page of the component and then try to link a project to that release by clicking "Link to Project"
*  Now Select any closed state project and try …
> fix(ui): cannot link Component with closed project

- scripts/docker-config/entry_point.sh
When compose is properly called to end ( down ), two signals are raised,
SIGINT/INT and EXIT. As the trap condition on shutdown script was tracking
down both, sw360_stop was called twice, failing on second instance
> fix(docker): Fix double called shutdown script

- .dockerignore
- .github/testForLicenseHeaders.sh
- Dockerfile
- scripts/download_dependencies.sh
Guava dependency was pointing out to wrong directory and not providing
any error on output, so creating an invalid file that failis only on
unpacking level.
If this kept used, in future maven should do the download automatically
instead of a script.
This provided possibility to alter Dockerfile deps download position,
and avoid recreate the build layer all the time.
In addition, a dockerignore file is added to avoid copy deploy / target
/ buiid massive outputs if local build is used to build docker too.
> fix(deps): Fixed wrong dependency download

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/ChangeLogsPortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortletUtils.java
Changed the logic of how (portlet) layout details are fetched in java.
Issue: We cannot update the `clearing request` and also `X` portlet URL is not getting generated in `Y` portlet.
This PR fixes the above mentioned issues.
Now you should be able to update the clearing request.
Must:
Signed-off-by: akapti <abdul.kapti@siemens-healthineers.com>
> fix(ui): Generate portlet X url inside portlet Y

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/attachmentUsagesRows.jspf
Fixed `release filter` in `Attachment usages` tab of `project` details page.
Issue: #1628 
please refer issue description.
Must:
Signed-off-by: akapti <abdul.kapti@siemens-healthineers.com>
> fix(ProjectUI): fixed Release filter bug in AttachmentUsage tab

- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/ModerationHandler.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ClearingRequestRepository.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
- libraries/lib-datahandler/src/main/thrift/moderation.thrift
SW360 user were not able to create the `critical` clearing request, 
The issue was due:
- The critical CR from other group / department were also considered while fetching the count.
- There were `closed` CR in `critical` state.
Changes: 
- This PR includes changes in logic of fetching the `critical` CR count from database.
- This PR will make the critical CR mutually exclusive from user group (department).
- Now only critical CR in `open` state and the CR …
> fix(CrUi): fix the critical CR creation issue

- .github/workflows/githubactions.yml
- Dockerfile
- scripts/download_dependencies.sh
- scripts/install-thrift.sh
Thrift need to be built inside docker, but was only compiler, not
required jar, which is downloaded as external dependency.
Now both compiler and jar are generated on the fly from same build, and
using cmake based build. Boost and ssl dev dependencies are no more
necessary to the builder base image, reducing size and install time for
base build system.
> Use only provided tarball to generate resources

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/resources/sw360.properties
> * Which issue is this pull request belonging to and how is it solving it? (#1587 ) 
Issue: 
Do not copy any SVM component ids #1587 
1)Goto component tab
2)click on component name
3)select release overview
4)We will find the list of name, then click on version 
5)click on edit Release button
6)Add external ids and values, …
> fix/svmcomponentids - do not copy svm component ids

- libraries/lib-datahandler/src/main/thrift/components.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
> * Which issue is this pull request belonging to and how is it solving it? #1607 
> * Did you add or update any new dependencies that are required for your change? yes, I added component type tag under release API.
Issue: 
1) Go to component tab and click on any component name.
2) If you need to change in the exiting component or you can select Release …
> fix(rest): Added component type tag in release api

- scripts/migrations/051_change_eccStatus.py
- scripts/migrations/README.md
Description: This script will change the ecc status of the affected releases to APPROVED. 
Condition: releases must have oss component type and and the source code download url for release should not be empty.
Issue: #1641 
- Create a release with oss component type and the source code download url for release should not be empty.
- After the above step, an ecc will be created for that release and ecc status will be OPEN.
- After running the script, ecc status will get changed to APPROVED.
> fix(ecc): Script to change ECC status in Release

- .github/workflows/githubactions.yml
Fail fast with the license checker without setting a full blown system
> Reduce usage of ghactions resources when not needed

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
Issue: #1656 
Ecc fields value of release will reset after changing component type.
Exception: changing component type to OSS, the ecc status won't get changed.
> fix(ecc): Reset Ecc Fields when Component type is changed.

- .github/testForLicenseHeaders.sh
- .github/workflows/githubactions.yml
- Dockerfile
- frontend/sw360-portlet/pom.xml
- libraries/commonIO/pom.xml
- libraries/datahandler/pom.xml
- libraries/exporters/pom.xml
- libraries/importers/pom.xml
- libraries/log4j-osgi-support/pom.xml
- pom.xml
- utils/pom.xml
- All maven dependencies are moved from the shell script to a maven process plugin
- sw360-portlet was proper moved to a war file
- Deployments of portlets now go to tomcat and libraries to deploy
> feat(buildsystem): Rearrange dependencies and deployments

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/UserPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/users/OrganizationHelper.java
- frontend/sw360-portlet/src/main/resources/sw360.properties
- Fetch the `countryid` based on `companyid` and `name` instead of using the default countryid (`19`) provided by Liferay, 
Issue: #1707 
1. Create a user from SW360 admin portlet with the new department (should not be present in Liferay PostgreSQL DB)
3. Upload the users with new department from csv file.
4. Creation of user should be successful in both of the above steps. …
> fix(User): CountryId does not exists while creating user with new Organization

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/DocumentPermissions.java
- libraries/datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/ProjectPermissionsTest.java
> Added a check so that 'clearing admin' user can merge components
> * Which issue is this pull request belonging to and how is it solving it? (#1669 )
Issue: 
Merge Components fails with error message #1669
1. Log in as 'clearing admin' user
2. Open a component and click on merge button
3. Select another component to merge into and run through the entire dailog and eventually click on Finish button
Signed-off-by: Eldrin <eldrin.sanctis@siemens.com>
> Added access for deleting merge source release for clearing admin

- backend/src-common/src/main/java/org/eclipse/sw360/components/summary/LicenseSummary.java
Signed-off-by: Nikesh kumar <kumar.nikesh@simens.com>
when we export spreadsheet in licenses tab, Text field column is blanks, So i  add the code to show the text data while export spreadsheet.
> * Which issue is this pull request belonging to and how is it solving it? #1709 
Issue: when we export spreadsheet in licenses tab, Text field column is blanks.
> You can suggest …
> fix(UI): Text field is blank while ExportSpread in licenses

- .github/workflows/docker_deploy.yml
- Dockerfile
- docker-compose.yml
- pom.xml
- utils/pom.xml
Add missing OSGI dependencies:
1. `commons-compress`
2. `failureaccess`
3. `libthrift`
In `docker_deploy.yml`:
1. Fix the docker image root to use `ghcr.io` registry
2. Fix Thrift version to `0.16.0` to match `pom.xml`
In `docker-compose.yml`:
1. Add `ghcr.io/` registry to sw360 image.
2. Add healthcheck to postgres and couchdb
In `Dockerfile`:
1. Fix thrift version to `0.16.0` to match `pom.xml`
2. Fix `liferay.deploy.dir` path to liferay/deploy
3. Add `ghcr.io/` registry to image path to prevent using …
> fix(docker): add missing dependencies

- Dockerfile
- docker-compose.yml
- Liferayy need to deploy theme in own deploy directory, not tomcat one.
- Disabled docker-compose document_library volume as never used
Thanks @GMishx
> fix(docker): Deploy libraries in correct place

- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Rest-Docs not get updated for Definition of Manufacturer on project level issue so I write a junit code as per the exiting scenario and test it from rest api url as well in REST Api Docs
Issue: #1676 
1.login into sw360
2. after …
> Update the REST-API documentation for Definition of Manufacturer on project level

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/preferences/view.jsp
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
Changes:
1) Read Access will be checked by default while generating token.
2) It is mandatory for Read access to be checked.
3) An error message saying 'Read Access is required' will be displayed if Read access is unchecked by user.
Issue: #1722 
Click on 'Generate Token' with the Read Access box unchecked.
> fix(PreferencesUI):Read Access has to be checked before Generating token

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
Description: (Accidently closed old PR #1714 )
1) Only a single instance of each linked project will be displayed in the Vulnerabilities tab.
2) This prevents multiple initializations leading to multiple Datatables alerts.
Issue: #1704 
@akapti
> fix(ProjectUI): Multiple alerts when there are same linked projects

- frontend/liferay-theme/src/main/webapp/css/portal/_alert.scss
- frontend/liferay-theme/src/main/webapp/templates/portal_normal.ftl
- This PR fixes the unresponsive UI elements when Session Message pop-up is open.
- Also top align the session message with full screen width (like [Liferay 7.3 session message](https://github.com/eclipse/sw360/pull/1508#issuecomment-1190234101)).
Issue: #1688 
Create and  Edit a `project / component / release` and you should see top align session message and all UI elements should be responsive.
Sample screenshot below:
Must:
Signed-off-by: akapti …
> fix(UI): Unresponsive UI & top align session message

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/oauthclient/view.jsp
Description:
1) Title has been changed to Update from Edit in the button used to save the changes.
2) The token validity metric will be set to Days by default while creating a new client.
3) Automatic conversion will take place from Days to seconds and vice versa on switching between the two select options.
4) The issue where the form button would change to 'OK' even when the form has not yet been submitted has been resolved.
How To test:
1) Go …
> feat(AdminUI): Changed the title of the button to 'Update' from 'Edit' in Edit Client modal in OauthClient and set the validity to 'Days' by default

- libraries/datahandler/src/main/thrift/components.thrift
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java
Description:
- Spreadsheet exported from 'Project with linked releases' will have two additional columns i.e. 'main license IDs' and 'other license IDs' next to the 'clearing state' column.
Issue: #1717 
1) Navigate to Projects tab
2) Open a project and go to License Clearing section
3) Click on 'Export Spreadsheet' and select 'Projects with linked releases'. The downloaded spreadsheet should contain 'main license IDs' and 'other license IDs' …
> feat(ProjectUI):License Info In the Spreadsheet Exported from Project License Clearing

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
Issue:  #1726 
Go to component tab and click the release dropdown button when inspecting a release of that component.
The list of release versions should be in descending order (newest to oldest).
> Feat(UI): apply sorting in release versions when inspecting component

- backend/src/src-licenseinfo/pom.xml
- backend/src/src-licenses/pom.xml
- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/tools/SpdxConnector.java
- pom.xml
Issue: #1699
1. Go to License Page in Tab Admin
2. Click button Import SPDX Information
3. Check License in tab License in Home Page
Must:
> fix(SPDX):  Import SPDX licenses with new SPDX library (tools-java 1.0.4)

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ModerationSearchHandler.java
Signed-off-by: Eldrin <eldrin.sanctis@siemens.com>
For moderation request filtering, added a check that if documentId is null then ignore that document
> * Which issue is this pull request belonging to and how is it solving it? (#1747 )
Issue: Moderation requests: search/filter does not work
1. Go to Requests tab
2. Filter the moderation request by searching for department 'SI' or 'ADV'
3. The search results an empty list even though there are many requests
> fix(moderation_request): Added a check that if documentId is null then ignore

- backend/src-common/src/main/java/org/eclipse/sw360/mail/MailUtil.java
- backend/src-common/src/main/resources/sw360.properties
Feature to control the trusted host while sending emails via property `MailUtil_smtpSSLTrust` in sw360.properties file, which in turn set the `mail.smtp.ssl.trust` in email session.
Issue: 
Please refer this guide on how can we can control the trusted host while sending an email via config `mail.smtp.ssl.trust`.
https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html
Must:
Signed-off-by: akapti <abdul.kapti@siemens-healthineers.com>
> feat(MailApi): enable control over trusting the email host

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/entitlement/ProjectModerator.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/ModerationHandler.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
- libraries/datahandler/src/main/thrift/moderation.thrift
Changing `Business Unit (Group)` of `project` should change the `ProjectBU` field in Clearing Request.
Issue: #1665 
1. Login as user (let's say `U1`) from Group (Business Unit) `X`.
2. Create a new `project` (with Group as `X`), set visibility of project to `Everyone` and add linked `components`, and then raise the `clearing request` for the project (let's sat `CR1`).
3. Once `CR1` is created, logout from …
> fix(ProjectUI): Changing Project group should update CR

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
Description:
After using the `Group` filter in Project Advance Search, the result displayed will be refreshed on switching tab/reloading of page.
Issue: #1753 
Please refer #1753
> fix(ProjectUI):Stale data displayed after using the Group filter in Project Advance Search

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
…onent
> * Which issue is this pull request belonging to and how is it solving it? #1755 
Issue: 
When we do duplication in product and component (release) tab, few unnecessary information is also copied, so we unset those field as per the user request.
1: Login sw360 
2: Go to project tab and create a duplicate.
3: Go to …
> fix(UI): unset few field while create a duplicate in project and component tab

- backend/src/src-fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
> * Which issue is this pull request belonging to and how is it solving it? #1789 
Issue: 
SW360 release, after the Successful FOSSology trigger is initial scan report and the report type is CLX which is wrong and which makes the SW360 status as "Report Available so we change report type is Initial Scan report this is the correct behavior.
> You can suggest reviewers here with an …
> fix(UI): ISR which will make the SW360 Release status as Scan Available

- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
> * Which issue is this pull request belonging to and how is it solving it? #1792 
Issue: 
we have added Created on field for project only and project with linked release in project tab.
1: Login sw360
2: Go to project tab
3: download export sheet and verify created on field  …
> fix(UI) : Added Created on in project export

- .github/workflows/build_and_test.yml
- scripts/install-thrift.sh
A part of CI build time is dedicated to rebuild Thrift all the time.
To avoid this, we will cache the binary when exists.
> feat(ci): Add thrift binary to cache

- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
> * Which issue is this pull request belonging to and how is it solving it? #1744 
Issue: 
Added EnableSVM field in project ExportSpreadsheet.
1: checkout Enable Security Vulnerability Monitoring in project tab.
2: download Export Spreadsheet 
3:verify in xls sheet.
> Have you …
> fix(UI): Added EnableSVM field in project exportspreadsheet

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
Fix bug update project without vendor information will remove existing vendor information
Fix issue 3 of #1770 
Precondition:
There is a project (project name: P1, a vendor A was linked to P1
Step 1: Update project P1 via API http://{server_ip:port}/resource/api/projects/{IdProject}
{
"name": "P2",
"description": "This is a sample project",
}
Step 2. Check vendor information via API/GUI
Expected output: Vendor A won't be removed.
> Fix(REST): Fix bug update project without vendor information will remove existing vendor information

- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/utils/includes/attachmentsUpload.js
Description:
- Upload bar in attachment upload modal will be hidden until the user clicks on upload button.
- This ensures an empty progress bar is not seen.
Issue: #1745 
How To Test?
- >Edit a project/component
- >Go to Attachments tab
- >Click on 'Add Attachment' button.
- >Upload a file
Screenshots:
On selecting a file
On clicking 'Upload'
> fix(attachmentsUploadModal) : The progress bar will be shown only after a file has been selected and is uploading

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
- `Add License Info to Release` feature at project-level will work for release with only one `non-Approved CLI` as well.
- `Obligations` will now be pulled from those release where only on non-approved CLI is present.
Issue: #1763 
Use Case 1:
1. Add only one CLI (xml/rdf) file (say `CLI X`) containing `License A` and `Obligations B` in release (say `Release A`) as attachment.
2. Link the release from step 1 `Release A` to a project (say: `project A`)
3. Loading of `project A` should load `Obligations B` …
> feat(ProjectUi): Enable Release with only one non-approved CLI for 'Adding License Infor To Release' and 'Displaying Obligations'

- clients/client/src/main/java/org/eclipse/sw360/clients/adapter/SW360VulnerabilityClientAdapterAsync.java
- clients/client/src/main/java/org/eclipse/sw360/clients/adapter/SW360VulnerabilityClientAdapterAsyncImpl.java
- clients/client/src/main/java/org/eclipse/sw360/clients/rest/SW360VulnerabilityClient.java
- clients/client/src/test/java/org/eclipse/sw360/clients/adapter/SW360VulnerabilityClientAdapterAsyncImplTest.java
- clients/client/src/test/java/org/eclipse/sw360/clients/rest/SW360VulnerabilityClientIT.java
- clients/client/src/test/resources/__files/delete_vulnerability_release_relation.json
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java
Improve the function of API to delete vulnerability information
Issue: #1606 
- Delete vulnerability success:
HTTP Status Code: 207
Response body:
[ {
　　　    "resourceId" : "external_id_1",
　　　     "status" : 200
} ]
- Vulnerability is linked with other releases:
HTTP Status Code: 207
Response body:
[ {
　　　    "resourceId" : "external_id_2",
　　　     "status" : 403
} ]
- Vulnerability does not exists:
HTTP Status Code: 207
Response body:
[ {
　　　    "resourceId" : "external_id_3",
　　　     "status" : 404
} ]
- …
> Update(Vulnerability): Improve the function of API to delete vulnerability information

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/clearingStatus.jsp
*  When the linked projects/releases size is large, then the downloading export spreadsheet is taking some time to download and which is blocking. These changes will enable emailing the download link after the spreadsheet writing is done. 
Issue: 
> You can suggest reviewers …
> feat(project): Added Email functionality for individual project spreadsheet export

- backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
Issue:  #1825 
Make a rest call for endpoint /components/usedBy/CompId.
Make sure this component does not have any releases.
The response for this rest call will be an empty list with 200 OK status message.
> fix(rest): endpoint components/usedBy/CompId gives 500 msg when no release attach to component

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
New `/projects/myprojects` to list projects for home page's "My Projects" table.
Please provide a summary of your changes here.
* Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
* Part of #1826
* Did you add or update any new dependencies that are required for your change?
* No
**How should these changes be tested by the reviewer?**
> Test the rest endpoint `/projects/myprojects` with various parameter …
> feat(rest): new endpoint `/projects/myprojects`

- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Issue: #1846 
Description: this endpoint returns the recent created 5 components in alphabetical order.
How to test:
Run this endpoint and you will get recent created components as response.
> feat(rest): new endpoint /components/recentComponents

- scripts/migrations/055_deactivateEmailNotification.py
- scripts/migrations/README.md
Issue: #1831 
Run the script to test the changes in db.
User's wantMainNotification field will change to false if that user does not belong to that specific domain.
Note: In script, add the domains that should belong to a particular instance.
> fix(db): Deactivate email notification of user not belonging to a domain

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/vulnerabilityTrackingStatus.jspf
Description:
ExternalId will now be displayed next to 'com.siemens.svm.monitoringlist.id:' under Vulnerability State Information when 'Do not create monitoring list, but use list from external id' checkbox is enabled.
Solves Issue: #1868 
Screenshot:
> fix(ProjectUI):External Id not visible in Vulnerability Tracking Status

- clients/client/src/main/java/org/eclipse/sw360/clients/rest/SW360Client.java
- clients/client/src/main/java/org/eclipse/sw360/clients/rest/SW360ReleaseClient.java
- clients/client/src/test/java/org/eclipse/sw360/clients/rest/AbstractMockServerTest.java
- clients/client/src/test/java/org/eclipse/sw360/clients/rest/SW360ReleaseClientIT.java
- clients/http-support/src/main/java/org/eclipse/sw360/http/HttpClientFactory.java
- clients/http-support/src/main/java/org/eclipse/sw360/http/HttpClientFactoryImpl.java
- clients/http-support/src/main/java/org/eclipse/sw360/http/NewHttpClientImpl.java
- clients/http-support/src/main/java/org/eclipse/sw360/http/NewRequestBodyBuilderImpl.java
- clients/http-support/src/main/java/org/eclipse/sw360/http/NewRequestBuilderImpl.java
- clients/http-support/src/main/java/org/eclipse/sw360/http/NewResponseImpl.java
- clients/http-support/src/main/java/org/eclipse/sw360/http/utils/HttpUtils.java
- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Converted request parameter to request body to disable external id decoding.
> * Which issue is this pull request belonging to and how is it solving it? (*#1659*)
Issue: 
Please refer the issue
> Have you …
> fix(rest): disable URI decoding in search by external ids in release

- .github/workflows/build_and_test.yml
- backend/src-common/src/main/java/org/eclipse/sw360/common/utils/BackendUtils.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src-common/src/test/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandlerTest.java
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- backend/src/src-components/src/test/java/org/eclipse/sw360/components/db/ComponentDatabaseHandlerTest.java
- backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- frontend/sw360-portlet/src/main/resources/sw360.properties
- libraries/datahandler/src/main/thrift/components.thrift
- libraries/datahandler/src/main/thrift/projects.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Issue:  #1861 
API Enhancements: API access without ModerationRequest
In SW360, the update process by general users generates Moderation Requests, so when general users register a large amount of data in a batch file, the approval process of the request becomes a problem. …
> feat(rest) : Update data without moderation request And This features' configurable setting

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/editAttachments.jspf
- Attachment info will be sent in Ajax GET request only if there is duplicate error while updating the document.
Issue: #1886 
@afsahsyeda 
See the issue #1886  description
Must:
The other way to fix this issue is to configure the `/tomcat/conf/server.xml` and `Liferay/portal-ext.properties` file to increase the default GET request size.
Changes in `Liferay/portal-ext.properties`:
- `invoker.filter.uri.max.length=8000` -> Refer: …
> fix(UI): Attachments tab not loading in UI

- libraries/datahandler/src/main/thrift/projects.thrift
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
Description:
Two more fields "ExternalIds" and "Additional Data" have been added to the Excel exported from License Clearing in Project Portlet.
Issue: #1897
> feat(ProjectUI):ExternalIds and Additional Data fields in Export Excel in License Clearing

- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortletUtils.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/clearing/clearingRequest.jsp
Description:
> Admin will now be able to edit the Requesting User field while editing a clearing request in Requests Portlet
>An empty comment will not be generated when clicking on 'update Request' without actually making a change
Issue: #1892 and #1903
Screenshot:
> feat(EditCR): Admin will be able to reassign/edit the Requesting User of CR

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Issue: #1874 
Description:
REST API endpoint api/projects with the parameters allDetails=true and group=DEPARTMENT,
i.e. in total api/projects?allDetails=true&group=DEPARTMENT.
Unfortunately this does not return all projects matching the search spec as the projects that are not shown in response structure are the ones having linked projects of different group/BU.
How to test:
Test this endpoint and it will return all projects.
> Fix(rest): endpoint for projects does not return all projects with allDetails=true

- backend/src/src-users/src/main/java/org/eclipse/sw360/users/UserHandler.java
- backend/src/src-users/src/main/java/org/eclipse/sw360/users/db/UserDatabaseHandler.java
- backend/src/src-users/src/test/java/org/eclipse/sw360/users/UserHandlerTest.java
- libraries/datahandler/src/main/thrift/users.thrift
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360GrantedAuthoritiesCalculator.java
- rest/resource-server/src/docs/asciidoc/api-guide.adoc
- rest/resource-server/src/docs/asciidoc/users.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/filter/EndpointsFilter.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/basic/Sw360CustomUserDetailsService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/basic/Sw360GrantedAuthoritiesCalculator.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/basic/Sw360GrantedAuthority.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/basic/Sw360UserDetailsProvider.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
- rest/resource-server/src/main/resources/application.yml
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
* Added a password field in the user structure.
* Added username and password based validation from REST endpoint.
* Added one endpoint for creating user. 
* 
Note: The above endpoints are required for building new UI and initial step to get rid of Liferay.
> * Which issue is this pull request belonging to and how is it solving it? (*#1826*)
> * Did you add or update any new dependencies that are …
> feat(rest): Added creating user from REST and basic authentication

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceListController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ProjectTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
While fetching the projects without filter on `/projects` endpoint, optimize the call to `getAccessibleProjectsSummary()`.
No
Issue: #1899
@smrutis1
For big database, fetch projects from REST API without any filter. Try with …
> feat(rest): optimize fetch project

- libraries/datahandler/pom.xml
- pom.xml
Spring boot 2.x requires httpcore series 4 as dependencies, so usage of httpcore5 would force to upgrade to newer spring boot, too big change to simply normalize a single version.
> Revert httpcore and fix httpcore and spring-boot

- backend/src/src-licenseinfo/pom.xml
- backend/src/src-licenses/pom.xml
- backend/src/src-vmcomponents/pom.xml
- pom.xml
- utils/pom.xml
On current codebase, sw360 is using 6 different json libraries. 
Google old json-simple and Cliftonlabs json had name clash. Google library was removed.
JSON Issue reference: https://github.com/eclipse-sw360/sw360/issues/1921
Issue: https://github.com/eclipse-sw360/sw360/issues/1808
TODO: Change all code to use one single library
> * Did you add or update any …
> Normalize json versions

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Description:
Provided a new endpoint for SBOM import. This currently only supports SPDX files.
Issue: #1904
> feat(REST): Endpoint for SBOM import

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParserTools.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
> Please provide a summary of your changes here. <br>
- This PR fixes the newly generated SPDX-2.3 version Initial Scan Report (`.rdf` for ISR attachment) parsing issue.
- The  SPDX-2.3 version Initial Scan Report (`.rdf` for ISR attachment) should be generated from latest version of FOSSology.
Issue: #1915 
@afsahsyeda 
**Release portlet:**<br>
1. Create a release and upload SPDX-2.3 standard file as attachment of type `ISR` to release.
2. Go to `Clearing Details` tab of release and click on `Show License …
> feat(spdx): Added support for pasring of SPDX-2.3 (ISR) generated via FOSSology 

- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
**Description**
> * Endpoint already existed but api documentation was missing so rest api documentation added. 
Issue: #1907
> Just click on "Rest API Docs" button on the bottom of project main page. 
> Navigate to Components section and find "3.4.2 Listing components with all details".
> feat(rest):Components with all details Rest Api doc updated

- backend/src-common/src/main/java/org/eclipse/sw360/spdx/SpdxBOMImporter.java
Issue: https://github.com/eclipse-sw360/sw360/issues/1871
From Akapti's comment (https://github.com/eclipse-sw360/sw360/pull/1872#issuecomment-1521219796), I created this PR.
1. Import a SBOM file to the component page (Change the …
> fix(license): Fix attachment type when importing SBOM

- backend/src-common/src/main/java/org/eclipse/sw360/components/summary/ComponentSummary.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Refer issue: #1958 
- Some components have main licenses and default vendor
Send API request to Urls:
1. http://localhost:8080/resource/api/components
2. http://localhost:8080/resource/api/components?name={component_name}
3. http://localhost:8080/resource/api/components?type={component_type}
Have these fields in responses:
- id
- mainLicenseIds
- defaultVendor (when default vendor exist)
- componentType
Example Response:
```
{
"_embedded": {
"sw360:components": [
{
"id": "000fa58564cd41d0838eb6702c87f189",
"name": "CompName",
"componentType": "OSS",
"visbility": "EVERYONE",
"mainLicenseIds": [
"GPL-3.0+"
],
"setVisbility": true,
"setBusinessUnit": false,
"defaultVendor": {
"type": "vendor",
"url": "http://localhost:8080/group/guest/vendors",
"shortName": "sads",
"fullName": "dasd"
}, …
```
> Fix(Rest): Add more fields in get components response (support new Front-end)

- docker-compose.yml
When docker compose is used to deploy sw360, document_properties by default is empty, with no LAR data deployment. 
If a new deployment over the same data is done forcing compose to be down, the imported LAR files become lost and resources are not available anymore, creating broken webpages.
Treating document_libraries as a persistent volume solve the issue allowing better migration/development deploys.
> fix(docker): Restore document_properties volume

- libraries/datahandler/pom.xml
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
- third-party/couchdb-lucene/pom.xml
- Restore original couchdb-lucene portlet naming, no more 2.2.0-SNAPSHOT
- Restore couchdb.properties config in datahandler
- Add debug info for couchdb-lucene url handler
> Restore original portlet naming and configs

- rest/resource-server/src/docs/asciidoc/moderationRequests.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestExceptionHandler.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationPatch.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationRequestController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/Sw360ModerationRequestService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ModerationRequestSpecTest.java
The PR adds new HTTP verbs to endpoint `/moderationrequest` to modify ModerationRequests from REST API.
* Which issue is this pull request belonging to and how is it solving it?
> PR is related to issue #1849
* Did you add or update any new dependencies that are required for your change?
> No
Issue: #1849
Create several moderation requests to perform following actions on the endpoint.
- `PATCH` …
> feat(rest): modify moderation requests

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
Issue: #1994
```
$ curl 'https://sw360.org/api/users' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4NjMwNzk2NSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6Inp6ang3YXhKSWZWT3FMSFBRTTdldWhicjQwWSIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.GN0qYkxZ4_DccOHcjBCmFFuNdRhGZbL1HLl9XRCIX-VvhfuP9E8xpoj8FyPtKN6PQZoFRWDyGlB7YUDf0h3CpOTIhf2dL5sH2p6lnYviM-1r …
```
> feat(rest): update response API Listing users

- scripts/migrations/README.md
Issue: #2005 
From release 16.0.0 onwards python2 is not supported.All migration scripts form release 16.0.0 onwards are in python3.
> fix(update): Update the migration readme file

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/ecc/EccPortlet.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/ecc/view.jsp
- libraries/datahandler/src/main/thrift/components.thrift
Added pagination code so that release list are loaded 10 at a time on the ECC portlet
> * Which issue is this pull request belonging to and how is it solving it? (*#1985*)
> You can suggest reviewers here with an @ag4ums .
Have a lot of releases (>1000) and then click on ECC portlet
> feat(ECC):Added pagination to ECC release list

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
I have created a new endpoint URL for summary and administrative page info.
Issue: #1894 
resource/api/projects/{id}/summary/administration
ex: resource/api/projects/c109935d14e846c4afe03a8f3e97798b/summary/administration
> How …
> fix(rest): Added endpoint url for summary and administration page info

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
- backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- libraries/datahandler/src/main/thrift/projects.thrift
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
#1901 
No
Issue: 
#1901 
It can be tested using postman or any other supporting API platform.
URL : http://localhost:8080/resource/api/reports/projects?withlinkedreleases=true&mimetype=xlsx&mailRequest=true
Response : E-mail sent succesfully to the end …
> feat(rest): New end point for downloading project reports.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Issue: #1979
```
$ curl 'https://sw360.org/api/releases/3765276512' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY4NzIzMTYzOCwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6ImJUQ3ZHZWE2U1dyRWFwZThTR2o2RzJ2M3RSRSIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.Hj0HmAHlSMq9K9ilFH3kXs0LBI5ICCR6Z1PceIMqWp3zaa0xbfLIQLeH92jmyHqDUlGuzrXHidW796tUQnJzeVD2qNfZND …
```
> feat(rest): update response API Get a single release

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
> * This PR is to merge two components
Issue: #1957
> Create two components
> Get components ids from couch db and pass it to the api as a param
> add body of component with changes made in component (sample given below)
{
"type":"component",
"name":"Deemo comp 4",
"attachments":[      
],
"createdOn":"2023-05-17",
"componentType":"INNER_SOURCE",
"createdBy":"admin@sw360.org",
"subscribers":[      
], …
> feat(rest): new endpoint merge components

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
Issue: #1726 
Description : Apply sorting (from newest to oldest) on versions in drop down menu when inspecting a specific component. 
with newest meaning 'highest version'.  (i.e. NOT the last one added in sw360)
> fix(UI): Sorting release versions in drop down menu 

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Get single release by id:
http://localhost:8080/resource/api/releases/{release_id}
Expect: Response body contain clearing information with format
```
"clearingInformation": {
"externalSupplierID": "",
"additionalRequestInfo": "",
"evaluated": "",
"procStart": "",
"requestID": "",
"binariesOriginalFromCommunity": false,
"binariesSelfMade": false,
"componentLicenseInformation": false,
"sourceCodeDelivery": false,
"sourceCodeOriginalFromCommunity": false,
"sourceCodeToolMade": false,
"sourceCodeSelfMade": false,
"sourceCodeCotsAvailable": false,
"screenshotOfWebSite": false,
"finalizedLicenseScanReport": false,
"licenseScanReportResult": false,
"legalEvaluation": false,
"licenseAgreement": false,
"scanned": "",
"componentClearingReport": false,
"clearingStandard": "",
"readmeOssAvailable": …
```
> fix(Rest): Add clearing information in release response (New Front-end)

- clients/client/src/main/java/org/eclipse/sw360/clients/rest/SW360ReleaseClient.java
- clients/client/src/test/java/org/eclipse/sw360/clients/rest/SW360ReleaseClientIT.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Modified code such that while searching for releases using externalIds via Rest endpoint, encoding is skipped
> * Which issue is this pull request belonging to and how is it solving it? (#1659)
@ag4ums 
Search for releases using externalId such that in key-value pair there are values that usually encodes to special characters(eg: %40)
> fix(Rest): Allowing search for externalIds without encoding

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src/src-components/src/main/java/org/eclipse/sw360/components/ComponentHandler.java
- libraries/datahandler/src/main/thrift/components.thrift
- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
#1855 
No
Issue: 
It can be tested using Rest client (Postman) with following URL and sample response.
URL : http://localhost:8080/resource/api/reports?withlinkedreleases=true&mimetype=xlsx&mailrequest=true&module=components …
> feat(rest) - Rest API for downloading components report.

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/edit.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/obligationsEdit.jspf
1. The comment and status fields of License Obligations in a project will be saved on editing.
2. On change in these 2 fields, their data is stored in the local storage which is then restored back on re-opening the edit page.
3. The local storage is clearing on submitting the project edit form.
Issue: #2004 
Screenshot:
> feat(ProjectObligationsEdit): Save comment and status fields on edit

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
I rename "Initial use scan" to "Internal use scan".
> * Did you add or update any new dependencies that are required for your change?No
Issue: #2034 
1: Login sw360
2: Go to project tab.
3: click on Attachments tab
4: click on attachments type.
> Have you …
> fix(UI):word correction of Initial use scan in attachment type

- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ProjectExporter.java
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java
Now we can the project id and release id in the excel exported on clicking "Export Spreadsheet" button available on the projects listing and project details page. 
Issue: #2041 
**Projects listing page: (Projects only option selected)**
**Project details page: (Project with linked releases option selected)**
> feat(ExportSpreadsheet): Add project and release ID to the exported excel

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
> * Which issue is this pull request belonging to and how is it solving it? #2042 
Issue: Component name search over endpoint with prefix ++ is returning an empty list
@ag4ums
Search for any component with name such as 'Angular++' over the rest endpoint
> fix(Rest): Allowing search for components without encoding

- rest/resource-server/src/docs/asciidoc/components.adoc
Found a merge conflict in doc. Removed the conflict notation line.
> fix(doc): remove merge conflict notation

- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Request url: http://localhost:8080/resource/api/releases/{releaseId}/reloadFossologyReport
Expected:
- Success:
```
HTTP status: 200
{
"_links": {
"self": {
"href": "http://localhost:8080/resource/api/releases/{releaseId}/checkFossologyProcessStatus"
}
},
"message": "Re-generate FOSSology's report process for Release Id : {releaseId} has been triggered."
}
```
- Release had another fossology process
HTTP status: 406
```
{
"_links": {
"self": {
"href": "http://localhost:8080/resource/api/releases/{releaseId}/checkFossologyProcessStatus"
}
},
"message": "Another FOSSology Process for Release Id : {releaseId} is already running. Please wait till it is completed."
}
```
- Reload report not available (Fossology process of release has never been run before):
HTTP status: 500
```
{
"message": …
```
> New endpoint allow to re-generate fossology report (New Frontend)

- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/tools/OSADLObligationConnector.java
Some entries from current OSADL obligations format were missing:
* **YOU MUST**
* **YOU MUST NOT**
Reference: Issue #1809
> Add missing obligation rules

- scripts/migrations/056_dataReduction.py
- scripts/migrations/README.md
Issue: #1937 
Description: this migration script will delete the Releases that are not linked to any project and does not have any clearing results and will also delete the components that does not have any releases.
Note: before running the script, enter the date in bufferDate variable.
This date will collect the releases and components that were created before or on this date.
> fix(db): Data quality and reduction of storage

- libraries/datahandler/src/main/thrift/components.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Issue: #2062
```
curl 'https://sw360.org/api/components/17653524' -i -X PATCH \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic …
```
> feat(rest): Update Component with attachment

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: #2030 
Description: GET request will get all releases of license clearing.
> feat(rest): listing license clearing info of a project.

- Dockerfile
- pom.xml
- third-party/couchdb-lucene/pom.xml
- third-party/couchdb-lucene/src/main/java/com/github/rnewson/couchdb/lucene/DatabaseIndexer.java
- third-party/couchdb-lucene/src/main/java/com/github/rnewson/couchdb/lucene/IndexKey.java
- third-party/couchdb-lucene/src/main/java/com/github/rnewson/couchdb/lucene/JSONErrorHandler.java
- third-party/couchdb-lucene/src/main/java/com/github/rnewson/couchdb/lucene/LuceneServlet.java
- third-party/couchdb-lucene/src/main/java/com/github/rnewson/couchdb/lucene/Main.java
- third-party/couchdb-lucene/src/main/java/com/github/rnewson/couchdb/lucene/PathParts.java
- third-party/couchdb-lucene/src/main/java/com/github/rnewson/couchdb/lucene/util/ServletUtils.java
- third-party/couchdb-lucene/src/main/java/com/github/rnewson/couchdb/lucene/util/Utils.java
Due to old tomcat available in Liferay, we need use javax.servlet and jetty series 10 for couchdb-clucene.
Updated Dockerfile to fix Liferay breakage on Java 11.0.20 release
> fix(lucene): Use old javax.servlet

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
Issue: #2037
- use API create component
*  If the inputted businessUnit is null, set businessUnit = user's department
*  If the inputted businessUnit is not null, set businessUnit = inputted businessUnit
Must:
> fix(rest): API create component's businessUnit is always set as the user's department

- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
- Request URL: http://localhost:8080/resource/api/releases/{releaseId}/spdxLicenses
- Request method: POST
- Example request body:
```
{
"mainLicenseIds" : [ "ML1", "ML2" ],
"otherLicenseIds" : [ "OL1", "OL2" ]
}
```
- Expected: License ids are added into main license and other license field of release
> feat(REST): New endpoint to write SPDX license info into release (New Frontend)

- backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMExporter.java
- backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Add handling of CPE fields during import and export of CycloneDX files.
Issue: #2072 
To test:
- import an SBOM in CycloneDX format including CPE information
- export a project with CPE information set
Must:
> feat(CycloneDX): support CPE in import and export

- rest/resource-server/src/docs/asciidoc/licenses.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
Issue: #2064 
Create a new rest endpoint to delete all license information in admin tab
1: http://localhost:8080/resource/api/licenses/delete
2: login with admin user and create token 
3: use token in postman. 
> How should these …
> fix(rest):new endpoint to delete all license information in admin tab

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Procedure:
- From GUI create a release with Component type = OSS
- Edit Ecommercial Details information of that Release
- Send a GET request to: https://localhost:8080/resource/api/releases/{releaseId}
Expected:
- Responsed release contains **sw360:cotsDetails** in **_embedded**
Must:
> Fix(REST): Add COTS details information when fetch a single release that has component type COTS

- Dockerfile
Updated maven env to current patch version 3.9.3 => 3.9.4
I didn't open an issue as it's a very minor change. I'd be happy to open one if it is still necessary.
No.
Issue: 
`./docker_build.sh` was failing because on 404 on …
> upd(docker): update maven version

- pom.xml
- rest/resource-server/pom.xml
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/OpenAPIPaginationHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationRequestController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/main/resources/application.yml
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- rest/resource-server/src/test/resources/application.properties
Use `org.springdoc.springdoc-openapi-ui` to generate openAPI docs as well as swagger UI.
New dependencies:
* [org.springdoc.springdoc-openapi-ui:1.7.0](https://central.sonatype.com/artifact/org.springdoc/springdoc-openapi-ui/1.7.0)
* [org.springdoc.springdoc-openapi-hateoas:1.7.0](https://central.sonatype.com/artifact/org.springdoc/springdoc-openapi-hateoas/1.7.0)
* [org.springdoc.springdoc-openapi-security:1.7.0](https://central.sonatype.com/artifact/org.springdoc/springdoc-openapi-security/1.7.0)
* …
> docs(rest): generate OpenAPI docs for ProjectController

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
#2023 
No
Issue: 
Use postman for testing.
Sample URL : 
http://localhost:8080/resource/api/reports?withlinkedreleases=true&mimetype=xlsx&mailrequest=true&module=components …
> feat(rest) asynchronous end point for downloading reports.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
```
curl 'https://sw360.org/api/releases' -i -X POST \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cC …
```
> feat(rest): Update API create Release with LinkedRelease

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/moderation/ModerationPortlet.java
create moderation and go to Requests / Open Moderation Requests and select a project clearing request then we get the error message.
closes #2081 
1:create Moderation request
2:Go to Request tab
3:open the any moderation …
> fix(UI): Added code to load moderation documents in request tab

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
- Send PATCH request to http://localhost:8080/resource/api/releases/{releaseId} with body
```
{
"attachments": [
{
"attachmentContentId": "{attachment Id in sw360}",
"sha1": "a56456d2f7ca6d0fa58dfeee3e442cea9130d5ca",
"attachmentType": "COMPONENT_LICENSE_INFO_XML",
"createdOn": "2022-08-19",
"filename": "JUL_to_SLF4J_bridge_1.7.32.spdx.rdf",
"checkedComment": "",
"checkStatus": "NOTCHECKED",
"createdBy": "admin@sw360.org",
"createdComment": "",
"createdTeam": "DEPARTMENT"
}
]
}
```
Expected:
- If **attachmentContentId** is existing in sw360: release updated successfully <200>
- If **attachmentContentId** is not existing in sw360: release updated fail <404>
> feat(rest): Update release with attachment info

- rest/resource-server/src/docs/asciidoc/packages.adoc
Issue #2097 
Copyright text from the REST API docs is removed
> fix(rest): Removed the copyright text from REST API docs

- frontend/sw360-portlet/src/main/resources/META-INF/resources/css/main.scss
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/ajax/linkedReleaseInNetwork.jsp
- Add following option to **/etc/sw360/sw360.properties** file **enable.flexible.project.release.relationship=true**
#2100 
- When user click **Add release** button to add a release to dependency network, the GUI will be broken as bellow
Steps:
- User click edit project
- User select a release and click
Expected:
- The GUI will work normally
> fix(GUI): Fix edit dependency network GUI broken

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/AttachmentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/changelog/ChangeLogController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
Added OpenAPI docs using springdoc for:
- `/attachments`
- `/changelog`
- `/clearingrequest`
It is continuation of #2071
@KoukiHama 
@heliocastro 
* The Swagger UI for the API should be available at http://localhost:8080/resource/api/swagger-ui/index.html
* Read the documentation for the endpoints.
* OpenAPI JSON file should be available at http://localhost:8080/resource/api-docs
> docs(openapi): add docs for attachment

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/search/SearchController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
Added OpenAPI docs using springdoc for:
- `/vendors`
- `/users`
- `/search`
It is continuation of #2071
@KoukiHama 
@heliocastro 
* The Swagger UI for the API should be available at http://localhost:8080/resource/api/swagger-ui/index.html
* Read the documentation for the endpoints.
* OpenAPI JSON file should be available at http://localhost:8080/resource/api-docs
> docs(openapi): add docs for vendor, user, search

- rest/resource-server/src/docs/asciidoc/licenses.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
Issue: #2111 
1: login sw360 with admin user
2: /resource/api/licenses/import/SPDX
Must:
> fix(rest): create new endpoint for import spdx information in admin tab

- libraries/datahandler/src/main/thrift/sw360.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
- Send GET request to
+ http://localhost:8080/resource/api/components/usedBy/{componentId}
+ http://localhost:8080/resource/api/releases/usedBy/{releaseId}
- Expected:
+ The response will contain number of restricted projects (of current user) :
```
"sw360:restrictedResources" : [ {
"projects" : {number_of_restricted_projects}
} ]
```
> feat(REST): Add restricted project counter for component and release usedBy API

- README_DOCKER.md
- docker_build.sh
Hello, community. 
I am a new contributor for sw360. When I tried to build sw360 by `docker-compose`, I found the issue that I couldn't set the CVE Search server. So I added an option for a docker build script.
This option's input changes the `cvesearch.properties`.
This is a very minor update, however users can it without changing manually.
* Add `--cvesearch-host` option for `docker_build.sh`.
For doing test this option, you can use your own CVE server, …
> feat(docker): Add option to specify cvesearch.host at build time

- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/LicsExporter.java
- rest/pom.xml
- rest/resource-server/src/docs/asciidoc/licenses.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
Issue: #2105 
URL:  /resource/api/licenses/downloadLicenses
1: user should have admin access.
2: Go to admin tab.
3: download licenses archive. …
> fix(rest): New endpoint to download license archive files in admin page

- rest/resource-server/src/docs/asciidoc/vulnerabilities.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/Sw360VulnerabilityService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VulnerabilitySpecTest.java
#2013 
No 
End Point : http://localhost:8080/resource/api/vulnerabilities/trackingstatus/8b3aa2f81a764fb482d6391516d153db
Sample Response : 
{
"_embedded": {
"sw360:releaseClearingStatusDatas": [
{ …
> feat(rest): API to get vulnerability tracking status

- scripts/migrations/057_closedModReqStats.py
- scripts/migrations/058_deleteClosedModReq.py
- scripts/migrations/README.md
> fix(db): clean-up closed moderation requests.

- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
(Release has 1 attachment with type Component license information (XML))
1. Send GET request to: http://localhost:8080/resource/api/releases/{releaseId}/assessmentSummaryInfo
2. Example Response:
- Release has an attachment with type Component license information (XML) and attachment has assessment summary info
**Status 200**
```
{
"GeneralAssessment": "GeneralAssessment",
"CriticalFilesFound": "None",
"#text": "\n  ",
"AdditionalNotes": "AdditionalNotes",
"UsageRestrictionsFound": "None",
"ExportRestrictionsFound": "None",
"DependencyNotes": "None"
}
```
- Release has an attachment with type Component license information (XML) but attachment does not have assessment summary info
**Status 204**
- Release has more or less than 1 attachment with type Component license information (XML) …
> New endpoint allow load assessment summary information of release (New Frontend)

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Issue:  #2136 
Using postman. 
URL : http://localhost:8080/resource/api/releases/caf6ff2180064d9faaebe8d7a7cd5ae2/attachments
Sample Response in the following attachment : 
> …
> feat(bug) : Releases attachment download issue fix

- backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Closes: #2137 
> Import an SBOM and then pick up any of the component from that SBOM.
> Change the fields of that component particular component and again import the same SBOM.
> fix(importCDX): Resolved unnecessary update of component fields

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/PackageSpecTest.java
Issue: https://github.com/eclipse-sw360/sw360/issues/2066#issuecomment-1690888032
- Execute API create new Package: 
```
$ curl 'https://sw360.org/api/packages' -i -X POST \
-H …
```
> fix(Package): Can't create a new Package by API

- rest/pom.xml
- rest/resource-server/src/docs/asciidoc/licenses.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
Create a new endpoint to upload license with external IDs combination in admin tab.
Issue: #2122 
URL : /resource/api/licenses/upload
1: Attach the license file.
2: checkout "Overwrite if externals IDs match"
3: checkout if IDs …
> fix(rest): Added new rest endpoint for upload license in admin tab.

- rest/resource-server/src/docs/asciidoc/licenses.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
You will import SPDX information in admin license.
Issue: #2113 
1: login sw360 with admin user
2: /resource/api/licenses/import/OSADL
> Have you implemented any additional …
> fix(rest): create new endpoint for import OSADL information in admin.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Issue: 　#2078
Performance Issues with Name Search via API 
> You can suggest reviewers here with an @ag4ums 
Using the Rest API of Release, "Acquisition of all records" and "Filtering by name" are executed, and confirm that there is no difference in the response JSON before and …
> fix(rest) : Modifications to improve API GET result speed for name search

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/PackageSpecTest.java
> @KoukiHama 
- Execute API create new Package: 
```
$ curl 'https://sw360.org/api/packages' -i -X POST \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY5NzQ0MzY4OSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6IlhKQVFFQkZyeGxieFJONUFRSDU3dGtfYzJkbyIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.ZueR84mNgqUULCYXTkFSSX4GGb01nPFcrINisAE5x8DCjdH …
```
> fix(package): Create package by API can't link release

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
Space character and "+" character in names is getting converted to "%20". This issue has been fixed by replacing "%20" to " " before searching for the component in the repository.
Closes #2115
> fix(REST):GET Component endpoint failing for names with space

- rest/resource-server/src/docs/asciidoc/licenses.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
Issue: #2146 
1: Login with Admin user.
Sample URL : http://localhost:8080/resource/api/licenses/addLicenseType
Must:
> fix(rest): Create new endpoint for LicenseType in admin tab

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Add OpenAPI docs using springdoc for ComponentController `/component`
Continuation of https://github.com/eclipse-sw360/sw360/pull/2071
**Note:** The properties `setVisbility` and `setBusinessUnit` were documented in the SpringDoc. However, they appear to be artifacts of thrift. Please let me know if they should exist and I will revert the changes.
@heliocastro
@KoukiHama
@ag4ums
* The Swagger UI for the API should be available at …
> docs(openapi): add OpenAPI doc for ComponentController

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: closes #2094 
Description: updated the existing attachmentUsages endpoint with more fields in response structure.
> feat(rest): endpoint to get attachmentUsages for a project.

- rest/resource-server/src/docs/asciidoc/licenses.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
- Update response for API single License
- Add rest docs for API Create License
```
$ curl 'https://sw360.org/api/licenses/Apache-2.0' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY5ODgyODgyNCwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6Inh4Z1RBZ2pIcUFfZkpuS3EwVmkxQXVFS0ZIZyIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.e6mw__gXV5fsQ4GkcG-RIlKjywv …
```
> fix(licenses): Update Response for api single license and add rest api docs create License

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- libraries/datahandler/src/main/thrift/projects.thrift
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: closes #2162 
Description: 
This endpoint will give the count of the license clearing count i.e. the data for the highlighted column in project table.
> feat(rest): endpoint to get license clearing count for a project

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
No
Issue: #2135 
Can be tested using Rest client - Postman. 
Sample URL  : http://localhost:8080/resource/api/projects/16f6d03ada424dea81c86fabdab3ee35/summaryAdministration …
> feat(rest) : Adding or Modifying fields to project summaryadministration API

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
Modified code such that while listing releases by externalIds using key-value pair, value is not required
- Which issue is this pull request belonging to and how is it solving it? (https://github.com/eclipse-sw360/sw360/issues/2207)
@ag4ums
> fix(Rest): Allowing search for releases using externalIds

- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Issue: #2195 
Sample URL and response as follows in the screenshot. 
URL : http://localhost:8080/resource/api/components?name=comp&page=0&page_entries=20&luceneSearch=true&sort=n …
> fix (rest) : Rest API for component search by Lucene search

- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
1. Add OpenAPI docs for `/releases` endpoints.
2. Add the missing AsciiDoc for getting releases by external ID.
3. Replace deprecated exception `HttpMessageNotReadableException` with `HttpClientErrorException`.
Continuation of https://github.com/eclipse-sw360/sw360/pull/2071
@heliocastro
@KoukiHama
@ag4ums
* The Swagger UI for the API should be available at http://localhost:8080/resource/api/swagger-ui/index.html
* Read the documentation for the endpoints.
* …
> docs(api): add OpenAPI docs for releases

- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/VulnerabilityController.java
1. Add OpenAPI docs for `/vulnerabilities` endpoints.
2. Replace deprecated exception `HttpMessageNotReadableException` with `HttpClientErrorException`.
Continuation of https://github.com/eclipse-sw360/sw360/pull/2071
@heliocastro
@KoukiHama
@ag4ums
* The Swagger UI for the API should be available at http://localhost:8080/resource/api/swagger-ui/index.html
* Read the documentation for the endpoints.
* OpenAPI JSON file should be available at …
> docs(api): add OpenAPI docs for /vulnerabilities

- scripts/migrations/059_repair_broken_releasevulnerability.py
- scripts/migrations/060_migrate_project_dependency_network.py
- scripts/migrations/README.md
The numbering of migration scripts is duplicated: duplicate 054 and 056 files
- **Renumbering scripts:**
056_migrate_project_dependency_network.py -> 060_migrate_project_dependency_network.py
054_repair_broken_releasevulnerability.py -> 059_repair_broken_releasevulnerability.py
-  **Correct file name in README.md file**
> fix(script): Fix incorrect numbering for migration scripts

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/spdx/edit.jspf
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/releases/spdx/view.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/attachmentsDetail.jsp
Issue: #2226 
-  Fix error of hiding attachment table content when click on header
-  Add collapse expand icons for SPDX document sections.
- Add configuration `spdx.document.enabled = true` to /etc/sw360/sw360.properties
- Release contains several attachments
Procedure:
- Select a release to view detail
- Select attachments tab
- Click on sort icons
Expected:
- Attachment will be sort successfully and table body will not be hidden
Procedure:
- Select a release to view detail
- Select SPDX document tab
Expected:
- SPDX document sections will have expand collapse icon on header as below
> fix(Table): Fix error of hiding attachment table content when click on header

- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/LicenseHandler.java
- backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
- libraries/datahandler/src/main/thrift/licenses.thrift
- rest/resource-server/src/docs/asciidoc/licenses.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
- Run command
```
$ curl 'https://sw360.org/api/licenses/MIT/obligations' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTcwMjM1MjAyNSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6IkxxSGFjbU5QVThlcWlEMnNpVTFlWGZ3bHB3USIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.gadnfJIwnx4D2a77wXBkZCUKldzOTnQNul4v2slHSkAePjTe7HqA4ktRQ4UoWWeb_7XRy2kvfZIEkc4MmiN7mIxKIB2PYNPHyPiDy6EO9VJPO …
```
> feat(license): Listing obligations by license

- rest/resource-server/src/docs/asciidoc/api-guide.adoc
- rest/resource-server/src/docs/asciidoc/schedule.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/ScheduleAdminController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/Sw360ScheduleService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ScheduleSpecTest.java
Closes #2237 
http://localhost:8080/resource/api/schedule/unscheduleAllService
Must:
> feat(rest): Create new endpoint to cancel all scheduled services.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
Revert changes done to `ReleaseController::searchByExternalIds` query parameter parsing.
1. Query releases by external ID.
2. Check the OpenAPI doc for search releases by external ID endpoint.
Must:
> fix(release): revert external id query parsing

- rest/resource-server/src/docs/asciidoc/users.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
- **Procedure**:
Send GET request to: [http://localhost:8080/resource/api/users/profile](http://localhost:8080/resource/api/users/profile)
- **Expected**
The response will show all information of requesting user.
```
{
"email": "admin@sw360.org",
"userGroup": "ADMIN",
"externalid": "sw3607",
"department": "DEPARTMENT",
"wantsMailNotification": true,
"notificationPreferences": {
"releaseCONTRIBUTORS": true,
"componentCREATED_BY": false,
"releaseCREATED_BY": false,
"moderationREQUESTING_USER": false,
"projectPROJECT_OWNER": false,
"moderationMODERATORS": true,
"releaseSUBSCRIBERS": true,
"componentMODERATORS": true,
"projectMODERATORS": false,
"releaseROLES": true,
"componentROLES": true,
"projectLEAD_ARCHITECT": true,
"componentCOMPONENT_OWNER": true,
"projectSECURITY_RESPONSIBLES": false, …
```
> feat(User): Add new endpoints to get/update requesting user profile

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/packages/SW360PackageService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Issue: #2252
Pre-condition: Package Pack1 is an orphan package, and Pack1 is linked to project P1.
Procedure: Perform rest API with:
Method: PATCH
URL: "http://:/resource/api/projects/${Id of P1}/unlink/packages"
Data in the body: ["${Id of Pack1}"]
Expected Output: Return status 201 Created. Pack1 is unlinked to project P1.
Pre-condition: Exist release R1 without any package. Package Pack1 is an orphan package.
Procedure: Perform rest API with:
Method: PATCH
URL: "http://:/resource/api/releases/${Id of …
> fix(package): Fix issues API for package

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
- Checked ```Apache-2.0``` of license is ```false``` 
```
$ curl 'https://sw360.org/api/licenses/Apache-2.0' -i -X PATCH \
-H 'Authorization: BearereyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY5OTQxOTQ0OSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6ImlyaWwxUDF5Rm1uY2kzaThyNlROWFZJemVvTSIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.ggC1M326qK …
```
> feat(license): Fix Update License when checked field is false

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
- frontend/sw360-portlet/src/main/resources/content/Language_zh.properties
Clearing Request will not be created if a project has 1 or more linked releases that do not have **SRC** type attachment, 
Issue: #2259 
Closes: #2259 
> Create a CR for a project.
Must:
> feat(CR): Disable Clearing Request creation for the projects which have linked releases without SRC type attachment

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Additional, if else condition has been added in code to handle the case when user try to import the SBOM and lacks import permission.
Closes: #2126
> fix(rest): error handling when user dont have sufficient import permission

- frontend/sw360-portlet/src/main/resources/sw360.properties
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
> chore(package-portlet): package-portlet enabled for default installation

- backend/src/src-schedule/src/main/java/org/eclipse/sw360/schedule/timer/ScheduleConstants.java
Issue: 
The default value for departmentInterval was causing a division by zero in Scheduler.getNextSyncDate
There is a properties file in the final scheduler jat that is supposed to be read, but this seems also to be broken, so  scheduler is falling back to the default value in …
> fix division by zero for department scheduler

- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/ModerationHandler.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
- backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationRequestRepository.java
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
- libraries/datahandler/src/main/thrift/moderation.thrift
- rest/resource-server/src/docs/asciidoc/moderationRequests.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationRequestController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/Sw360ModerationRequestService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ModerationRequestSpecTest.java
New endpoint `/moderationrequest/mySubmissions` to get moderation requests submitted by the user.
Also, refactor the `ModerationRequestController` to use `ModerationRequestController.getModerationResponseEntity()`
Closes #1849
Issue: #1849
1. Check the docs for the new endpoint.
2. Check moderation request matches the "My Task Submissions" list from SW360 Homepage.
Must:
> feat(api): new endpoint /mySubmissions

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: Closes #2275 
Description: get license obligations for the project from license database.
Steps to test:
- create a release and a project to which the release will be linked
- add a CLX attachment to release, having status checked/accepted
- in attachment usages of project enable the license info checkbox for the release(having attachment)
- run the new endpoint to get the list of obligations from the license database
> feat(obligation): endpoint to list license obligations from license db.

- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
- frontend/sw360-portlet/src/main/resources/content/Language_zh.properties
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
- libraries/datahandler/src/main/thrift/components.thrift
- libraries/datahandler/src/main/thrift/sw360.thrift
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ReleaseExporter.java
- libraries/exporters/src/main/java/org/eclipse/sw360/exporter/helper/ReleaseHelper.java
Clearing Request for a project should have a state **Sanity Check** for the clearing team to make sure that the CR for a project is eligible to be accepted. Clearing admin can change the CR state from `New` to `Sanity Check`. They can navigate to the **License Clearing** tab in the project portlet and select **Export Project with linked releases** option.
This will download an excel file containing all previous info with 2 additional columns:
**Source Code Downloadurl** - contains the Source Code Downloadurl for each linked releases 
**SRC/SRS Attachments** - contains the filenames of SRC and SRS type attachments for each linked release.
Clearing Team can go through this data to make sure CR is eligible to be accepted or not.
Closes: #2287
> feat(CR): Create a new Clearing Request state Sanity Check to perform sanity check before accepting a project.

- backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Now, the CycloneDX import summary message will correctly display the list of invalid packages.
closes: #2341
> fix(importSBOM): Remove the invalid characters appearing in import summary message for invalid packages list

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: Closes #2301 
Description: 
This new endpoint will list license obligation data for the given project.
> feat(obligation): list license obligation table data 

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> fix(rest) : attachment usage type fix in response

- rest/resource-server/src/docs/asciidoc/users.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/UserSpecTest.java
1. Create endpoint to list all user's tokens.
2. Create endpoint to create new user's token.
3. Create endpoint to revoke user's token by its name.
**1. Endpoint to list all user's tokens**
- Send GET request to http://localhost:8080/resource/api/users/tokens
- Response will list all Rest API token of the requesting user. (Status code 200).
**2. Endpoint to create new user's token**
- Send POST request to http://localhost:8080/resource/api/users/tokens with request body:
```
{
"name" : "MyToken3",
"expirationDate" : "2023-12-29",
"authorities" : ["READ", "WRITE"]
}
```
- Response will contain created token. (Status code 201).
- A new Rest API token will be created for requesting user.
- You can use this created token to authenticate API request by setting Authorization header in this …
> Feat(User): Create new endpoints to Create/Revoke/List rest API token for users

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
- Other licenses information is not be presented in release's response
Release must have at least one license in other licenses field
Send GET request to get single release: http://localhost:8080/resource/api/releases/{release_id}
Response will contain other licenses of release in embedded field with the format:
```
"sw360:otherLicenses" : [ {
"OSIApproved" : "NA",
"FSFLibre" : "NA",
"checked" : true,
"shortName" : "BSD-3-Clause",
"fullName" : "BSD-3-Clause",
"_links" : {
"self" : {
"href" : "https://sw360.org/api/licenses/BSD-3-Clause"
}
}
}, {
"OSIApproved" : "NA",
"FSFLibre" : "NA",
"checked" : true,
"shortName" : "MIT",
"fullName" : "MIT",
"_links" : {
"self" : {
"href" : "https://sw360.org/api/licenses/MIT"
}
}
} ]
}
```
> fix(Release): Add embedded other licenses in release response

- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/dependencyNetwork.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/expandCollapse.js
Issue: #2390
- This PR will reduce effect of expandCollapse.js file, which is used to toggle collapse, expand icon. Then the issue will be solved
- Fix bug close icon is shown incorrectly (should be "x" icon)
Refer to Issue: #2390
Ensure that the collapse, expand icon are toggled correctly in Project, Release, Component, Package detail tabs
Must:
> fix(Project): Fix bug Expand Next Level and Collapse All button are hidden when click on sort icon

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
If a project is not modified, modifier email is null. Check the email before trying to embedd the user object.
@smrutis1
Fetch project summary for a new project using `/resource/api/projects/{id}/summaryAdministration` endpoint.
Must:
> fix(api): check project modifier before embedding

- backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Now during the SBOM import, If we found a component already exists' s in SW360, then we are going to use the existing component name. After this we will search for the release in sw360 that we want to create using the SBOM, and if we found the release we are going to use the same release.
Closes: #2220
> fix(importCDX): Resolve duplicate release creation during SBOM import

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/search/SearchController.java
Provide name for the `typeMasks` parameter in `/search?searchText=hello&typeMasks=document` as it is `Optional` type.
This causes spring to throw following exception:
```
Name for argument of type [java.util.Optional] not specified, and parameter name information not available via reflection. Ensure that the compiler uses the '-parameters' flag.
```
@smrutis1 @ag4ums 
Hit the search endpoint.
Must:
> fix(api): provide typeMasks name as Optional type

- backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/attachmentsDetail.jsp
- frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/importBom.jspf
- frontend/sw360-portlet/src/main/resources/content/Language.properties
- frontend/sw360-portlet/src/main/resources/content/Language_ja.properties
- frontend/sw360-portlet/src/main/resources/content/Language_vi.properties
- frontend/sw360-portlet/src/main/resources/content/Language_zh.properties
A package having a clashing state where it does not have a source/VCS in SBOM but is linked to source release in SW360 will now get linked to a project along with its release as expected.
**Note**: Corresponding UI Changes in the Import Status dialog box have not been implemented due to migration to React. 
Closes #2387
> fix(importCDX): Packages without VCS in SBOM having VCS in SW360 are not getting linked to project

- frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
Clearing the existing license info when adding the new license info from a CLI file
> * Which issue is this pull request belonging to and how is it solving it?#2412
> fix(Release): Updating the license overview in the summary page

- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/docs/asciidoc/packages.adoc
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/packages/PackageController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: closes #2330 
Description: decoding the query parameters for rest endpoints.
How to test:
- send the query parameters in encoded format for rest endpoints.
Test endpoints like:
- search components/projects/releases by name
- search components/projects/releases by externalIds
- search projects by tag
Screenshots:
> fix(rest): url decoding.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Now, if we try to import the SBOM on a already existing project in SW360 and if this SBOM contains different name and version information than the project which is present on SW360, then were handling this case properly in showing the relevant message to the user.
Closes: #2411
> fix(REST): Improve error message handling for CycloneDX sbom import using REST API

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Some of the data in the bug templating are outdated and mentioning specific information that is no longer valid.
Refactor to match with new docker setups and modern SW360 state
Issue: 
> How should these changes be tested by the …
> chore(templates): Update outdated bug/issue templates

- backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
This pull request addresses an issue where the import-summary-message inaccurately reports the count of linked packages and releases in a SW360 project due to the presence of duplicate components in the SBOM.
closes: #2425
> fix(importCDX): Resolve incorrect package/release count in import summary

- rest/resource-server/src/docs/asciidoc/licenses.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
- Feature Update Whitelist in License Page
- Run command
```
curl 'https://sw360.org/api/licenses/Apache-2.0/whitelist' -i -X PATCH \
-H 'Authorization: BearereyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTcwNDg4MzY5OSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6ImRJc0ZOSml3ckhHRjE1ZHJrZzBCX1JSX21rVSIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.iuADty2_ZFsM1ETIqAJI …
```
> feat(license): Update Whitelist for License

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: Closes #2356 
Run the existing attachment usage endpoint with one of the filter options as parameter.
ex. http://localhost:8080/resource/api/projects/df84ec3a9eba4e67a5b8fcf19c3d099e/attachmentUsage?filter=withSourceAttachment&transitive=true
It will return the releases having source type attachments.
> feat(rest): filter releases for attachment usages page in project

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationRequestController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ModerationRequestSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Ignore common fields while returning additions and deletions in a Moderation Request.
Also, ignore the revision field for a moderation request (CouchDB field) but add "id" field to project allowing for easy identification.
Fixes #2417
Try to create some moderation requests and get them via REST API.
The additions/deletions should not contain any fields which have same value.
The boolean fields are still there …
> feat(moderation): ignore common fields

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/Sw360ModerationRequestService.java
1. Throw `HttpClientErrorException` instead of `InvalidParameterException` to get correct status code instead of 500.
2. Also, change the status code from 400 to 409 incase the moderator is last moderator.
1. Create a moderation request.
2. Use REST API to unassign moderators from the MR.
3. Upon removal of last moderator, endpoint should return status code 409 instead of 500.
Must:
> fix(api): throw 409 if last moderator

- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageDatabaseHandler.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/PackageRepository.java
- backend/src/src-packages/src/main/java/org/eclipse/sw360/packages/PackageHandler.java
- libraries/datahandler/src/main/thrift/package.thrift
- rest/resource-server/src/docs/asciidoc/packages.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/packages/PackageController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/packages/SW360PackageService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/PackageSpecTest.java
New endpoint called "Search Packages" has been created. It enables the user to search for packages through name, version, purl or packageManagers and also perform more specific searches by combining these parameters using the & operator.
Closes #2445
> feat(REST): Search package by purl and version

- backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
closes #2428
Now when an SBOM is imported containing a duplicate pkg, the existing pkg's linked release would not be modified. 
For example : 
If this an SBOM that contains a duplicate pkg but different VCS : 
The existing pkg : **chartjs.chartjs-color-string (0.6.0)** along with it's release is linked to the project along with the new release that is created from the SBOM. 
With this change the projects that were using the particular pkg won't be affected and there won't be an inconsistency in them.
> fix(importCDX) : Fix package's linked release updation when an SBOM is imported

- backend/src-common/src/main/resources/sw360.properties
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: 
Closes #2256 
URL : 
http://localhost:8080/resource/api/reports?withlinkedreleases=false&module=projects&projectId=bf1570a235414de486eb1043d4b0c0a8
Response : 
After …
> feat(rest) : Remove mail-request parameter and read from config file while downloading reports.

- .github/workflows/build_and_test.yml
Rest test with Java 17 will not work until the new rest interfaces are set.
The new rest code can't be set until the Java 17 is already set on main.
So, the tests need to be reenabled after the rest commits arrive.
> fix(test): Disable rest test to avoid chicken and egg integration

- .github/pull_request_template.md
PR's should not be assigned to a single company or a single project or owner.
> fix: Remove wrong placed copyrights on commit template

- backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Currently, when an import fails due to an invalid PURL (Package URL) present in the SBOM, the error message lacked details about the failed component and gives a null exception. Now the components having malformed PURL are listed for the users to know where it failed.
Closes : #2451 
Before : 
Now we get info of the failed component :
> fix(importCDX):Improve error message when PURL is invalid

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Fixes the issue where linking of projects was not possible when projects passed in the request body did not have any linkedProject to them. (couchDB project document did not have a linkedProject object). 
Endpoint : http://localhost:8080/resource/api/projects/{src_project_id}/linkProjects
Request body : array of project ids to be linked.
closes : #2472
> fix(rest): Fix internal server error with 500 status code for link project to projects endpoint.

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: #2475
Rest endpoint to update license obligations of project.
Pass a map having key as Obligation Title and value as Obligation Status and Obligation Comment which you want to update.
How to test:
run the endpoint to update license obligations: 
http://localhost:8080/resource/api/projects/036452503f984171971de77c8f4de185/updateLicenseObligation
> feat(obl): rest endpoint to update license obligations of project

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/Sw360ModerationRequestService.java
Closes: #2490, #2518 
###Description
Upon clicking the "Accept Request" button for a moderation request, the REST API response returns a 202 (Accepted) status. However, the database is not being updated with the proposed changes. For example, if a project page is edited and a moderation request is created, accepting the proposed changes does not update the project page with the new values; it still shows the old values.
> * Which issue is this pull request belonging to and how is it solving it? …
> fix(rest): modified accept request to see the proposed changes in user to moderation request rest Api.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
closes : #2595 
500 internal server error fixed if the project document is missing the **linkedProjects** field.
> fix(rest): Add null check for linkedProject field if it is empty.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
If a clearing request has been REJECTED or CLOSED, "requestClosedOn" field will be added in the get clearingById endpoint response body.
http://localhost:8080/resource/api/clearingrequest/{crId}
> fix(rest): add requestClosedOn field in get clearingRequest_by_id endpoint.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/search/SearchController.java
Include documentation for "document" as typeMask in search endpoint which dictates entire document search or only specific fields.
No issue.
No new dependency
Check the OpenAPI doc for search endpoint.
Must:
> fix(doc): fix OpenAPI doc for Search endpoint

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
- libraries/datahandler/src/main/thrift/vulnerabilities.thrift
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: #2529 
Description: new endpoint for vulnerability summary page for a project.
How To Test: run the endpoint , {PROJECTS_URL}/{id}/vulnerabilitySummary to get the result.
> feat(rest): endpoint for vulnerabilitySummary page.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Issue: Closes : #2569 
1: URL: http://localhost:8080/resource/api/projects (post)
2: Include the visibility field in the request body.
3: Set the visibility field to both uppercase (e.g., "PRIVATE") and lowercase (e.g., "private").
> How should these changes be tested …
> fix(rest): Ensure visibility field is case-insensitive

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationPatch.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationRequestController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/Sw360ModerationRequestService.java
Update `PATCH` endpoint for `ModerationRequestController` to accept `POSTPONE` as an action from user.
When the user clicks on "Postpone Request" button from new UI, the moderation request can be patched with `action: POSTPONE` and new comment updated on the MR.
Closes #2467
> feat(api): postpone moderation request action

- backend/src/src-licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
1. The "Generate License Info" feature is failing for projects with linked releases having the same CLX attachment.
2. Duplicate releases can exist with version changes like abc 1.0.0 and abc v1.0.0. They have the same CLX attachment(same attachmentContentId). If both of such releases are linked to a project, we get a Duplicate key error due to same attachmentContentId for different release Ids.
> fix(GenerateLicenseInfo): Generate License Info is failing for releases having the same CLX

- backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
- backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- The VCS URL if not empty, will be validated for a valid URL while creating and updating a component. If the VCS string contains "github.com", it will sanitized to remove the noise and conform to the repository URL format: https://github.com/{supplier}/{component name}.
- Packages with invalid VCS URLs in the SBOM will be created as orphan packages
Closes #2377 
1. Creating/Updating a component via REST API and UI.
2. Creating a component via CDX Import.
_Relevant Screenshots:_
> feat(ComponentPortlet & ImportCDX): Validate VCS URL

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ClearingRequestSpecTest.java
Extra fields needed for get clearing request endpoints are added in the response.
Closes : #2500, #2499 
Endpoints where new fields are added : 
http://localhost:8080/resource/api/clearingrequests
http://localhost:8080/resource/api/clearingrequest/byId
> feat(rest): Add additional fields in get clearingrequest endpoints.

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/NouveauLuceneAwareDatabaseConnector.java
- libraries/nouveau-handler/src/main/java/org/eclipse/sw360/nouveau/LuceneAwareCouchDbConnector.java
1. Catch exception thrown by couchdb for nouveau query and log them for easy debugging.
2. Also ignore `@` in the query as it is treated as bad syntax.
Note: If you are using nouveau with old backed, check the error: https://github.com/apache/couchdb/issues/5262
Deploy the new branch and try a bad query, catalina log should have the response body for the exception.
> chore(nouveau): catch exception for nouveau query

- backend/licenseinfo/src/main/resources/xhtmlLicenseInfoFile.vm
Fix XHTML render issues:
* Missing `lang` or `xml:lang` attribute in `<html>`
* Missing font family.
* Unknown attribute `xborder-right`
Generate LicenseInfo with xhtml format and lint the generated report.
> fix(UI): Add lang attribute to ReadmeOSS.html for generated license info

- backend/common/pom.xml
- backend/common/src/main/java/org/eclipse/sw360/mail/MailUtil.java
- backend/components/src/main/java/org/eclipse/sw360/components/ComponentServlet.java
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java
- backend/pom.xml
- backend/projects/src/main/java/org/eclipse/sw360/projects/ProjectServlet.java
- clients/client/pom.xml
- clients/http-support/pom.xml
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseRepositoryCloudantClient.java
- pom.xml
- rest/authorization-server/pom.xml
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/customheaderauth/Sw360CustomHeaderAuthenticationFilter.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/customheaderauth/Sw360CustomHeaderAuthenticationProvider.java
- rest/resource-server/pom.xml
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/databasesanitation/Sw360DatabaseSanitationService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
Replace all `javax.*` dependencies with `jakarta.*` dependencies as Tomcat 11 completes the migration and servlets refuse to load.
Did not migrate to latest jakarta-mail `2.1.3` as it throws error "No provider of jakarta.mail.util.StreamProvider was found". `2.0.1` is the latest version which works.
Also, fix some compile warnings from Java 11.
@heliocastro
Setup new backend with Java 21+ and Apache Tomcat 11.
> fix(servlet): complete migration javax to jakarta

- backend/common/src/main/java/org/eclipse/sw360/components/summary/ComponentSummary.java
- backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/PackageDatabaseHandler.java
Components are being created from the vcs field in a CDX SBOM using the naming convention "manf.name". This has been changed to create the name with only the component name extracted from the vcs, omitting the manufacturer part unless and until there is a name class, which in that case the name would be created as manf/name. 
Import a CDX SBOM
> feat(ImportSBOM):Change naming convention of imported components

- backend/vendors/src/main/java/org/eclipse/sw360/vendors/VendorDatabaseHandler.java
- rest/resource-server/src/docs/asciidoc/vendors.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java
Issue: #2604 
Description: endpoint to update a vendor.
> feat(rest): endpoint to update a vendor.

- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
1. The new clearing state of a release was not being rendered after a successful PATCH. It was rereferring to the older clearing state.
2. If an empty array of attachments was passed in the request body, the clearing state of the release would get updated to NEW while an approved CLX/CRT was still present. 
**These issues are fixed by**
-  Fetching the updated release before creating a HalResource out of it.
-  Setting the new clearing state _after_ the approved attachments are retained.
1. Pass an empty array of attachments and …
> fix(REST): Patch Release is causing the clearing state to be updated to NEW even if a Clearing is existing

- backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java
- backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/JsonGenerator.java
- backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/OutputGenerator.java
- backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/TextGenerator.java
- backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGenerator.java
- backend/licenseinfo/src/test/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGeneratorTest.java
- libraries/datahandler/src/main/thrift/licenseinfo.thrift
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/Sw360LicenseInfoService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Parameter "excludeReleaseVersion" for endpoint /projects/{id}/licenseinfo that excludes release version information from the license info document when set to true.
Works for variant "DISCLOSURE" only.
> feat(REST): Exclude release version from license info

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue reference 
Closes #2441 
Sample test : 
URL : http://localhost:8080/resource/api/reports?module=licenseInfo&projectId=8fef50eafc484e33bb8ebb33618ed56d&generatorClassName=DocxGenerator&variant=DISCLOSURE
Result : 
Can download from rest!
> fix(rest) : Move GenerateLicenseInfoFile rest end point to SW360reportcontroller

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Add the missing variable `excludeReleaseVersion` from #2496 in changes from #2442
@smrutis1 @afsahsyeda
Check build logs and REST API test docs.
> fix(build): add the missing excludeReleaseVersion

- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- libraries/datahandler/src/main/thrift/projects.thrift
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Turn on feature by adding this property into /etc/sw360/sw360.properties: **enable.flexible.project.release.relationship=true**
Create a new project with dependency network:
- Url: http://localhost:8080/resource/api/projects/network
- Method: POST
- Body: 
```
{
"name": "Test_PR",
"dependencyNetwork": [
{
"releaseId": "${release_id_1_in_sw360}", // Replace this by an existing release id in sw360
"releaseRelationship": "CONTAINED",
"mainlineState": "OPEN",
"comment": "",
"createOn": "2024-07-05",
"createBy": "admin@sw360.org",
"releaseLink": [
{
"releaseId": "${release_id_2_in_sw360}", // Replace this by an existing release id in sw360 (difference from above)
"releaseRelationship": "OPTIONAL",
"mainlineState": "MAINLINE",
"comment": "",
"createOn": "2024-07-05",
"createBy": …
```
> feat(Project): Add new endpoint for project's license clearing tree view

- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/common/src/main/java/org/eclipse/sw360/spdx/SpdxBOMImporter.java
- backend/common/src/test/java/org/eclipse/sw360/spdx/SpdxBOMImporterTest.java
Issue #2364 (Import SPDX function not working when `enable.flexible.project.release.relationship=true` is enabled)
This PR allows to import SDPX as project's dependency network
Add configuration: `enable.flexible.project.release.relationship=true` to `/etc/sw360/sw360.properties`
1. Go to Project Page then select import SBOM (SPDX):
2. Import following file (Unzip this zip file to get SPDX example file) [SPDX_Example.spdx.zip](https://github.com/eclipse-sw360/sw360/files/14612031/SPDX_Example.spdx.zip):
3. Click **Upload & Import** button, then a new project with name **Project3** will be created:
4. Select **License Clearing** tab the tree view will show as below:
> fix(Project): Import SPDX as dependency network

- backend/licenses-core/pom.xml
- backend/vulnerabilities-core/pom.xml
- keycloak/README.md
- keycloak/event-listeners/pom.xml
- keycloak/pom.xml
- keycloak/user-storage-provider/pom.xml
- pom.xml
Since now we do not have OSGi modules, in bare metal install, there is no need to put the jar files. Everything is packages as war and put in tomcat/webapps.
Set the default value of `jars.deploy.dir` to empty to prevent their copy but still allow Docker builds to work as it is passed as parameter to maven.
At the same time, add `listener.deploy.dir` (with default empty value) for copying keycloak related dependencies and jars to its provider directory.
@heliocastro @smrutis1
Install sw360 with `mvn clean install -DskipTests …
> chore(maven): segregate war and jar deploy dirs

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: Closes #2371
Description: this new endpoint is used to save attachmnetUsages for the project.
How to test:
Pass Map< String, List< String >> in request body.
String can be of 4 types:
- selected : release attachmentUsage that you want to save/check
- deselected : release attachmentUsage that you want to delete/uncheck
- selectedConcludedUsages : release attachmentUsage that you want to save/check of type license info's conclusion checkbox only
- deselectedConcludedUsages:  release attachmentUsage that you want to delete/uncheck of type license info's conclusion checkbox only
Format of String inside list varies according to the usageFields (sourcePackage, licenseInfo, manuallySet) :
- for `sourcePackage`, releaseId_sourcePakage_attachmentContentId
- for `licenseInfo`, …
> feat(rest): saveUsages in project page

- backend/common/src/main/java/org/eclipse/sw360/common/utils/BackendUtils.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/common/src/main/resources/sw360.properties
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/permissions/PermissionUtils.java
Issue: #2544 
To make it configurable, set the variable as true in sw360.properties file.
--> disable.clearing.fossology.report.download=true
After making it configurable, sw360 will now upload the clearing report to fossology for scanning purpose only i.e., it won't generate and download the report back to sw360 as an attachment in release.
As a result it will change the state from Scan Available to Under Clearing.
> fix(clearingState): making fossology report download configurable.

- rest/resource-server/src/docs/asciidoc/vendors.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java
Closes: #2563 
Description: run the endpoint to get the releases used by the vendor.
> feat(rest): get releases used by vendor

- rest/resource-server/src/docs/asciidoc/schedule.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/ScheduleAdminController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/Sw360ScheduleService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ScheduleSpecTest.java
…ent deletion.
Closes #2242 
http://localhost:8080/resource/api/schedule/cveService
http://localhost:8080/resource/api/schedule/unscheduleCve
http://localhost:8080/resource/api/schedule/deleteAttachment …
> feat(rest): Create new endpoint for schedule CVE and schedule attachment deletion in admin tab.

- rest/resource-server/src/docs/asciidoc/clearingRequests.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/Sw360ClearingRequestService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ClearingRequestSpecTest.java
Endpoint to update comment on a clearing request.
Response contains a list of all the comments present on the CR.
Closes : #2524
> feat(rest): Endpoint to add comment on a clearing request.

- backend/common/src/test/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandlerTest.java
- backend/components/src/test/java/org/eclipse/sw360/components/db/ProjectDatabaseHandlerTest.java
Fix bug: Project test fail with enable.flexible.project.release.relationship=true
Ref: https://github.com/eclipse-sw360/sw360/pull/2612#issuecomment-2404432363
> Fix bug: Project test fail when enable.flexible.project.release.relationship=true

- backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
**Description**:
1. On importing a CDX SBOM that contains characters like ":" in the vcs string, the import fails with a NullPointerException.
1. Use something like - "scm:git:github.com/afollestad/material-dialogs.git" as the vcs value in the sbom and import it.
> fix(ImportCDX): VCS sanitization failing on characters like colon

- .github/workflows/build_and_test.yml
- .github/workflows/codeql.yml
- .github/workflows/docker_deploy.yml
Reference on scorecard:
Token-Permissions
Determines if the project's workflows follow the principle of least privilege.
Reason
detected GitHub workflow tokens with excessive permissions
Details
Info: jobLevel 'packages' permission set to 'read': .github/workflows/codeql.yml:37
Info: jobLevel 'actions' permission set to 'read': .github/workflows/codeql.yml:40
Info: jobLevel 'contents' permission set to 'read': .github/workflows/codeql.yml:41
Info: jobLevel 'contents' permission set to 'read': .github/workflows/docker_deploy.yml:64
Info: jobLevel 'contents' permission set to 'read': .github/workflows/docker_deploy.yml:91
Info: jobLevel 'contents' permission set to 'read': .github/workflows/docker_deploy.yml:123
Warn: no topLevel permission defined: .github/workflows/build_and_test.yml:1 …
> chore(scorecard): Update permissions on workflows

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: #2610 
Description: endpoint to get obligations depending upon obligation level (Possible values are: License, Project, Component, Organization).
> feat(rest): endpoint to get obligations depending upon obligation level

- backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/SPDXParser.java
When generating license information for a project, some releases may contain attachments (e.g., ISR, CLX files) that are in a corrupted format. These corrupted attachments prevent the successful generation of the license information for the entire project. However, identifying which specific release has the corrupted attachment is challenging.
**Solution:** Adding log statements to the license generation process can help identify specific release(s) with corrupted attachments, such as ISR or CLX files. By logging details when an attachment processing fails, we can quickly pinpoint which release is causing the issue
> feat: Add logging to identify releases with corrupted attachments during license generation

- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
**Description**:
Fetch all the releases that are in NEW_CLEARING state and have a source attachment available by using the `isNewClearingWithSourceAvailable` filter/parameter and setting it to true. This function is useful in determining the candidate releases that can be sent to license scanning tools.
> feat(REST):fetch releases that are in NEW_CLEARING state and have a SRC/SRS attachment using parameter isNewClearingWithSourceAvailable

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/resourcelists/ResourceComparatorGenerator.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ClearingRequestSpecTest.java
Added **pagination** for get all visible clearing requests endpoint and fixed 403 forbidden error for CRs created for projects with **"ME_AND_MODERATORS**" visibility.
Endpoint : http://localhost:8080/resource/api/clearingrequests?page=0&page_entries=2
closes : #2646
> feat(rest): Add pagination to get clearing requests endpoint and fix 403 forbidden error.

- rest/resource-server/src/docs/asciidoc/vendors.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java
Issue: #2624 
Description: run the endpoint to delete a vendor by id.
> feat(rest): delete a vendor by id.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
Issue: #2695 
Description: After these changes, attachment won't get deleted when component's externalIds field is updated through rest.
> fix(rest): component attachment deletion while updating externalIds

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: #2598 
Description: endpoint to remove orphaned obligations from the project's license obligation page.
> feat(rest): endpoint to remove orphaned obligations from project.

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
- rest/resource-server/src/docs/asciidoc/clearingRequests.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/Sw360ClearingRequestService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ClearingRequestSpecTest.java
This endpoint is to update a clearing request using id.
Closes: #2464 
Closes: #2523
> feat(rest): Add endpoint to handle updation of clearing requests.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestExceptionHandler.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/SimpleAuthenticationEntryPoint.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/configuration/security/Sw360AuthorizationServerConfiguration.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ApiSpecTest.java
1. Re-enable the ignored `should_document_error_unauthorized` test.
2. Add the missing exception handler for OAuth2 security filter chain and test cases.
3. Update the authentication exception handler to use classes from `RestExceptionHandler` to get uniform response.
@smrutis1
1. Check if no tests are skipped for resource controller.
2. Check if a proper response body is sent for unauthorized REST API requests.
> fix(test): enable unauthorized request test

- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/moderation/src/main/java/org/eclipse/sw360/moderation/ModerationHandler.java
- backend/moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
- libraries/datahandler/src/main/thrift/moderation.thrift
- libraries/datahandler/src/main/thrift/projects.thrift
- libraries/datahandler/src/main/thrift/sw360.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/Sw360ClearingRequestService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Add a new field **size** to the clearing request which determines the size of the clearing request based on the number of **open releases** in the project for which the CR is created. 
Size based on the table below : 
1- 20 = **Very Small**
21- 50 = **Small**
50-75 = **Medium**
75-150 = **Large**
150 and above = **Very large**
The CR size should be dynamic. if release are uploaded after CR creation, it should reflect in the `CR Size`.
> feat(rest): Add size parameter to clearing request.

- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/client/persistence/OAuthClientRepository.java
> * Which issue is this pull request belonging to and how is it solving it? (*#https://github.com/eclipse-sw360/sw360/issues/2742*)
Issue: 
Must:
> fix(rest): Fixed the reference to wrong db for oauthclients

- backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
- libraries/datahandler/src/main/thrift/projects.thrift
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
This PR introduces the feature that allows users to configure release creation when importing CycloneDX SBOM to an existing project.
closes: #2435
> feat(importCDX): Add functionality to configure release creation when importing SBOM to an existing project

- rest/resource-server/src/docs/asciidoc/schedule.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/ScheduleAdminController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/Sw360ScheduleService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ScheduleSpecTest.java
Issue: #2268 
create new endpoint to schedule svm sync , reverse svm match , track the feedback and cancel services as well.
Note : only admin user can access.
> Have you …
> feat(rest): Create new Api's to track feedback, reverse svm match and schedule svm sync in schedule tab.

- backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
**Description**:
- Certain VCS URLs in the imported SBOM redirect to different URLS.
- The URLS they are redirecting to might already exist in SW360, leading to duplicate creation of components.
- This redirection is now handled during import where each each valid VCS is checked for redirection. If the VCS redirects, the final URL it redirects to is considered as the actual VCS of the component.
- The maximum number of redirect attempts and connection timeout can be configured in the sw360.properties file. The default value has been set to 5 and …
> feat(Import CDX): Handle redirection of VCS URLs in SBOM

- backend/fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java
Closes #2787
Description: Stop repetitive entries of attachment in fossology dashboard when fossology process is triggered.
> feat(FossologyTrigger): stop repetitive entries of attachment.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
Add new endpoint that allows user to subscribe and unsubscribe to a release
- If the user **has** previously subscribed to that release, they will **unsubscribe** from that release
- If the user **has not** previously subscribed to that release, they will **subscribe** from that release
- URL: http://localhost:8080/resource/api/releases/{release_id}/subscriptions
- Method: POST
- Response: Status 200
-  If the user **has** previously subscribed to that release
```
Release has been unsubscribed
```
-  If the user **has not** previously subscribed to that release
```
Release has been subscribed
```
> feat(Release): Add new endpoint for release subscription

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Add new endpoint that allows user to subscribe and unsubscribe to a component
- If the user **has** previously subscribed to that component, they will **unsubscribe** from that component
- If the user **has not** previously subscribed to that component, they will **subscribe** from that component
- URL: http://localhost:8080/resource/api/components/{component_id}/subscriptions
- Method: POST
- Response: Status 200
-  If the user **has** previously subscribed to that component
```
Successfully unsubscribed from the component.
```
-  If the user **has not** previously subscribed to that component
```
Successfully subscribed from the component.
```
Must:
> feat(Component): Add new endpoint that allows user to subscribe and unsubscribe to a component

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Rest end point for project ECC Export Spreadsheet
Closes #2462 
Add screenshots to help explain your problem.
* Docker version OR
* Last commit id on main
* With docker through `docker logs sw360`
* From bare metal / vm install system under /var/log/sw360/sw360.log and /var/log/tomcat/error.log
> feat(rest) : Rest end point for project ECC Export Spreadsheet

- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ClearingRequestSpecTest.java
Added missing documentation for new parameter `clearingSize `introduced in #2642
> feat(rest): Add documentation for new clearing size parameter.

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Closes #2780 
Description:
Endpoint to get the license info header text.
> feat(rest): endpoint to get license info header text.

- backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Reverts eclipse-sw360/sw360#2138
The component is being updated only if the specific fields are empty which is the expected behavior. This feature prevents the CDX component type from being in the component and also removes the feature of merging different component descriptions using the "||" operator.
> Revert "fix(importCDX): Resolved unnecessary update of component fields"

- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/spdx/document/SpdxDocumentDatabaseHandler.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/spdx/documentcreationinfo/SpdxDocumentCreationInfoDatabaseHandler.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/spdx/packageinfo/SpdxPackageInfoDatabaseHandler.java
- backend/common/src/main/java/org/eclipse/sw360/spdx/SpdxBOMImporter.java
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
- rest/resource-server/src/docs/asciidoc/releases.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/SW360SPDXDocumentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
- Get SPDX Document Information
- Update SPDX Document Information
```
curl 'https://sw360.org/api/releases/3765276512' -i -X GET \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTcxMjkxOTg2NywiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6IlFNd3UxMFVWdUUwdFd3MkV5VnRsQm1OdGRzdyIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.Xp3TdSvb2oQ77zqg8RLaz4F47vFEX0lPL4ijmKRmL9 …
```
> feat(spdx): Add API for SPDX Document tab

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Rest end point forExport Project Create Clearing Request
Closes : #2461 
This PR should be merged after #2442
> feat(rest) : Export Project Create Clearing Request

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
- rest/resource-server/src/main/resources/application.yml
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/SW360RestHealthIndicatorTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/configuration/security/Sw360AuthorizationServerConfiguration.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/HealthSpecTest.java
- rest/resource-server/src/test/resources/application.yml
Add the missing docs for `/health` endpoint in OpenAPI docs. To make the changes work with Swagger UI, the `/health` endpoint had to be moved making it a breaking change.
**BREAKING CHANGE:** Move the health endpoint from `/resource/health` to `/resource/api/health` for OpenAPI documentations to be easy to use.
Check OpenAPI docs for the health endpoint.
> fix(openapi)!: add health endpoint to openapi

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/TestRestDocsSpecBase.java
Closes : #2491 
Recently, we were able to upload a single file as an attachment, but after these code changes, we can now upload multiple files, including the same file or modified versions.
http://localhost:8080/resource/api/projects/{projectId}/attachments
> fix(rest): Added code for updating multiple project attachments.

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
1. Fix OpenAPI docs for the `/reports` endpoint.
2. Refactor `/reports` endpoint to expose all hidden parameters.
3. Modify source bundle to use attachment usage to generate bundle.
4. Do not update attachment usage based on report generation. Should be changed with `/attachmentUsage` endpoint only.
@keerthi-bl
Generate different reports with `/reports` endpoint to check all parameters.
> fix(report): refactor /reports endpoint

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
Fix structure of `elemMatch`. The position of operator and field was wrong in the structure.
Current:
```json
{
"$elemMatch": {
"field": {
"$eq": "value"
}
}
}
```
Correct:
```json
{
"field": {
"$elemMatch": {
"$eq": "value"
}
}
}
```
See: http://localhost:5984/_utils/docs/api/database/find.html#find-elemmatch
Fetch data which uses this filter:
1. Fetch moderation request list
2. Fetch projects
3. Fetch projects with moderator filter
> fix(cloudant): fix structure of elemMatch query

- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java
- backend/licenseinfo/pom.xml
- backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxUtils.java
- backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/XhtmlGenerator.java
- backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/parsers/AbstractCLIParser.java
- backend/search/src/main/java/org/eclipse/sw360/search/db/SearchDocument.java
- backend/vmcomponents/src/main/java/org/eclipse/sw360/vmcomponents/VMComponentHandler.java
- backend/vmcomponents/src/main/java/org/eclipse/sw360/vmcomponents/common/SVMMapper.java
- backend/vmcomponents/src/main/java/org/eclipse/sw360/vmcomponents/db/VMDatabaseHandler.java
- backend/vmcomponents/src/main/java/org/eclipse/sw360/vmcomponents/handler/SVMSyncHandler.java
- backend/vmcomponents/src/main/java/org/eclipse/sw360/vmcomponents/process/VMProcessHandler.java
- backend/vmcomponents/src/test/java/org/eclipse/sw360/vmcomponents/handler/SVMSyncHandlerTest.java
- backend/vulnerabilities-core/src/main/java/org/eclipse/sw360/vulnerabilities/db/VulnerabilityDatabaseHandler.java
- backend/vulnerabilities/src/main/java/org/eclipse/sw360/vulnerabilities/VulnerabilityHandler.java
- libraries/datahandler/src/test/java/org/eclipse/sw360/datahandler/permissions/DocumentPermissionsTest.java
- libraries/nouveau-handler/pom.xml
- pom.xml
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/client/rest/OAuthClientController.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/Sw360UserDetailsProvider.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/customheaderauth/Sw360CustomHeaderAuthenticationFilter.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/security/customheaderauth/Sw360CustomHeaderAuthenticationProvider.java
- rest/resource-server/pom.xml
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/UserController.java
Old apache-commons-lang was puled down by nouveau-handler, and misleading outdated code in different sources.
All code now is adjusted to commons-lang3 or commons-text where needed.
> fix(deps): Deprecate old commmons-lang library

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/NouveauLuceneAwareDatabaseConnector.java
- rest/resource-server/src/docs/asciidoc/components.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
Add all advance search parameters for `/components` endpoint.
Closes #2842
1. Test all combinations of the filter.
2. Test with lucene as true and false.
Must:
> feat(api): complete advance search for components

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
fix(rest): Added code to get obligation releaseView data in project.
http://localhost:8080/resource/api/projects/{ id}/licenseObligations?view=true
Closes : #2485
Please describe your issue in few words here.
Describe the bug and list the steps you used when the issue occurred.
Add screenshots to help explain your problem.
* Docker version OR
* Last commit id on main
* With docker through `docker logs sw360`
* From bare metal / vm install system under /var/log/sw360/sw360.log and /var/log/tomcat/error.log
> fix(rest): Added code to get obligation releaseView data in project.

- rest/resource-server/src/docs/asciidoc/moderationRequests.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationRequestController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/Sw360ModerationRequestService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ModerationRequestSpecTest.java
Issue: Closes: #2362 
http://localhost:8080/resource/api/moderationrequest/delete/{id}
Must:
> feat(rest): create new endpoint to delete ModerationRequests by id.

- pom.xml
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/Sw360AuthorizationServer.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
- rest/rest-common/pom.xml
- rest/rest-common/src/main/java/org/eclipse/sw360/rest/common/Sw360XSSRequestWrapper.java
- rest/rest-common/src/main/java/org/eclipse/sw360/rest/common/Sw360XssFilter.java
This PR is to sanitize JSON and request parameters, headers containing potential malicious texts such as  `<img/src/onerror = alert(1)>` and store it as `&lt;img/src/onerror=alert(1)&gt;` in database.
Issue: 
@GMishx @heliocastro @hoangnt2  …
> rest(xss): Prevent stored XSS

- backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Added logging while importing SBOMs with wrong/incomplete metadata. Also updated the error msg on UI.
closes : #2879
> fix(importCDX): Add logging for null metadata in sbom.

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ProjectTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: 
Closes : #2832 
Closes: #2854
Rest end point added with following parameters for advance search in a project list page.
Version, Project responsible, State, Clearing State, additional Data.
URL : http://localhost:8080/resource/api/projects?name=update&version=1.1&state=PHASE_OUT&projectResponsible=keerthi_admin@sw360.org
Response : 
{
<project list with above criteria should get displayed here.>
}
Must:
> feat(Rest) : Advanced Search for project page

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Closes #2876 
(post method ): http://localhost:8080/resource/api/projects
(patch method): http://localhost:8080/resource/api/projects/{Id}
While creating a project, include the packageIds and verify whether they are updated in the database. Similarly, while patching a …
> fix(rest): Added packageIds in project create and update APIs.

- rest/resource-server/src/docs/asciidoc/projects.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
…ctId.
Issue: Closes #2896 
get:  http://localhost:8080/resource/api/projects/{projectId}/packages
Must:
> fix(Rest): new endpoint will help to get the package details by projectID

- backend/attachments/src/main/java/org/eclipse/sw360/attachments/AttachmentHandler.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentDatabaseHandler.java
- libraries/datahandler/src/main/thrift/attachments.thrift
- libraries/datahandler/src/main/thrift/components.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/AttachmentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/AttachmentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ComponentSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
1. Currently, there are two formats when fetching attachments for a project, component, or release
- For **projects** and **releases**:
```json
{
"_embedded": {
"sw360:attachments": [....]
}
}
```
- For **components**:
```json
{
"_embedded": {
"sw360:attachmentDTOes": [....]
}
}
```
2. Additionally, project/release attachments cannot be updated when calling the patch project/release endpoint.
1. Make get attachment endpoints response format consistent
2. Allow patching a project/component/release with attachment data (in a consistent way)
3. …
> fix(Attachment): Make get attachment endpoints consistent, allow to update project/component/release with attachment data

- backend/moderation/src/main/java/org/eclipse/sw360/moderation/db/ProjectModerationRequestGenerator.java
Issue:  Closes : #2828 
Curl : 
curl --request PATCH \
--url http://localhost:8080/resource/api/projects/65806abc788143958e3ffd808cc85f1a \
--header 'authorization: Basic a2VlcnRoaV91c2VyQHN3MzYwLm9yZzoxMjM0NQ==' \
--header 'content-type: application/json' \
--data '{
"description": "desc 500"
}'
Must:
> fix(rest) : Moderation update overwrites previous fields

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Adding licenseInfoHeaderText parameter in summaryAdministration api response.
Closes : #2867  
API end point :  projects/{projectId}/summaryAdministration .
Must:
> fix(rest) : Add licenseInfoHeaderText in summaryAdministration api response

- rest/resource-server/src/docs/asciidoc/vendors.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/VendorSpecTest.java
Closes: #2869 
Description: this new endpoint will merge the source vendor to the target vendor.
> feat(rest): endpoint to merge vendor.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/obligation/ObligationController.java
[//]: # (This program and the accompanying materials are made)2921
Issue: #2921 
Must:
> feat(rest) : Comment added to reuse methods for Duplicateobligation functionality

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
Issue: Closes : #2802 
1. Get list of releases for edit : (RE-USE existing endpoint)
URL : http://localhost:8080/resource/api/releases : GET
2. Update release : (RE-USE existing endpoint)
URL : http://localhost:8080/resource/api/releases/1bb5055fdabb42e78f9bd81710a6e74d     request : PATCH
Body : 
{
"cpeid": "12343", …
> feat(rest) : Search for vendors added

- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/BulkDeleteUtil.java
- backend/components/src/test/java/org/eclipse/sw360/components/db/BulkDeleteUtilTest.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Issue: #2415, #1649
Create new endpoint for bulk delete function (#1468).
- Preparations  
- Before starting the system, add the following options to sw360.properties.  
```
bulk.release.deleting.enabled=true  
admin.private.project.access.enabled=true  
```
- Obtain an API token …
> feat(rest): create new endpoint for bulk delete function

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> fix(rest): Added a commit message while create a moderation request.

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseRepositoryCloudantClient.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/client/persistence/OAuthClientDeserializer.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/client/persistence/OAuthClientEntity.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/client/rest/OAuthClientController.java
- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/client/rest/OAuthClientResource.java
This pull request addresses issues with database operations for `OAuthClientEntity`, ensuring performing CRUD properly and compatible with the existing database and response formats.
1. **Fix for `updateIdAndRev` in `OAuthClientEntity`**
- **Issue**: The  changes in [#2607](https://github.com/eclipse-sw360/sw360/pull/2607) refactored `OAuthClientEntity` from implementing `CouchDbDocument` to `Serializable`, breaking `_id` and `_rev` updates due to a Thrift type check (`TBase` mismatch) in DatabaseCloudantConnector.
- **Solution**: Added custom handling for `OAuthClientEntity` in Thrift checking methods.
2. **Custom Deserializer for Database Compatibility**
- **Issue**: The switch to `Serializable` led to JSON-format storage and responses, misaligning with the GSON-based format (e.g., …
> Fix OAuth Client deserialization and database operations

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
Add a null check at `/projects/{id}/summaryAdministration` endpoint for License Info Header.
@keerthi-bl
> fix(project): null check at /summaryAdministration

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/SW360SPDXDocumentService.java
Issue:  Update a non existing SPDX Document will not create a new one. Response always:
Status: 400
Message:
```
Add SPDXDocument Failed!
```
Edit sw360.properties
```properties
spdx.document.enabled = true
```
URL: http://{ip}:8080/resource/api/releases/${releaseId}/spdx
Body:
```json
{
"documentCreationInformation": {
"creator": [
{
"type": "Person",
"value": "Test Admin (admin@sw360.org)",
"index": 0
}
],
"created": "2025-03-07T02:52:37.360Z"
}
}
```
Expected: Status 200
> fix(SPDXDocument): Fix bug add SPDX document always return fail

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: #2844 
resource/api/projects/{id}/addLinkedRelesesLicenses
please check project should have licenses attached.
Must:
> fix(rest): Add license information linking for project releases.

- backend/fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java
This PR enhances logging and error handling in the `FossologyRestClient` to improve debugging and maintainability. It addresses inconsistent error messages and insufficient debug information when failures occur.
- **Improved Debug Logging:**
- Added detailed debug logs before making HTTP requests (e.g., upload, scan, report generation).
- Included relevant context such as `filename`, `uploadId`, `jobId`, `reportId`, and `shaValue`.
- **Enhanced Error Handling:**
- Improved exception messages for `RestClientException`, `NumberFormatException`, and unexpected cases.
- Logs now provide clear descriptions of failures, including HTTP status codes and response bodies when available.
- Added debug logs for detailed error stack traces.
- **Fixed Typos and Formatting Issues:**
- Corrected spelling …
> refactor(rest): improve logging in FossologyRestClient

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
- libraries/datahandler/src/main/thrift/projects.thrift
This PR adds new project state values under the Administration tab of the project.
Previously available values:
- Active
- Phaseout
- Unknown
Newly added values:
- SVM Only
- Private
- Under Development
- Released
> feat(project): add new values to project state field

- backend/licenses-core/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/obligation/ObligationController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/obligation/Sw360ObligationService.java
> Please provide a summary of your changes here. Added new end point for editing an obligation
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)Edit Page (N) #2797
> * Did you add or update any new dependencies that are required for your change? no new Dependencies added
Issue: 
Edit Page (N) #2797
@GMishx 
Ensure the application is running.
Obtain valid authentication tokens for users with and without CLEARING_ADMIN authority.
* Test Case 1: Successful Update  
* Use a valid obligation ID and …
> feat(rest) :New Rest end point for edit obligation

- scripts/addUnsafeDefaultClient.sh
Read host, user and pass as arguments in addUnsafeDefaultClient.sh
@amritkv
Pass different parameters/flags to script:
* -d : Should delete default client
* -du : Should delete default user
* --host : To change host from `http://127.0.0.1:5984`
* --user : To change username from `admin`
* --pass : To change password from `admin`
> feat(script): read host, user and pass as args

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Constants.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
> * https://github.com/eclipse-sw360/sw360/issues/2858
Closes: #2858
Request Type : get
bomType : json or xml
withSubProject : true or false
module= sbom
projectId : project id
url:
http://localhost:8080/resource/api/reports?module=sbom&projectId=c2b4ced4c19ebb07d63039c5d501800a&withSubProject=true&bomType=json
Must:
> feat(rest) : Endpoint for export SBOM at project detail page

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/ScheduleAdminController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/schedule/Sw360ScheduleService.java
Description:
This PR introduces two new API endpoints to check the status of scheduled services.
1. Added GET /anyServiceScheduled endpoint to check if any service is scheduled, returning true or false
2. Added POST /status endpoint to check a specific service's status, requiring a service name.
> feat(rest): Added endpoints to fetch schedule service status

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/ThriftEnumUtils.java
- libraries/datahandler/src/main/thrift/components.thrift
Added new component type COTS-Trusted Supplier
https://github.com/eclipse-sw360/sw360/issues/3001
Issue: https://github.com/eclipse-sw360/sw360/issues/3001
> @GMishx 
New element has been added in the dropdown of component type in add component screen
Must:
> feat(addNewComponentType) : Added new component type COTS-Trusted Supplier

- build-configuration/pom.xml
- pom.xml
- rest/resource-server/pom.xml
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/Sw360ResourceServer.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/moderationrequest/ModerationRequestController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/security/ResourceServerConfiguration.java
- rest/resource-server/src/main/resources/application.yml
- rest/rest-common/src/main/java/org/eclipse/sw360/rest/common/Sw360XSSRequestWrapper.java
Use `git-commit-id-maven-plugin` plugin to read git properties and generate version for OpenAPI doc on the fly.
The version uses major and minor version from git and number of commits between HEAD and last tag as the patch version.
This helps in providing a reliable way of identifying updates in REST API until we have stable REST API to use custom API version.
@heliocastro @hoangnt2 @smrutis1
Open the OpenAPI docs and check the API version.
> feat(version): generate OpenAPI doc version on fly

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/thrift/ThriftValidate.java
Add validation checks to ensure SPDX documents have required fields:
- Add null object validation for SPDXDocument and DocumentCreationInformation
- Validate ID fields in SPDXDocument are not empty
- Ensure creator and creation date are present in DocumentCreationInformation
@GMishx @KoukiHama 
Must:
> fix(spdx): add null and empty field checks for SPDX documents

- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/EccTest.java
Added integration tests for the ECC (Export Control and Customs) API endpoints.
The tests cover:
Retrieving all ECC information
Pagination of ECC information results
Empty result handling
Exception handling
These tests ensure proper functionality of the ECC-related REST API endpoints
and improve overall test coverage for the resource server.
> feat(rest): added tests for ecc rest endpoints

- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/SearchTest.java
Added integration tests for Search API with test cases for:
- Basic search and filtering
- Pagination
- Empty results
- Error handling
All tests passing.
> feat(rest): added search API integration tests

- rest/authorization-server/src/main/java/org/eclipse/sw360/rest/authserver/Sw360AuthorizationServer.java
Remove unused property variables:
- `rest.access.token.validity.seconds`
- `sw360.liferay.company.id`
> chore(authorizationserver): remove unused vars

- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ConfigContainerRepository.java
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/config/FossologyConfig.java
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/config/FossologyRestConfig.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/admin/fossology/FossologyAdminController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/admin/fossology/Sw360FossologyAdminServices.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/FossologySpecTest.java
This PR replaces the hardcoded download timeout in FossologyConfig.java with a dynamic configuration fetched from ConfigContainerRepository. The timeout value is now configurable via the database  allowing administrators to adjust it without modifying the source code (hardcoding the timeout values ).
Issue: 
Resolves the TODO: "TODO get from a config class" in FossologyConfig.java.
@GMishx @keerthi-bl 
1. Ensure CouchDB contains a valid ConfigContainer entry with keys:
-    "fossology.downloadTimeout" (numeric value for timeout)
- …
> fix(fossology): Fetch download timeout from ConfigContainer repository

- keycloak/user-storage-provider/src/main/java/org/eclipse/sw360/keycloak/spi/Sw360UserStorageProviderFactory.java
The current KeyCloak integration works only when a user is created in KeyCloak. The update of the user fails sometimes with no specific reason.
The integration does not work other way around. KeyCloak cannot import existing users from SW360. The sync fails.
Fixes #3087
> @GMishx 
- Keycloak is installed, configured, and running.
- The `Sw360UserStorageProvider` is deployed and registered as a User Storage Provider in Keycloak.
- The external service (e.g., SW360 Couch DB) is running and accessible, with users available for synchronization.
- A …
> fix(security) :  KeyCloak cannot import existing users from SW360

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
Closes #2952 
Run the existing licenseClearing endpoint with different filters(component type, release clearing state, release relation).
> feat(Rest): adding filter search in license clearing get endpoint.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
i traced `importSBOM` method in  `ComponentController.java` and this problem handled by return message 'Invalid SBOM file' so i followed the same approch in `ProjectController.java` to achive consistent error handling for invalid SBOM uploads across both controllers.
Issue: 
closes: #3104
> @GMishx 
>  send invaild SBOM file
Must:
> fix(rest): improve error messages for invalid SBOM file imports

- libraries/datahandler/src/main/thrift/components.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/ComponentController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
1. Use `ComponentDTO` for `/splitcomponent` as `Component` does not accept attachments.
2. Add `releaseIds` to `ComponentDTO` as `Component` has it and makes it easy for client to provide the release info.
Try to split some components with multiple releases and attachments.
> fix(component): ComponentDTO for /splitcomponent

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportBean.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
Issue: 
Closes : #3052 
@GMishx 
1. Check existing end point for download licenseinfo report and add param for it selectedRelRelationship. 
Sample URL : GET :
http://localhost:8080/resource/api/reports?projectId={projectId}&module=licenseInfo&variant=REPORT&generatorC …
> fix(rest) : Missing request param for downloadlicenseinfo report.

- keycloak/event-listeners/pom.xml
- rest/pom.xml
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
This PR fixes the issue by modifying the createHalLicenseClearing method in ProjectController.java to explicitly set the self-link with the actual project ID. The fix ensures that the response contains the correct project ID in the self-link, making the API more consistent and reliable.
No new dependencies were added or updated for this change.
fixes issue #3106 
- @GMishx 
- @deo002 
1. Build and deploy the application
2. Make a GET request to `/projects/{projectId}/licenseClearing` with a valid project ID
3. Verify that the response contains a self-link with the correct project ID in the format:
```json
"_links": {  
"self": {  
"href": "http://localhost:8080/resource/api/projects/{actual-project-id}"  
}  
}
```
4. No additional tests were implemented as this is a straightforward fix …
> Add proper self-link with project ID in licenseClearing endpoint

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java
Issue: #3144
Description: this new endpoint will help to get the licenses info present in release attachment in project's license clearing page.
> feat(rest): endpoint to get src file list for the licenses.

- backend/schedule/src/main/java/org/eclipse/sw360/schedule/service/ScheduleHandler.java
- backend/vmcomponents/src/main/java/org/eclipse/sw360/vmcomponents/handler/SVMSyncHandler.java
In SVMSyncHandler::getVulnerabilitiesByComponent
function, used to create ReleaseVulnerabilityRelation, do not return in between the loop.
Closes #3173
> fix(svm): SVMSyncHandler dont return loop

- rest/resource-server/src/docs/asciidoc/licenses.adoc
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
…ense tab.
Issue: #3114 
endpoint: 
http://localhost:8080/resource/api/licenses/6d990cf76cc16de6068e32ebd100091b/deleteLicenseType
Must:
> fix(Rest): Only admin users can delete license types in the admin license type.

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
this PR fixes a critical API inconsistency in the VendorController.getReleases() method. Previously, the endpoint would return 204 No Content for non-existent vendor IDs, making it impossible for clients to distinguish between "vendor exists but has no releases" and "vendor doesn't exist".
closes #3205
> fix(rest): add vendor existence validation in getReleases endpoint

- backend/licenses-core/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
…sponse
Closes #3192
Delete: http://localhost:8080/resource/api/licenseTypes/5c2f90c4f15d2c92a91ff880c00021
First, create a License Type and then assign it to a License. After that, try to delete the License Type using its ID — it will not be allowed because it is in …
> fix(rest): Restructuring of the response to Delete a License Type API.

- backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/LicenseInfoHandler.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/licenseinfo/Sw360LicenseInfoService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java
Throw better exceptions when the `generatorClassName` or `variant` is wrong while generating LicenseInfo report.
Also update the documentation for possible combinations of `generatorClassName` and `variant` in OpenAPI docs.
1. Check if the documentation is clear.
2. Check if bad request is thrown if generator or variant is wrong.
> docs(licenseinfo): better excp for wrong generator

- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ComponentTest.java
This PR adds the IT for component endpoints.
Summary: As part of migrating the REST API test cases from Spring-Doc to open API, have migrated all the Integration tests for component endpoints from ComponentSpecTest to ComponentTest. 
@GMishx
How To Test?
Must:
> test(integration): added component integration tests in ComponentTest

- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/spdx/document/SpdxDocumentDatabaseHandler.java
This PR enhances the SBOM file import functionality to support older versions of CycloneDX in both .xml and .json formats (v1.1, v1.2, v1.3, etc.).
Previously, the import process rejected valid SBOM files using older CycloneDX schemas. With this update:
- .xml and .json files with schema versions like 1.1, 1.2, 1.3 are now validated and accepted correctly.
- SPDX import logic remains untouched.
Testing:
- Navigate to the SBOM import section.
- Upload CycloneDX .xml or .json files with schema version 1.1, 1.2, 1.3.
- Ensure the import succeeds and shows correct results.
> fix(sbom): add support for older CycloneDX XML/JSON format

- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ProjectTest.java
This PR adds the IT for project endpoints.
Summary: As part of migrating the REST API test cases from Spring-Doc to open API, have migrated all the Integration tests for project endpoints from ProjectSpecTest to ProjectTest. 
@GMishx
How To Test?
Must:
> test(integration): added project integration tests in ProjectTest

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/Sw360VendorService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java
Issue: 
Closes : #3294 
Before the PR
1. Create a Vendor and use it in a release/component/project.
2. Delete the Vendor from REST API.
3. Linked element cannot be loaded as the deleted Vendor ID is still associated.
After the PR : 
1. Create a Vendor and use it in a release/component/project.
2. Delete the Vendor from …
> fix(rest) : Check vendor usage before delete

- backend/fossology/pom.xml
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/FossologyHandler.java
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/config/FossologyConfig.java
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/config/FossologyRestConfig.java
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyInputStreamResource.java
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyResponse.java
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/rest/FossologyRestClient.java
- backend/fossology/src/main/java/org/eclipse/sw360/fossology/rest/model/FossologyV2Models.java
- libraries/datahandler/src/main/thrift/fossology.thrift
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/admin/fossology/FossologyAdminController.java
This PR is a part of the GSoC'25 Project. More PRs will follow this PR, this is a part of a series of PRs for "Improving Integration wish Fossology" - PR - 1
Fossology V2 Endpoints Refactor. 
- refactored the fossology codebase with the v2 endpoints
- at present attachments from sw360 are getting sent to fossology for a scan properly and the scan starts automatically
- facing some problems in triggering the auto report generation and then attaching it to the sw360 attachments thing
- This PR has the functionality, where files are being uploaded …
> feat(fossology): v2 endpoints refactor GSoC Phase 1

- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentRepository.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentSearchHandler.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectSearchHandler.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ReleaseRepository.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/UserRepository.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/UserSearchHandler.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/VulnerabilitySearchHandler.java
- backend/moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationRequestRepository.java
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseConnectorCloudant.java
- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/cloudantclient/DatabaseRepositoryCloudantClient.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/component/Sw360ComponentService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/user/Sw360UserService.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/Sw360VulnerabilityService.java
1. Correct pagination sort property names to use actual column names.
2. Remove custom sorting as it is already done by `org.eclipse.sw360.datahandler.resourcelists.ResourceListController#getPaginationResultFromPaginatedList` to avoid duplicate efforts.
Check if sorting still works as expected in following endpoints.
1. /projects
2. /components
3. /users
4. /vulnerabilities
> fix(pagination): use correct sort column

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java
- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/Sw360LicenseService.java
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/LicenseSpecTest.java
- on hitting endpoint /licences/import/SPDX returns 200 with a response body.
Issue: #3249 
@GMishx 
@amritkv 
@rudra-superrr 
- can test via swagger or curl after build
- tested via curl 
Curl Command -- 
```bash
curl -v --max-time 30 -X 'POST' \
'http://127.0.0.1:8080/resource/api/licenses/import/SPDX' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-H 'Authorization: Basic YWRtaW5Ac3czNjAub3JnOjEyMzQ1' \
-d '{}'
```
Output Response Body --
```bash
{
"requestStatus" : "SUCCESS",
"totalAffectedElements" : 699, …
```
> bug(spdx): fixed spdx import format

- rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
This PR fixes a NullPointerException that occurred during license info generation for projects that had linkedProjects set to null.
**Key Enhancements:**
Safely handles both cases
- Projects with linked projects.
- Projects without any linked projects
**Improved the /attachmentUsage API:**
- Made the transitive query parameter is now optional with a default value (false) to prevent 400 Bad Request.
**Bug Fixed:**
NPE when generating license info for projects with null linkedProjects.
> Fix NPE During License Info Generation; Support Projects With and Without Linked Projects

- .github/workflows/build_and_test.yml
- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/VulnerabilityTest.java
Use couchdb container as an action service instead of running it on same container.
> feat(ci): use couchdb as actions service

- backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
- backend/common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
This PR enhances the CycloneDX SBOM import process by adding robust handling for invalid or missing VCS URLs in SBOM components.
- Validation of VCS URLs during SBOM parsing to detect invalid or malformed entries.
- Prevents creation of components with invalid VCS values and categorizes them as invalid VCS components.
- Aggregates and returns import result details, including counts and lists of invalid components, duplicate components, releases, and packages.
- Maintains compatibility with existing CycloneDX import logic.
- Ensures better feedback to users via import result summaries.
**Test it by:**
- Importing SBOM with valid and invalid VCS URLs (CycloneDX XML).
- Verify import results and JSON summary output in Postman.
> fix(sbom-import): handle invalid VCS URLs in SBOM-import

- backend/common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java
Space characters in the VCS URL of SBOM are getting encoded to "plus" due to URL encoding. The VCS URL is to be trimmed before processing.
> fix(CDXImport): Trim VCS URLs before processing

- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/ModerationRequestTest.java
This PR adds the IT for ModerationRequest endpoints.
Summary: Created ModerationRequestTest file and add the integration tests by extending the TestIntegrationBase class.
Current coverage - 87%
@GMishx
How To Test?
Must:
> test(integration): Added ModerationRequest tests in ModerationRequestTest

- rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/integration/DatabaseSanitationTest.java
This PR adds the IT for DatabaseSanitation endpoints.
Summary: Created DatabaseSanitationTest file and add the integration tests by extending the TestIntegrationBase class.
Current coverage - 100%
@GMishx
How To Test?
Must:
> test(integration): Added DatabaseSanitation tests in DatabaseSanitationTest

- libraries/datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
In `isValidDate()`, check if dates are equals or after creating an `>=` check.
Modify a clearing request and send the `requestedClearingDate` with same value as current CR.
> fix(utils): check CR date is equals or after

- third-party/thrift/Dockerfile
Fix the version of Ubuntu Nobel image used to create thrift container.
> fix(docker): use new ubuntu-nobel for thrift
